import { registerStrings } from './i18n';

const ja = {
  'lang.toggle': 'JP',
  'brand.subtitle': '完全合成ドラムマシン',
  'kit.selectTitle': 'キット（音色セット）',
  'status.tapToStart': '画面をタップすると音が出ます',
  'panic.title': '全停止（Esc）',
  'panic.label': '全停止',

  'play.title': '再生 / 停止（Space）',
  'rec.title': 'パッドの演奏をパターンに書き込む（R）',
  'tap.title': 'テンポをタップで入力',
  'pattern.title': 'パターン {name}',
  'song.title': 'ソングモード（パターンを並べて通しで再生）',

  'tab.edit': '打ち込み',
  'tab.pads': 'パッド',
  'tab.voice': '音づくり',
  'tab.mix': 'ミキサー',
  'tab.fx': 'エフェクト',
  'tab.song': 'ソング',
  'tab.demo': 'デモ',
  'tab.export': '書き出し',

  'panel.edit.title': '打ち込み',
  'panel.edit.hint': 'マス目をタップ / 長押しでステップの詳細',
  'ctl.inputVelocity.label': '入力の強さ',
  'vel.ghost': 'ゴースト',
  'vel.normal': 'ノーマル',
  'vel.accent': 'アクセント',
  'ctl.stepCount.label': 'ステップ数',
  'ctl.stepCount.hint': '1〜64。16 = 1小節（16分音符）',
  'ctl.swing.label': 'スウィング',
  'ctl.swing.hint': '50% で均等、62% 前後で三連のハネ',
  'ctl.humanize.label': 'ヒューマナイズ',
  'ctl.humanize.hint': 'タイミングと強さをわずかに揺らす',
  'ctl.subdivision.label': '細かさ',
  'sub.16': '16分',
  'sub.8t': '8分3連',
  'sub.16t': '16分3連',
  'ctl.follow.label': '再生位置を追う',
  'ctl.follow.hint': '長いパターンで自動的に横スクロール',
  'tool.shiftLeft': '◀ ずらす',
  'tool.shiftRight': 'ずらす ▶',
  'tool.double': '倍に伸ばす',
  'tool.duplicate': 'パターンを複製',
  'tool.clearTrack': '選択トラックを消去',
  'tool.clearPattern': 'パターンを消去',
  'tool.undo': '元に戻す',

  'panel.pads.title': 'パッド',
  'panel.pads.hint': 'キーボードの A S D F G H J / Z X C V B N M でも叩けます',
  'pads.note': 'REC を点灯させて再生すると、叩いた音がそのままステップに書き込まれます（自動でマス目に合わせます）。',

  'panel.voice.title': '音づくり — {track}',
  'panel.voice.hint': '左のトラック名を押すと切り替わります',
  'ctl.tune.label': '音程',
  'ctl.tune.hint': '半音単位',
  'ctl.decay.label': '減衰',
  'ctl.decay.hint': '大きいほど長く伸びる',
  'ctl.tone.label': 'トーン',
  'ctl.snap.label': 'アタック',
  'ctl.voiceDrive.label': 'ドライブ',
  'ctl.voiceDrive.hint': 'サチュレーションで太くする',
  'ctl.level.label': '音量',
  'ctl.pan.label': '定位',
  'pan.center': '中央',
  'ctl.reverbSend.label': 'リバーブ送り',
  'ctl.delaySend.label': 'ディレイ送り',
  'ctl.trackLength.label': 'このトラックの長さ',
  'ctl.trackLength.hint': '0 でパターン全体と同じ。別の数にするとポリメーターになります',
  'action.preview': '試聴',
  'action.resetTrack': 'このトラックを初期値に',

  'tonehint.kick': 'アタックの高さ（クリック感）',
  'tonehint.snare': 'ノイズの明るさ',
  'tonehint.clap': '手のあたる高さ',
  'tonehint.metal': '金物の明るさ（高域の量）',
  'tonehint.tom': '打面の張り',
  'tonehint.shaker': '粒の細かさ',
  'tonehint.default': '音色の明るさ',
  'snaphint.kick': 'ビーターのクリック音',
  'snaphint.snare': 'スナッピー（響き線）の量',
  'snaphint.clap': '手の重なり具合',
  'snaphint.tom': '打面のノイズ',
  'snaphint.shaker': '立ち上がりの速さ',
  'snaphint.default': 'アタックのノイズ量',

  'panel.mix.title': 'ミキサー',
  'panel.mix.hint': '音量・定位・センドをまとめて調整します',
  'mini.level': '音量',
  'mini.pan': '定位',

  'panel.fx.title': 'エフェクト',
  'panel.fx.hint': 'マスターの音作りと空間系',
  'ctl.masterVolume.label': 'マスター音量',
  'ctl.masterDrive.label': 'ドライブ',
  'ctl.masterDrive.hint': 'バス全体を軽く歪ませて密度を出す',
  'ctl.glue.label': 'グルー（バスコンプ）',
  'ctl.glue.hint': '全体をまとめて前に出す',
  'ctl.low.label': '低域',
  'ctl.high.label': '高域',
  'ctl.reverbType.label': 'リバーブ',
  'reverbType.none': 'なし',
  'ctl.reverbAmount.label': 'リバーブ量',
  'ctl.delayDivision.label': 'ディレイ（テンポ同期）',
  'delayDivision.none': 'なし',
  'delay.triplet': '3連',
  'delay.dotted': '付点',
  'ctl.delayAmount.label': 'ディレイ量',
  'ctl.feedback.label': 'フィードバック',
  'ctl.pingpong.label': 'ピンポン',
  'ctl.pingpong.hint': '左右交互に返す',

  'panel.song.title': 'ソング',
  'panel.song.hint': 'パターンを並べて曲にします',
  'ctl.songMode.label': 'ソングモードで再生',
  'ctl.songMode.hint': 'この並び順で通して再生します',
  'tool.addBlock': 'ブロックを追加',
  'tool.appendCurrent': '現在のパターンを末尾に',
  'song.summary': '全体で {total} ステップ・約 {seconds} 秒（{bpm} BPM）',

  'panel.demo.title': 'デモ',
  'panel.demo.hint': '読み込むと現在の内容は置き換わります（保存したい場合は先に書き出してください）',
  'demo.meta': '{bpm} BPM / {kit}',
  'action.load': '読み込む',

  'panel.export.title': '書き出し',
  'panel.export.hint': 'すべて端末内で処理します。アップロードは行いません',
  'ctl.exportLoops.label': '繰り返し回数',
  'ctl.exportLoops.hint': 'パターン（またはソング全体）を何回続けて書き出すか',
  'action.exportWav': 'WAV を書き出す',
  'action.exportStems': 'トラック別 WAV（ZIP）',
  'action.exportMidi': 'MIDI を書き出す',
  'action.saveProject': 'プロジェクトを保存',
  'action.loadProject': 'プロジェクトを読み込む',
  'export.note': 'WAV は 48kHz / 24bit ステレオ。書き出した音源は自由に使えます（商用利用可・クレジット不要）。',
  'export.status': '対象：{mode} ／ 長さ 約 {seconds} 秒',
  'export.mode.song': 'ソング全体',
  'export.mode.pattern': 'パターン {name}',

  'status.noUndo': '元に戻せる操作はありません',
  'status.undone': '元に戻しました',
  'status.maxLength': 'これ以上は伸ばせません（最大64ステップ）',
  'status.noEmptyPattern': '空きパターンがありません',
  'status.duplicated': 'パターン {name} に複製しました',

  'inspector.title': '{track} ／ {index} ステップ目',
  'ctl.velocity.label': '強さ',
  'ctl.probability.label': '確率',
  'ctl.roll.label': '連打',
  'ctl.offset.label': 'ずらし',
  'ctl.offset.hint': '1ステップ幅に対する割合',
  'offset.just': 'ジャスト',
  'action.delete': '消す',
  'action.close': '閉じる',

  'status.ready': '準備完了',
  'status.audioInitFailed': '音声を初期化できませんでした',
  'status.stopped': '停止',
  'status.playingSong': 'ソングを再生中',
  'status.playingPattern': 'パターン {name} を再生中',
  'status.recording': '録音中：パッドを叩くと書き込まれます',
  'status.recordingEnded': '録音を終了しました',
  'status.allStopped': '全停止しました',
  'status.tapMore': 'もう数回タップしてください',
  'status.tempo': 'テンポ {bpm} BPM',
  'status.songMode': 'ソングモード',
  'status.patternMode': 'パターンモード',
  'status.kit': 'キット：{name}',
  'status.demoLoaded': 'デモ「{name}」を読み込みました',

  'export.exporting': '書き出し中…',
  'export.wavDone': 'WAV を書き出しました（{size} MB）',
  'export.failed': '書き出しに失敗しました',
  'export.stemsProgress': 'トラック別に書き出し中… ({i}/{total}) {track}',
  'export.stemsDone': '{count} 本のトラックを ZIP にまとめました',
  'export.midiDone': 'MIDI を書き出しました（GM ドラムマップ・チャンネル10）',
  'export.projectSaved': 'プロジェクトを保存しました',
  'export.projectLoaded': 'プロジェクトを読み込みました',
  'export.projectLoadFailed': 'ファイルを読み込めませんでした',

  'mute.title': 'ミュート',
  'solo.title': 'ソロ',

  'track.kick.name': 'キック',
  'track.snare.name': 'スネア',
  'track.clap.name': 'クラップ',
  'track.rim.name': 'リムショット',
  'track.ch.name': 'クローズドハット',
  'track.oh.name': 'オープンハット',
  'track.tom1.name': 'ロータム',
  'track.tom2.name': 'ミドルタム',
  'track.tom3.name': 'ハイタム',
  'track.ride.name': 'ライド',
  'track.crash.name': 'クラッシュ',
  'track.cowbell.name': 'カウベル',
  'track.shaker.name': 'シェイカー',
  'track.perc.name': 'パーカッション',

  'kit.analog.name': 'クラシック・アナログ',
  'kit.analog.desc': '長く伸びる正弦波のキックと金属的なハット。80年代のリズムマシン的な響き',
  'kit.punch.name': 'パンチ・マシン',
  'kit.punch.desc': '短くタイトに詰めた、抜けの良いダンス系キット',
  'kit.acoustic.name': 'アコースティック',
  'kit.acoustic.desc': '胴鳴りとノイズ成分を多めにした、生ドラムに寄せたキット',
  'kit.lofi.name': 'ローファイ・ヒップホップ',
  'kit.lofi.desc': '角を落とした丸い音。少し歪んだキックと控えめなハット',
  'kit.techno.name': 'テクノ・インダストリアル',
  'kit.techno.desc': '歪ませたキックと硬い金物。空間を広くとったハードな音',
  'kit.house.name': 'ハウス',
  'kit.house.desc': '四つ打ち向け。深めのキックと粒立ちの良いハット・クラップ',
  'kit.trap.name': 'トラップ',
  'kit.trap.desc': '長く沈むサブベース級のキックと、細かく刻める短いハット',
  'kit.ambient.name': 'アンビエント',
  'kit.ambient.desc': '柔らかいアタックと長い余韻。静かな曲やIDM向け',

  'room.room.label': 'ルーム',
  'room.plate.label': 'プレート',
  'room.hall.label': 'ホール',
  'room.cavern.label': 'カヴァーン',

  'section.main': 'メイン',
  'section.dev': '展開',
  'section.break': 'ブレイク',
  'section.fill': 'フィル',
  'section.drop': '落とし',
  'section.quiet': '静か',
  'section.roll': '転がし',
  'section.chorus': 'サビ',
  'section.clave': 'クラーベ',
  'section.thicker': '厚く',
  'section.space': '余白',
  'section.converge': '収束',
  'section.basic': '基本',
  'section.climax': 'クライマックス',

  'demo.house.name': 'ディープ・ハウス',
  'demo.house.desc': '四つ打ち + 裏拍のオープンハット。クラブ系の基本形',
  'demo.techno.name': 'ハード・テクノ',
  'demo.techno.desc': '歪んだキックと16分のハット。ミニマルに押し切る',
  'demo.boombap.name': 'ブーンバップ',
  'demo.boombap.desc': 'ハネたゴーストノートと重いスネア。90年代のヒップホップ的な間',
  'demo.trap.name': 'トラップ',
  'demo.trap.desc': 'ハーフタイムのスネアと、細かく転がすハイハットロール',
  'demo.dnb.name': 'ドラムンベース',
  'demo.dnb.desc': '2小節のブレイクビート。速いテンポで走らせる',
  'demo.rock.name': 'エイトビート',
  'demo.rock.desc': 'ロックの基本形。生ドラム寄りのキットで',
  'demo.funk.name': 'ファンク・シャッフル',
  'demo.funk.desc': '強いハネとゴーストノート。スウィング 62%',
  'demo.latin.name': 'ラテン・パーカッション',
  'demo.latin.desc': 'クラーベを軸にしたパーカッシブなリズム',
  'demo.polymeter.name': 'ポリメーター実験',
  'demo.polymeter.desc': 'シェイカー7歩・パーカッション5歩。トラックごとに長さを変えると模様がゆっくり移り変わる',
  'demo.synthpop.name': 'シンセポップ',
  'demo.synthpop.desc': '80年代風。ゲートのかかった硬いスネアとカウベル',

  'demo.tenmon-01.name': '混沌の序章',
  'demo.tenmon-01.desc': '天問 - モーダル・スウィング。ミステリアスで間を活かした一曲目',
  'demo.tenmon-02.name': '誰が空を創ったのか',
  'demo.tenmon-02.desc': '天問 - ミディアム・スウィングの12小節ブルース',
  'demo.tenmon-03.name': '星の回廊',
  'demo.tenmon-03.desc': '天問 - 3拍子のジャズ・ワルツ',
  'demo.tenmon-04.name': '地の果てへ',
  'demo.tenmon-04.desc': '天問 - ボサノヴァ。柔らかいリムとシェイカーで',
  'demo.tenmon-05.name': '問いかける月',
  'demo.tenmon-05.desc': '天問 - バラード。ブラシとライドだけの静けさ',
  'demo.tenmon-06.name': '龍の眠り',
  'demo.tenmon-06.desc': '天問 - ハードバップ。速いテンポで攻める',
  'demo.tenmon-07.name': '見えない橋',
  'demo.tenmon-07.desc': '天問 - アフロキューバン・ジャズ。クラーベとライドの融合',
  'demo.tenmon-08.name': '光と影のあいだ',
  'demo.tenmon-08.desc': '天問 - モーダル・ジャズ。2コードのヴァンプ',
  'demo.tenmon-09.name': '天の川を渡る',
  'demo.tenmon-09.desc': '天問 - アップテンポ・スウィング。リズムチェンジ系',
  'demo.tenmon-10.name': '終わりなき問い',
  'demo.tenmon-10.desc': '天問 - バラード。アルバムを締めくくるエピローグ',
};

const en: typeof ja = {
  'lang.toggle': 'EN',
  'brand.subtitle': 'Fully Synthesized Drum Machine',
  'kit.selectTitle': 'Kit (tone set)',
  'status.tapToStart': 'Tap the screen to make sound',
  'panic.title': 'Stop all (Esc)',
  'panic.label': 'Stop All',

  'play.title': 'Play / Stop (Space)',
  'rec.title': 'Write pad performances into the pattern (R)',
  'tap.title': 'Tap to set tempo',
  'pattern.title': 'Pattern {name}',
  'song.title': 'Song mode (play patterns back to back)',

  'tab.edit': 'Edit',
  'tab.pads': 'Pads',
  'tab.voice': 'Voice',
  'tab.mix': 'Mixer',
  'tab.fx': 'Effects',
  'tab.song': 'Song',
  'tab.demo': 'Demo',
  'tab.export': 'Export',

  'panel.edit.title': 'Edit',
  'panel.edit.hint': 'Tap a cell / long-press for step details',
  'ctl.inputVelocity.label': 'Input Strength',
  'vel.ghost': 'Ghost',
  'vel.normal': 'Normal',
  'vel.accent': 'Accent',
  'ctl.stepCount.label': 'Step Count',
  'ctl.stepCount.hint': '1–64. 16 = one bar (16th notes)',
  'ctl.swing.label': 'Swing',
  'ctl.swing.hint': '50% is even, around 62% gives a triplet feel',
  'ctl.humanize.label': 'Humanize',
  'ctl.humanize.hint': 'Slightly varies timing and strength',
  'ctl.subdivision.label': 'Subdivision',
  'sub.16': '16th',
  'sub.8t': '8th Triplet',
  'sub.16t': '16th Triplet',
  'ctl.follow.label': 'Follow Playhead',
  'ctl.follow.hint': 'Auto-scrolls horizontally for long patterns',
  'tool.shiftLeft': '◀ Shift',
  'tool.shiftRight': 'Shift ▶',
  'tool.double': 'Double Length',
  'tool.duplicate': 'Duplicate Pattern',
  'tool.clearTrack': 'Clear Selected Track',
  'tool.clearPattern': 'Clear Pattern',
  'tool.undo': 'Undo',

  'panel.pads.title': 'Pads',
  'panel.pads.hint': 'Can also be played with A S D F G H J / Z X C V B N M on your keyboard',
  'pads.note': 'With REC lit and playback running, hits are written straight into the steps (automatically snapped to the grid).',

  'panel.voice.title': 'Voice — {track}',
  'panel.voice.hint': 'Click a track name on the left to switch',
  'ctl.tune.label': 'Tune',
  'ctl.tune.hint': 'In semitones',
  'ctl.decay.label': 'Decay',
  'ctl.decay.hint': 'Higher values ring out longer',
  'ctl.tone.label': 'Tone',
  'ctl.snap.label': 'Attack',
  'ctl.voiceDrive.label': 'Drive',
  'ctl.voiceDrive.hint': 'Thickens the sound with saturation',
  'ctl.level.label': 'Level',
  'ctl.pan.label': 'Pan',
  'pan.center': 'Center',
  'ctl.reverbSend.label': 'Reverb Send',
  'ctl.delaySend.label': 'Delay Send',
  'ctl.trackLength.label': 'This Track\'s Length',
  'ctl.trackLength.hint': '0 matches the full pattern. A different number creates a polymeter',
  'action.preview': 'Preview',
  'action.resetTrack': 'Reset This Track to Default',

  'tonehint.kick': 'Attack pitch (click character)',
  'tonehint.snare': 'Noise brightness',
  'tonehint.clap': 'Pitch of the hand contact',
  'tonehint.metal': 'Brightness of the metal (amount of highs)',
  'tonehint.tom': 'Tension of the head',
  'tonehint.shaker': 'Fineness of the grain',
  'tonehint.default': 'Tone brightness',
  'snaphint.kick': 'Beater click sound',
  'snaphint.snare': 'Amount of snappy (snare wire) buzz',
  'snaphint.clap': 'How much the hand claps overlap',
  'snaphint.tom': 'Head noise',
  'snaphint.shaker': 'Speed of the attack',
  'snaphint.default': 'Amount of attack noise',

  'panel.mix.title': 'Mixer',
  'panel.mix.hint': 'Adjust level, pan, and sends all together',
  'mini.level': 'Level',
  'mini.pan': 'Pan',

  'panel.fx.title': 'Effects',
  'panel.fx.hint': 'Master tone-shaping and space effects',
  'ctl.masterVolume.label': 'Master Volume',
  'ctl.masterDrive.label': 'Drive',
  'ctl.masterDrive.hint': 'Lightly distorts the whole bus for extra density',
  'ctl.glue.label': 'Glue (Bus Comp)',
  'ctl.glue.hint': 'Pulls everything together and forward',
  'ctl.low.label': 'Low',
  'ctl.high.label': 'High',
  'ctl.reverbType.label': 'Reverb',
  'reverbType.none': 'None',
  'ctl.reverbAmount.label': 'Reverb Amount',
  'ctl.delayDivision.label': 'Delay (Tempo-Synced)',
  'delayDivision.none': 'None',
  'delay.triplet': 'Triplet',
  'delay.dotted': 'Dotted',
  'ctl.delayAmount.label': 'Delay Amount',
  'ctl.feedback.label': 'Feedback',
  'ctl.pingpong.label': 'Ping-Pong',
  'ctl.pingpong.hint': 'Bounces the repeats left and right',

  'panel.song.title': 'Song',
  'panel.song.hint': 'Arrange patterns into a song',
  'ctl.songMode.label': 'Play in Song Mode',
  'ctl.songMode.hint': 'Plays through in this order',
  'tool.addBlock': 'Add Block',
  'tool.appendCurrent': 'Append Current Pattern',
  'song.summary': '{total} steps total, about {seconds} seconds ({bpm} BPM)',

  'panel.demo.title': 'Demo',
  'panel.demo.hint': 'Loading replaces the current content (export first if you want to keep it)',
  'demo.meta': '{bpm} BPM / {kit}',
  'action.load': 'Load',

  'panel.export.title': 'Export',
  'panel.export.hint': 'Everything is processed on-device. Nothing is uploaded',
  'ctl.exportLoops.label': 'Repeat Count',
  'ctl.exportLoops.hint': 'How many times to loop the pattern (or full song) when exporting',
  'action.exportWav': 'Export WAV',
  'action.exportStems': 'Per-Track WAV (ZIP)',
  'action.exportMidi': 'Export MIDI',
  'action.saveProject': 'Save Project',
  'action.loadProject': 'Load Project',
  'export.note': 'WAV is 48kHz / 24-bit stereo. Exported audio is yours to use freely (commercial use is fine, no credit required).',
  'export.status': 'Target: {mode} / Length: about {seconds}s',
  'export.mode.song': 'Full Song',
  'export.mode.pattern': 'Pattern {name}',

  'status.noUndo': 'There is nothing to undo',
  'status.undone': 'Undone',
  'status.maxLength': 'Cannot extend any further (max 64 steps)',
  'status.noEmptyPattern': 'No empty pattern slots available',
  'status.duplicated': 'Duplicated into Pattern {name}',

  'inspector.title': '{track} / Step {index}',
  'ctl.velocity.label': 'Strength',
  'ctl.probability.label': 'Probability',
  'ctl.roll.label': 'Roll',
  'ctl.offset.label': 'Offset',
  'ctl.offset.hint': 'As a fraction of one step width',
  'offset.just': 'On Grid',
  'action.delete': 'Delete',
  'action.close': 'Close',

  'status.ready': 'Ready',
  'status.audioInitFailed': 'Could not initialize audio',
  'status.stopped': 'Stopped',
  'status.playingSong': 'Playing song',
  'status.playingPattern': 'Playing pattern {name}',
  'status.recording': 'Recording: hit pads to write them in',
  'status.recordingEnded': 'Recording ended',
  'status.allStopped': 'Stopped all sound',
  'status.tapMore': 'Tap a few more times',
  'status.tempo': 'Tempo {bpm} BPM',
  'status.songMode': 'Song mode',
  'status.patternMode': 'Pattern mode',
  'status.kit': 'Kit: {name}',
  'status.demoLoaded': 'Loaded demo "{name}"',

  'export.exporting': 'Exporting…',
  'export.wavDone': 'WAV exported ({size} MB)',
  'export.failed': 'Export failed',
  'export.stemsProgress': 'Exporting per track… ({i}/{total}) {track}',
  'export.stemsDone': 'Bundled {count} tracks into a ZIP',
  'export.midiDone': 'MIDI exported (GM drum map, channel 10)',
  'export.projectSaved': 'Project saved',
  'export.projectLoaded': 'Project loaded',
  'export.projectLoadFailed': 'Could not load the file',

  'mute.title': 'Mute',
  'solo.title': 'Solo',

  'track.kick.name': 'Kick',
  'track.snare.name': 'Snare',
  'track.clap.name': 'Clap',
  'track.rim.name': 'Rimshot',
  'track.ch.name': 'Closed Hat',
  'track.oh.name': 'Open Hat',
  'track.tom1.name': 'Low Tom',
  'track.tom2.name': 'Mid Tom',
  'track.tom3.name': 'High Tom',
  'track.ride.name': 'Ride',
  'track.crash.name': 'Crash',
  'track.cowbell.name': 'Cowbell',
  'track.shaker.name': 'Shaker',
  'track.perc.name': 'Percussion',

  'kit.analog.name': 'Classic Analog',
  'kit.analog.desc': 'A long sine-wave kick and metallic hats. That 80s drum machine sound',
  'kit.punch.name': 'Punch Machine',
  'kit.punch.desc': 'Short and tight, a cutting dance-music kit',
  'kit.acoustic.name': 'Acoustic',
  'kit.acoustic.desc': 'More shell resonance and noise, closer to real drums',
  'kit.lofi.name': 'Lo-Fi Hip-Hop',
  'kit.lofi.desc': 'Rounded-off, soft tone. A slightly distorted kick and understated hats',
  'kit.techno.name': 'Techno Industrial',
  'kit.techno.desc': 'A distorted kick and hard metal. A hard sound with wide-open space',
  'kit.house.name': 'House',
  'kit.house.desc': 'Built for four-on-the-floor. A deep kick with crisp hats and claps',
  'kit.trap.name': 'Trap',
  'kit.trap.desc': 'A deep, sinking sub-bass-class kick and short, choppable hats',
  'kit.ambient.name': 'Ambient',
  'kit.ambient.desc': 'A soft attack and long tail. Great for quiet tracks and IDM',

  'room.room.label': 'Room',
  'room.plate.label': 'Plate',
  'room.hall.label': 'Hall',
  'room.cavern.label': 'Cavern',

  'section.main': 'Main',
  'section.dev': 'Build',
  'section.break': 'Break',
  'section.fill': 'Fill',
  'section.drop': 'Drop',
  'section.quiet': 'Quiet',
  'section.roll': 'Roll',
  'section.chorus': 'Chorus',
  'section.clave': 'Clave',
  'section.thicker': 'Thicker',
  'section.space': 'Space',
  'section.converge': 'Converge',
  'section.basic': 'Basic',
  'section.climax': 'Climax',

  'demo.house.name': 'Deep House',
  'demo.house.desc': 'Four-on-the-floor plus offbeat open hats. The basic clubbing groove',
  'demo.techno.name': 'Hard Techno',
  'demo.techno.desc': 'A distorted kick and 16th-note hats. Grinding it out, minimal-style',
  'demo.boombap.name': 'Boom Bap',
  'demo.boombap.desc': 'Swung ghost notes and a heavy snare. That 90s hip-hop pocket',
  'demo.trap.name': 'Trap',
  'demo.trap.desc': 'A half-time snare with fast, rolling hi-hats',
  'demo.dnb.name': 'Drum and Bass',
  'demo.dnb.desc': 'A two-bar breakbeat driven at a fast tempo',
  'demo.rock.name': 'Eighth-Note Rock',
  'demo.rock.desc': 'The basic rock groove, played on an acoustic-leaning kit',
  'demo.funk.name': 'Funk Shuffle',
  'demo.funk.desc': 'Heavy swing and ghost notes. Swing set to 62%',
  'demo.latin.name': 'Latin Percussion',
  'demo.latin.desc': 'A percussive rhythm built around a clave',
  'demo.polymeter.name': 'Polymeter Experiment',
  'demo.polymeter.desc': 'Shaker in 7 steps, percussion in 5. Changing each track\'s length slowly shifts the pattern',
  'demo.synthpop.name': 'Synthpop',
  'demo.synthpop.desc': '80s style. A gated, punchy snare and cowbell',

  'demo.tenmon-01.name': 'Prologue: Chaos',
  'demo.tenmon-01.desc': 'Tenmon (天問) - Modal swing, mysterious and sparse. Track 1 of the album',
  'demo.tenmon-02.name': 'Who Made the Sky?',
  'demo.tenmon-02.desc': 'Tenmon (天問) - A medium-swing 12-bar jazz blues',
  'demo.tenmon-03.name': 'Corridor of Stars',
  'demo.tenmon-03.desc': 'Tenmon (天問) - A jazz waltz in 3/4',
  'demo.tenmon-04.name': 'To the Edge of the Earth',
  'demo.tenmon-04.desc': 'Tenmon (天問) - Bossa nova, soft rim clicks and shaker',
  'demo.tenmon-05.name': 'The Questioning Moon',
  'demo.tenmon-05.desc': 'Tenmon (天問) - Ballad. Just brushes and a whispering ride',
  'demo.tenmon-06.name': 'Sleep of the Dragon',
  'demo.tenmon-06.desc': 'Tenmon (天問) - Hard bop, driving at a fast tempo',
  'demo.tenmon-07.name': 'The Invisible Bridge',
  'demo.tenmon-07.desc': 'Tenmon (天問) - Afro-Cuban jazz, clave fused with a swung ride',
  'demo.tenmon-08.name': 'Between Light and Shadow',
  'demo.tenmon-08.desc': 'Tenmon (天問) - Modal jazz over a two-chord vamp',
  'demo.tenmon-09.name': 'Crossing the Milky Way',
  'demo.tenmon-09.desc': 'Tenmon (天問) - Up-tempo swing, rhythm-changes family',
  'demo.tenmon-10.name': 'Endless Question',
  'demo.tenmon-10.desc': 'Tenmon (天問) - Ballad epilogue that closes the album',
};

registerStrings(ja, en);
