import { registerStrings } from './i18n';

const ja = {
  'lang.toggle': 'EN',
  'brand.sub': '日本語 歌声シンセサイザー',
  'transport.play': '▶ 再生',
  'transport.stop': '■ 停止',
  'rewind.title': '先頭へ',
  'action.export': '書き出し',
  'action.save': '保存',
  'action.load': '読込',
  'status.initial': 'ピアノロールに音符を書いて、再生してみてください',
  'status.credit': 'サンプル音源なし・広告なし・オフライン動作',

  'tool.pen.label': '✏️ ペン',
  'tool.pen.hint': 'クリックで音符を追加',
  'tool.select.label': '✋ 選択',
  'tool.select.hint': 'ドラッグで画面移動・Shiftで範囲選択',
  'tool.erase.label': '🧽 消す',
  'tool.erase.hint': 'クリックで音符を削除',
  'roll.snap.label': 'スナップ',
  'roll.length.label': '長さ',
  'length.2beat': '2拍',
  'length.1beat': '1拍',
  'length.eighth': '8分',
  'length.sixteenth': '16分',
  'snap.quarter': '1/4',
  'snap.eighth': '1/8',
  'snap.sixteenth': '1/16',
  'snap.triplet': '3連',
  'snap.none': 'なし',
  'roll.selectAll': '全選択',
  'roll.deleteSelection': '削除',

  'tab.voice': '声',
  'tab.expression': '歌い方',
  'tab.accomp': '伴奏',
  'tab.mix': 'ミックス',
  'tab.record': '録音',
  'tab.song': '曲',

  'section.voice.title': 'ボイス',
  'section.voice.hint': '声帯と声道の設定一式',
  'voice.range': '得意音域 {lo} 〜 {hi}',
  'flash.voiceSwitched': '{name} に切り替えました',
  'section.toneAdjust.title': '声色の調整',
  'section.toneAdjust.hint': 'プリセットを土台に微調整できます',
  'ctl.tract.label': '声の高さ感（声道の長さ）',
  'ctl.tract.hint': '大きいほど幼く・女性的に、小さいほど太く・男性的になります',
  'ctl.brightness.label': '明るさ',
  'ctl.breath.label': '息（ブレス感）',
  'ctl.tension.label': '声の張り',
  'ctl.tension.hint': '強いほど前に出る硬い声、弱いほど柔らかい声',
  'ctl.nasality.label': '鼻にかかる量',
  'ctl.body.label': '声の太さ',
  'ctl.growl.label': 'エッジ（うなり）',
  'ctl.growl.hint': 'ロック系のかすれ・パワー感',
  'ctl.a4.label': '基準ピッチ A4',

  'section.vibrato.title': 'ビブラート',
  'ctl.vibDepth.label': '深さ',
  'unit.cents': 'セント',
  'ctl.vibRate.label': '速さ',
  'ctl.vibDelay.label': 'かかり始め',
  'ctl.vibDelay.hint': '音符の長さに対する位置。遅いほど「まっすぐ伸ばしてから揺れる」',
  'section.legato.title': '音のつなぎ',
  'ctl.portamento.label': 'ポルタメント',
  'ctl.portamento.hint': '次の音へ音程が滑る時間',
  'ctl.scoop.label': 'しゃくり',
  'ctl.scoop.hint': 'フレーズ頭を下からすくい上げる量',
  'ctl.consonant.label': '子音の長さ',
  'ctl.consonant.hint': '長いほど言葉がはっきりする',
  'unit.times': '倍',
  'section.dynamics.title': '強弱と息',
  'ctl.dynamics.label': '抑揚',
  'ctl.dynamics.hint': '音符ごとの強さ（ベロシティ）の効き',
  'ctl.attack.label': '立ち上がり',
  'ctl.release.label': '語尾の消え方',
  'ctl.breathNoise.label': 'ブレス（息継ぎ音）',
  'ctl.breathNoise.hint': 'フレーズの前に入る息の音',
  'ctl.drift.label': 'ゆらぎ',
  'ctl.drift.hint': '人の声らしい微妙なピッチの揺れ',

  'style.off': 'なし',
  'style.ballad': 'バラード',
  'style.pop': 'ポップ',
  'style.arpeggio': 'アルペジオ',
  'style.pad': 'パッド',
  'style.band': 'バンド',
  'section.accompStyle.title': '伴奏スタイル',
  'section.accompStyle.hint': 'コード進行から自動で伴奏を作ります',
  'flash.accompChanged': '伴奏を変更',
  'ctl.accompLevel.label': '伴奏の音量',
  'section.chords.title': 'コード進行',
  'section.chords.hint': '1行 = 1小節。1行に複数書くと小節を分割します',
  'field.chords.label': 'コード',
  'flash.chordsChanged': 'コードを変更',
  'chords.placeholder': '例）C / Am7 / F G / G7sus4 / F#m7b5 / C/E',

  'section.balance.title': 'バランス',
  'ctl.masterVolume.label': 'マスター音量',
  'ctl.vocalLevel.label': 'ボーカル',
  'ctl.accompLevel2.label': '伴奏',
  'section.mixTone.title': '音作り',
  'ctl.mixTone.label': 'トーン（明るさ）',
  'ctl.lowCut.label': '低域の整理',
  'ctl.lowCut.hint': 'こもりを取ってボーカルを前に出します',
  'ctl.comp.label': 'コンプレッサー',
  'ctl.comp.hint': '音量のばらつきをそろえます',
  'section.space.title': '空間',
  'ctl.doubler.label': 'ダブラー（厚み）',
  'ctl.doubler.hint': '少しずらした声を左右に重ねます',
  'ctl.width.label': '広がり',
  'ctl.reverbType.label': 'リバーブ',
  'ctl.reverbMix.label': 'リバーブ量',
  'ctl.delayMix.label': 'ディレイ量',
  'ctl.delayBeats.label': 'ディレイの間隔',
  'delaybeats.16': '16分',
  'delaybeats.8': '8分',
  'delaybeats.dotted8': '付点8分',
  'delaybeats.4': '4分',
  'section.reset.title': '初期化',
  'action.resetMix': 'ミックスを既定値に戻す',
  'flash.mixReset': 'ミックスを戻しました',

  'section.micRecord.title': 'マイクから録音',
  'section.micRecord.hint': '歌うと音符になってピアノロールへ入ります',
  'mic.unsupported': 'この端末ではマイクを使えません。HTTPS で開いているか確かめてください。',
  'record.stopAndImport': '■ 停止して取り込む',
  'record.start': '● 録音開始',
  'mic.stopMonitor': 'マイクの確認をやめる',
  'mic.checkMic': 'マイクを確かめる',
  'mic.monitorHint': '声を出すと上のバーが動きます。動かないときは端末のマイク設定をご確認ください。',
  'section.recordSettings.title': '録音の設定',
  'section.recordSettings.hint': 'ハウリングを避けるため、イヤホンの使用をおすすめします',
  'ctl.countIn.label': 'カウントイン',
  'ctl.countIn.hint': '1小節分クリックを鳴らしてから録音を始めます',
  'ctl.metronomeDuringRec.label': '録音中もクリックを鳴らす',
  'ctl.trimStart.label': '最初の音を先頭に詰める',
  'ctl.trimStart.hint': 'カウントインに合わせて歌うときはオフにしてください',
  'ctl.insertAt.label': '取り込む位置',
  'insertAt.start': '先頭',
  'insertAt.playhead': '再生位置',
  'insertAt.end': '曲の最後',
  'ctl.snapNote.label': '音符の位置合わせ',
  'ctl.sensitivity.label': '感度',
  'ctl.sensitivity.hint': '音符が抜けるときは上げ、雑音を拾うときは下げてください',
  'ctl.lyricMode.label': '歌詞の付け方',
  'lyricMode.speech': '言葉を聞き取る',
  'lyricMode.vowel': '母音を推定',
  'lyricMode.ra': '「ら」',
  'speech.supportedHint': 'ブラウザの音声認識を使います（インターネット接続が必要です）。聞き取れないときは母音の推定に切り替わります。',
  'speech.unsupportedHint': 'この端末は音声認識に対応していません。母音の推定で歌詞を付けます。',
  'vowel.hint': '声の響きから あいうえお を推定します（オフラインで動きます）。',
  'section.lastRecording.title': '最後の録音',
  'lastRecording.subtitle': '{seconds} 秒',
  'label.heardWords': '聞き取った言葉',
  'action.reimport': 'この録音をもう一度取り込む',
  'reimport.hint': '感度や位置合わせを変えてから押すと、設定し直した結果を追加できます。',
  'section.recordTips.title': 'うまく取り込むコツ',
  'tip.1': '「ら・ら・ら」のように音を切って歌うと、音符に分かれやすくなります。',
  'tip.2': 'カウントインのクリックに合わせて歌うと、小節の位置がそろいます。',
  'tip.3': '取り込んだ音符は普通の音符です。ピアノロールで自由に直せます。',
  'tip.4': '取り込みすぎたときは Ctrl+Z（元に戻す）で戻せます。',

  'status.recordingStop': '録音中です。歌い終わったら停止を押してください',
  'status.analyzing': '解析しています…',
  'status.pressToRecord': 'ボタンを押すとマイクの使用を尋ねます',

  'status.audioReady': '準備ができました',
  'status.audioError': 'オーディオを開始できません: {err}',
  'status.noNotes': '音符がありません。ピアノロールに書き込んでください',
  'status.playing': '再生中',
  'flash.undone': '元に戻しました',
  'flash.redone': 'やり直しました',
  'status.micUnavailable': 'マイクを使えません: {err}',
  'status.micMonitoring': 'マイク確認中… 現在 {peak}％ ／ 最大 {max}％',
  'status.requestMic': 'マイクの使用を許可してください…',
  'status.countIn': 'カウントイン…',
  'status.transcribing': '聞き取った言葉をまとめています…',
  'status.recordingTooShort': '録音が短すぎます。もう一度お試しください',
  'status.noMicSignal': 'マイクから音が入っていませんでした。端末のマイクの許可・別アプリでの使用・外部マイクの接続をご確認ください',
  'record.levelNote': '録音 {seconds} 秒 ／ 最大音量 {peak}％（平均 {rms}％）',
  'status.analyzingProgress': '解析しています… {pct}%',
  'status.analyzeFailed': '解析できませんでした: {err}',
  'status.noNotesExtracted': '音符を取り出せませんでした。「あー」と声を伸ばして歌うと拾いやすくなります（話し声や小さすぎる声は音程が取れません）',
  'flash.notesImported': '{count} 音符を取り込みました{lyricNote}',
  'lyricNote.suffix': '・歌詞 {n} 文字',
  'error.micNotAllowed': 'マイクの使用が許可されませんでした',
  'error.micNotFound': 'マイクが見つかりません',

  'section.songSettings.title': '曲の設定',
  'field.title.label': '曲名',
  'title.untitled': '無題',
  'field.tempo.label': 'テンポ（BPM）',
  'flash.tempoChanged': 'テンポを変更',
  'field.beatsPerBar.label': '1小節の拍数',
  'flash.timeSigChanged': '拍子を変更',
  'action.semitoneDown': '半音下げ',
  'action.semitoneUp': '半音上げ',
  'action.octaveDown': '1オクターブ下',
  'action.octaveUp': '1オクターブ上',
  'section.lyricBulk.title': '歌詞のまとめ入力',
  'section.lyricBulk.hint': 'ひらがな・カタカナ・ローマ字で書くと、先頭の音符から順に割り当てます',
  'field.lyrics.label': '歌詞',
  'lyrics.placeholder': '例）よぞらに ひかる ほしのこえ（空白は息継ぎの位置になります）',
  'action.fillFromStart': '先頭から流し込む',
  'flash.lyricsApplied': '{n} 音符に歌詞を入れました',
  'action.fillFromSelected': '選択した音符から',
  'status.selectNoteFirst': '先に音符を選んでください',
  'section.demoSongs.title': 'デモ曲',
  'section.demoSongs.hint': 'すべてこのアプリのための書き下ろし（オリジナル）です',
  'flash.demoLoaded': '{title} を読み込みました',
  'section.files.title': 'ファイル',
  'action.newSong': '新しい曲',
  'confirm.discardSong': '編集中の曲を破棄して新しい曲を作りますか？',
  'flash.newSongCreated': '新しい曲を作りました',
  'action.saveProject': 'プロジェクトを保存',
  'action.loadProject': 'プロジェクトを読込',
  'section.about.title': 'このアプリについて',
  'about.text': '音声はすべてその場で計算して作っています（録音素材・外部ライブラリ・課金・広告はありません）。書き出した音源は自由に配信・販売に使えます。',
  'action.privacy': 'プライバシー',

  'inspector.hint': 'ペンで音符を追加 → ダブルクリック（またはEnter）で歌詞を入力できます',
  'inspector.singleNote': '{note} ・ {lyric}',
  'inspector.multiSelect': '{count} 音を選択中',
  'field.lyric.label': '歌詞',
  'flash.lyricChanged': '歌詞を変更',
  'inline.velocity': '強さ',
  'inline.vibrato': 'ビブラート',
  'flash.breathOn': 'ブレスを入れました',
  'flash.breathOff': 'ブレスを外しました',
  'check.breathHere': 'ここでブレス',
  'action.listenNote': 'この音を聴く',

  'menu.wavMix': 'WAV（ミックス）',
  'menu.wavVocal': 'WAV（ボーカルのみ）',
  'menu.wavAccomp': 'WAV（伴奏のみ）',
  'menu.midiLyrics': 'MIDI（歌詞つき）',
  'menu.projectJson': 'プロジェクト（JSON）',
  'status.noExportContent': '書き出す内容がありません',
  'status.exportingWav': 'WAV を書き出しています…',
  'status.wavExported': 'WAV を書き出しました',
  'status.exportFailed': '書き出しに失敗しました: {err}',
  'status.midiExported': 'MIDI を書き出しました',
  'status.projectSaved': 'プロジェクトを保存しました',
  'status.invalidProject': '読み込めるプロジェクトではありませんでした',
  'flash.projectLoaded': 'プロジェクトを読み込みました',

  'roll.measureLabel': '小節',
  'roll.noteDeleted': '音符を削除',
  'roll.noteMoved': '音符を移動',
  'roll.lengthChanged': '長さを変更',
  'roll.noteAdded': '音符を追加',

  'voice.yoi.name': '宵（よい）',
  'voice.yoi.description': '透明感のある女性ポップ・ボーカル。まっすぐ伸びる中高音。',
  'voice.mio.name': '澪（みお）',
  'voice.mio.description': 'クラシック寄りの女性ソプラノ。深いビブラートとレガート。',
  'voice.akari.name': '燈（あかり）',
  'voice.akari.description': '明るく前に出るキュートな声。アップテンポの曲に。',
  'voice.nagi.name': '凪（なぎ）',
  'voice.nagi.description': '中性的なウィスパー・ボイス。息成分が多く、静かな曲に合う。',
  'voice.sou.name': '蒼（そう）',
  'voice.sou.description': '素直な男性テノール。合唱にもポップスにも。',
  'voice.riku.name': '陸（りく）',
  'voice.riku.description': '少しハスキーな男性ポップ。語尾のエッジが効く。',
  'voice.hibiki.name': '響（ひびき）',
  'voice.hibiki.description': '太く低い男性バリトン。コーラスの土台に。',
  'voice.kotori.name': '小鳥（ことり）',
  'voice.kotori.description': '子どもらしい高くて軽い声。童謡や合いの手に。',

  'room.off.label': 'なし',
  'room.room.label': 'ルーム',
  'room.plate.label': 'プレート',
  'room.hall.label': 'ホール',
  'room.church.label': '大聖堂',

  'demo.hoshi.title': '星のことば',
  'demo.hoshi.subtitle': 'しっとりしたバラード｜宵',
  'demo.asahi.title': 'はしれ、あさひ',
  'demo.asahi.subtitle': '疾走するポップ｜燈',
  'demo.minamo.title': 'みなもの うた',
  'demo.minamo.subtitle': '静かなアルペジオ｜凪',
  'demo.yuki.title': 'ゆきの こもりうた',
  'demo.yuki.subtitle': '3拍子の子守唄｜澪',
  'demo.machi.title': 'まちの あかり',
  'demo.machi.subtitle': '夜のシティポップ｜陸',
  'demo.akatsuki.title': 'あかつきの こえ',
  'demo.akatsuki.subtitle': '低音の讃歌｜響',

  'song.newSongTitle': '新しい曲',
};

const en: typeof ja = {
  'lang.toggle': 'JP',
  'brand.sub': 'Japanese Singing Voice Synthesizer',
  'transport.play': '▶ Play',
  'transport.stop': '■ Stop',
  'rewind.title': 'Go to Start',
  'action.export': 'Export',
  'action.save': 'Save',
  'action.load': 'Load',
  'status.initial': 'Write some notes in the piano roll and try playing them',
  'status.credit': 'No sample audio, no ads, works offline',

  'tool.pen.label': '✏️ Pen',
  'tool.pen.hint': 'Click to add a note',
  'tool.select.label': '✋ Select',
  'tool.select.hint': 'Drag to pan, Shift to box-select',
  'tool.erase.label': '🧽 Erase',
  'tool.erase.hint': 'Click to delete a note',
  'roll.snap.label': 'Snap',
  'roll.length.label': 'Length',
  'length.2beat': '2 beats',
  'length.1beat': '1 beat',
  'length.eighth': '8th',
  'length.sixteenth': '16th',
  'snap.quarter': '1/4',
  'snap.eighth': '1/8',
  'snap.sixteenth': '1/16',
  'snap.triplet': 'Triplet',
  'snap.none': 'None',
  'roll.selectAll': 'Select All',
  'roll.deleteSelection': 'Delete',

  'tab.voice': 'Voice',
  'tab.expression': 'Expression',
  'tab.accomp': 'Backing',
  'tab.mix': 'Mix',
  'tab.record': 'Record',
  'tab.song': 'Song',

  'section.voice.title': 'Voice',
  'section.voice.hint': 'A full set of vocal cord and vocal tract settings',
  'voice.range': 'Best range {lo} – {hi}',
  'flash.voiceSwitched': 'Switched to {name}',
  'section.toneAdjust.title': 'Tone Adjustment',
  'section.toneAdjust.hint': 'Fine-tune on top of the preset',
  'ctl.tract.label': 'Pitch Character (Vocal Tract Length)',
  'ctl.tract.hint': 'Higher is younger/more feminine, lower is thicker/more masculine',
  'ctl.brightness.label': 'Brightness',
  'ctl.breath.label': 'Breath (Breathiness)',
  'ctl.tension.label': 'Vocal Tension',
  'ctl.tension.hint': 'Stronger gives a forward, hard voice; weaker gives a soft voice',
  'ctl.nasality.label': 'Nasality',
  'ctl.body.label': 'Voice Thickness',
  'ctl.growl.label': 'Edge (Growl)',
  'ctl.growl.hint': 'Rock-style rasp and power',
  'ctl.a4.label': 'Reference Pitch A4',

  'section.vibrato.title': 'Vibrato',
  'ctl.vibDepth.label': 'Depth',
  'unit.cents': 'cents',
  'ctl.vibRate.label': 'Rate',
  'ctl.vibDelay.label': 'Onset',
  'ctl.vibDelay.hint': 'Position relative to note length. Later means "hold straight, then wobble."',
  'section.legato.title': 'Note Transitions',
  'ctl.portamento.label': 'Portamento',
  'ctl.portamento.hint': 'Time to glide to the next pitch',
  'ctl.scoop.label': 'Scoop',
  'ctl.scoop.hint': 'How much the start of a phrase scoops up from below',
  'ctl.consonant.label': 'Consonant Length',
  'ctl.consonant.hint': 'Longer makes words clearer',
  'unit.times': 'x',
  'section.dynamics.title': 'Dynamics & Breath',
  'ctl.dynamics.label': 'Expression',
  'ctl.dynamics.hint': 'How much each note\'s velocity affects loudness',
  'ctl.attack.label': 'Attack',
  'ctl.release.label': 'Release',
  'ctl.breathNoise.label': 'Breath (Intake Sound)',
  'ctl.breathNoise.hint': 'The breath sound before a phrase',
  'ctl.drift.label': 'Drift',
  'ctl.drift.hint': 'Subtle, human-like pitch wandering',

  'style.off': 'None',
  'style.ballad': 'Ballad',
  'style.pop': 'Pop',
  'style.arpeggio': 'Arpeggio',
  'style.pad': 'Pad',
  'style.band': 'Band',
  'section.accompStyle.title': 'Backing Style',
  'section.accompStyle.hint': 'Automatically builds backing from the chord progression',
  'flash.accompChanged': 'Backing changed',
  'ctl.accompLevel.label': 'Backing Volume',
  'section.chords.title': 'Chord Progression',
  'section.chords.hint': 'One line = one bar. Multiple chords on a line split the bar.',
  'field.chords.label': 'Chords',
  'flash.chordsChanged': 'Chords changed',
  'chords.placeholder': 'e.g. C / Am7 / F G / G7sus4 / F#m7b5 / C/E',

  'section.balance.title': 'Balance',
  'ctl.masterVolume.label': 'Master Volume',
  'ctl.vocalLevel.label': 'Vocal',
  'ctl.accompLevel2.label': 'Backing',
  'section.mixTone.title': 'Tone Shaping',
  'ctl.mixTone.label': 'Tone (Brightness)',
  'ctl.lowCut.label': 'Low-End Cleanup',
  'ctl.lowCut.hint': 'Removes muddiness to bring the vocal forward',
  'ctl.comp.label': 'Compressor',
  'ctl.comp.hint': 'Evens out volume variation',
  'section.space.title': 'Space',
  'ctl.doubler.label': 'Doubler (Thickness)',
  'ctl.doubler.hint': 'Layers a slightly offset voice left and right',
  'ctl.width.label': 'Width',
  'ctl.reverbType.label': 'Reverb',
  'ctl.reverbMix.label': 'Reverb Amount',
  'ctl.delayMix.label': 'Delay Amount',
  'ctl.delayBeats.label': 'Delay Interval',
  'delaybeats.16': '16th',
  'delaybeats.8': '8th',
  'delaybeats.dotted8': 'Dotted 8th',
  'delaybeats.4': 'Quarter',
  'section.reset.title': 'Reset',
  'action.resetMix': 'Reset Mix to Defaults',
  'flash.mixReset': 'Mix reset',

  'section.micRecord.title': 'Record from Microphone',
  'section.micRecord.hint': 'Sing and it becomes notes in the piano roll',
  'mic.unsupported': 'The microphone is not available on this device. Check that the page is open over HTTPS.',
  'record.stopAndImport': '■ Stop & Import',
  'record.start': '● Start Recording',
  'mic.stopMonitor': 'Stop Checking Mic',
  'mic.checkMic': 'Check Microphone',
  'mic.monitorHint': 'The bar above moves when you make sound. If it doesn\'t, check your device\'s microphone settings.',
  'section.recordSettings.title': 'Recording Settings',
  'section.recordSettings.hint': 'Headphones are recommended to avoid feedback',
  'ctl.countIn.label': 'Count-In',
  'ctl.countIn.hint': 'Clicks for one bar before recording starts',
  'ctl.metronomeDuringRec.label': 'Click During Recording',
  'ctl.trimStart.label': 'Trim to First Note',
  'ctl.trimStart.hint': 'Turn off when singing along with the count-in',
  'ctl.insertAt.label': 'Insert Position',
  'insertAt.start': 'Start',
  'insertAt.playhead': 'Playhead',
  'insertAt.end': 'End of Song',
  'ctl.snapNote.label': 'Note Snapping',
  'ctl.sensitivity.label': 'Sensitivity',
  'ctl.sensitivity.hint': 'Raise if notes are missed, lower if it picks up noise',
  'ctl.lyricMode.label': 'Lyric Assignment',
  'lyricMode.speech': 'Recognize Speech',
  'lyricMode.vowel': 'Estimate Vowels',
  'lyricMode.ra': '"Ra"',
  'speech.supportedHint': 'Uses your browser\'s speech recognition (requires an internet connection). Falls back to vowel estimation if it can\'t make out the words.',
  'speech.unsupportedHint': 'This device does not support speech recognition. Lyrics will be assigned by vowel estimation.',
  'vowel.hint': 'Estimates a/i/u/e/o from the timbre of your voice (works offline).',
  'section.lastRecording.title': 'Last Recording',
  'lastRecording.subtitle': '{seconds}s',
  'label.heardWords': 'Recognized Words',
  'action.reimport': 'Import This Recording Again',
  'reimport.hint': 'Press this after changing sensitivity or position to add the result with the new settings.',
  'section.recordTips.title': 'Tips for a Clean Recording',
  'tip.1': 'Singing distinct syllables, like "la, la, la," makes it easier to split into separate notes.',
  'tip.2': 'Singing in time with the count-in click keeps the bars aligned.',
  'tip.3': 'Imported notes are ordinary notes — you can freely edit them in the piano roll.',
  'tip.4': 'If too much gets imported, undo with Ctrl+Z.',

  'status.recordingStop': 'Recording. Press stop when you\'re done singing.',
  'status.analyzing': 'Analyzing…',
  'status.pressToRecord': 'Press the button to request microphone access',

  'status.audioReady': 'Ready',
  'status.audioError': 'Could not start audio: {err}',
  'status.noNotes': 'There are no notes. Write some in the piano roll.',
  'status.playing': 'Playing',
  'flash.undone': 'Undone',
  'flash.redone': 'Redone',
  'status.micUnavailable': 'Could not use the microphone: {err}',
  'status.micMonitoring': 'Checking mic… now {peak}% / peak {max}%',
  'status.requestMic': 'Please allow microphone access…',
  'status.countIn': 'Count-in…',
  'status.transcribing': 'Compiling the recognized words…',
  'status.recordingTooShort': 'The recording is too short. Please try again.',
  'status.noMicSignal': 'No signal came from the microphone. Check the device\'s mic permission, whether another app is using it, and any external mic connection.',
  'record.levelNote': 'Recording {seconds}s / peak {peak}% (average {rms}%)',
  'status.analyzingProgress': 'Analyzing… {pct}%',
  'status.analyzeFailed': 'Could not analyze: {err}',
  'status.noNotesExtracted': 'Could not extract any notes. Try singing sustained "ah" sounds — spoken voice or very quiet singing can\'t be pitch-tracked.',
  'flash.notesImported': 'Imported {count} notes{lyricNote}',
  'lyricNote.suffix': ', {n} lyric characters',
  'error.micNotAllowed': 'Microphone access was not granted',
  'error.micNotFound': 'No microphone was found',

  'section.songSettings.title': 'Song Settings',
  'field.title.label': 'Title',
  'title.untitled': 'Untitled',
  'field.tempo.label': 'Tempo (BPM)',
  'flash.tempoChanged': 'Tempo changed',
  'field.beatsPerBar.label': 'Beats per Bar',
  'flash.timeSigChanged': 'Time signature changed',
  'action.semitoneDown': 'Semitone Down',
  'action.semitoneUp': 'Semitone Up',
  'action.octaveDown': 'Octave Down',
  'action.octaveUp': 'Octave Up',
  'section.lyricBulk.title': 'Bulk Lyric Entry',
  'section.lyricBulk.hint': 'Write in hiragana, katakana, or romaji and it will be assigned starting from the first note',
  'field.lyrics.label': 'Lyrics',
  'lyrics.placeholder': 'e.g. yozorani hikaru hoshinokoe (spaces become breath positions)',
  'action.fillFromStart': 'Fill From the Start',
  'flash.lyricsApplied': 'Applied lyrics to {n} notes',
  'action.fillFromSelected': 'From Selected Note',
  'status.selectNoteFirst': 'Select a note first',
  'section.demoSongs.title': 'Demo Songs',
  'section.demoSongs.hint': 'All written especially for this app (original)',
  'flash.demoLoaded': 'Loaded {title}',
  'section.files.title': 'File',
  'action.newSong': 'New Song',
  'confirm.discardSong': 'Discard the current song and start a new one?',
  'flash.newSongCreated': 'Created a new song',
  'action.saveProject': 'Save Project',
  'action.loadProject': 'Load Project',
  'section.about.title': 'About This App',
  'about.text': 'All audio is computed on the fly (no recorded material, external libraries, purchases, or ads). Exported audio is yours to distribute and sell freely.',
  'action.privacy': 'Privacy',

  'inspector.hint': 'Add a note with the pen tool → double-click (or press Enter) to type its lyric',
  'inspector.singleNote': '{note} · {lyric}',
  'inspector.multiSelect': '{count} notes selected',
  'field.lyric.label': 'Lyric',
  'flash.lyricChanged': 'Lyric changed',
  'inline.velocity': 'Strength',
  'inline.vibrato': 'Vibrato',
  'flash.breathOn': 'Added a breath',
  'flash.breathOff': 'Removed the breath',
  'check.breathHere': 'Breath here',
  'action.listenNote': 'Listen to This Note',

  'menu.wavMix': 'WAV (Mix)',
  'menu.wavVocal': 'WAV (Vocal Only)',
  'menu.wavAccomp': 'WAV (Backing Only)',
  'menu.midiLyrics': 'MIDI (with Lyrics)',
  'menu.projectJson': 'Project (JSON)',
  'status.noExportContent': 'There is nothing to export',
  'status.exportingWav': 'Exporting WAV…',
  'status.wavExported': 'WAV exported',
  'status.exportFailed': 'Export failed: {err}',
  'status.midiExported': 'MIDI exported',
  'status.projectSaved': 'Project saved',
  'status.invalidProject': 'This is not a loadable project',
  'flash.projectLoaded': 'Project loaded',

  'roll.measureLabel': 'Bar',
  'roll.noteDeleted': 'Note deleted',
  'roll.noteMoved': 'Note moved',
  'roll.lengthChanged': 'Length changed',
  'roll.noteAdded': 'Note added',

  'voice.yoi.name': 'Yoi',
  'voice.yoi.description': 'A clear, transparent female pop vocal with a straight, soaring mid-high range.',
  'voice.mio.name': 'Mio',
  'voice.mio.description': 'A classically-leaning female soprano with deep vibrato and legato phrasing.',
  'voice.akari.name': 'Akari',
  'voice.akari.description': 'A bright, forward, cute voice. Great for upbeat songs.',
  'voice.nagi.name': 'Nagi',
  'voice.nagi.description': 'A gender-neutral whisper voice, breathy and well suited to quiet songs.',
  'voice.sou.name': 'Sou',
  'voice.sou.description': 'A straightforward male tenor, at home in both choir and pop.',
  'voice.riku.name': 'Riku',
  'voice.riku.description': 'A slightly husky male pop voice with an edgy tail on phrase endings.',
  'voice.hibiki.name': 'Hibiki',
  'voice.hibiki.description': 'A thick, low male baritone — a solid foundation for choruses.',
  'voice.kotori.name': 'Kotori',
  'voice.kotori.description': 'A childlike, high, light voice. Great for nursery rhymes and call-and-response.',

  'room.off.label': 'None',
  'room.room.label': 'Room',
  'room.plate.label': 'Plate',
  'room.hall.label': 'Hall',
  'room.church.label': 'Cathedral',

  'demo.hoshi.title': 'Words of the Stars',
  'demo.hoshi.subtitle': 'A gentle ballad ｜ Yoi',
  'demo.asahi.title': 'Run, Morning Sun',
  'demo.asahi.subtitle': 'A driving pop song ｜ Akari',
  'demo.minamo.title': "Song of the Water's Surface",
  'demo.minamo.subtitle': 'A quiet arpeggio ｜ Nagi',
  'demo.yuki.title': 'Snow Lullaby',
  'demo.yuki.subtitle': 'A lullaby in 3/4 ｜ Mio',
  'demo.machi.title': 'City Lights',
  'demo.machi.subtitle': 'Nighttime city pop ｜ Riku',
  'demo.akatsuki.title': 'Voice of the Dawn',
  'demo.akatsuki.subtitle': 'A low anthem ｜ Hibiki',

  'song.newSongTitle': 'New Song',
};

registerStrings(ja, en);
