/*
 * 表示文字列（日本語 / 英語）。
 *
 * 付属音源の名前もここに置く。合成の側（factory.ts）は id だけを扱い、
 * 見せ方には関わらない。
 */

import { registerStrings } from './i18n';

const ja: Record<string, string> = {
  'app.name': 'Yamabiko Sampler',
  'app.tagline': '自分の音で楽器をつくる',

  'tab.browse': '音源',
  'tab.map': '割り当て',
  'tab.sound': '音づくり',
  'tab.fx': 'エフェクト',
  'tab.rec': '録音',
  'tab.export': '書き出し',

  'header.voices': '同時発音',
  'header.volume': '音量',
  // 表示中の言語を出す（押すともう一方へ切り替わる）。他の6本と同じ書き方
  'lang.toggle': 'JP',
  'lang.toggle.hint': 'Switch to English',

  // 付属音源
  'inst.kotoStrings': '木の弦',
  'inst.kotoStrings.desc': '指ではじいた、木の胴の弦',
  'inst.steelHarp': '鋼の弦',
  'inst.steelHarp.desc': '硬く、長く伸びる金属弦',
  'inst.mistPad': '霞',
  'inst.mistPad.desc': 'ゆっくり立ち上がる、うねりのある持続音',
  'inst.hollowReed': '空洞',
  'inst.hollowReed.desc': '奇数倍音だけの、芯のある持続音',
  'inst.bellField': '鈴野',
  'inst.bellField.desc': '音程の定まらない金物',
  'inst.drumField': '打楽器',
  'inst.drumField.desc': '鍵盤ごとに別の打楽器を割り当てたキット',

  'sample.kick': 'キック',
  'sample.snare': 'スネア',
  'sample.rim': 'リム',
  'sample.hatClosed': 'クローズハット',
  'sample.hatOpen': 'オープンハット',
  'sample.tomLow': 'ロータム',
  'sample.tomHigh': 'ハイタム',
  'sample.crash': 'クラッシュ',

  'demo.title': '収録デモ',
  'demo.hint': '押すと読み込んで再生します。そのまま書き出せます',
  'demo.loaded': '{name} を読み込みました',
  'demo.stoneGarden.name': '石庭',
  'demo.stoneGarden.desc': '音と音のあいだの静けさ',
  'demo.frost.name': '氷結',
  'demo.frost.desc': '上下に折り返す分散和音',
  'demo.morningMist.name': '朝霧',
  'demo.morningMist.desc': 'ゆっくり立ち上がる和音',
  'demo.reedPath.name': '笛の道',
  'demo.reedPath.desc': '素朴な旋律をひとつ',
  'demo.bellHill.name': '鐘の丘',
  'demo.bellHill.desc': '疎らに置いた金物',
  'demo.earthPulse.name': '土の鼓動',
  'demo.earthPulse.desc': '素直な四つ打ち',
  'demo.raindrops.name': '雨だれ',
  'demo.raindrops.desc': '高いところから降りてくる',
  'demo.stardust.name': '星屑',
  'demo.stardust.desc': '長いディレイのなかの疎らな高音',
  'demo.trench.name': '海溝',
  'demo.trench.desc': 'ほとんど動かない持続音',
  'demo.festival.name': '祭囃子',
  'demo.festival.desc': '裏を詰めて前へ転がす',

  'browse.title': '音を選ぶ',
  'browse.factory': '付属音源',
  'browse.factory.hint': 'すべてその場で合成しています。録音素材は入っていません',
  'browse.mine': '自分の素材',
  'browse.mine.hint': '取り込んだ音・録音した音',
  'browse.empty': 'まだ素材がありません',
  'browse.import': 'ファイルから取り込む',
  'browse.record': 'マイクで録る',
  'browse.recording': '録音中… もう一度押すと止まります',
  'browse.storage': '使用中 {used} / {max}',
  'browse.delete': '削除',
  'browse.makeInstrument': 'この素材で楽器をつくる',
  'browse.loading': '合成しています…',

  'import.done': '{name} を取り込みました',
  'import.failed.tooLarge': 'ファイルが大きすぎます（上限 {max} MB）',
  'import.failed.tooLong': '長すぎます（上限 {max} 秒）',
  'import.failed.notAudio': '音声として読み取れませんでした',
  'import.failed.empty': '中身が空のファイルです',
  'import.failed.silent': '音が入っていないファイルです',
  'import.failed.store': '保存できませんでした（空き容量を確認してください）',

  'record.denied': 'マイクを使えませんでした。端末の設定で許可してください',
  'record.tooShort': '短すぎます',
  'record.done': '{seconds} 秒 録音しました',

  'map.title': '割り当て',
  'map.hint': 'どの鍵盤で、どの素材を、どの強さで鳴らすか',
  'map.zone': 'ゾーン {n}',
  'map.noZones': 'ゾーンがありません',
  'map.addZone': 'ゾーンを足す',
  'map.removeZone': 'このゾーンを消す',
  'map.sample': '素材',
  'map.keyRange': '鍵盤の範囲',
  'map.velRange': '強さの範囲',
  'map.rootKey': '基準の音',
  'map.rootKey.hint': 'この素材が本来鳴っている音程。ここを基準に音程を変えます',
  'map.tune': '音程の補正',
  'map.gain': '音量',
  'map.pan': '定位',
  'map.group': 'ラウンドロビンの組',
  'map.group.hint': '同じ組のゾーンが順番に鳴ります。同じ音が続いても機械的になりません',
  'map.reverse': '逆再生',
  'map.loop': 'ループ',
  'map.loopRange': 'ループの範囲',
  'map.trim': '鳴らす範囲',
  'map.autoMap': '鍵盤に自動で並べる',
  'map.autoMap.hint': '選んだ素材を、鍵盤いっぱいに割り当て直します',
  'map.listen': '試し弾き',

  'wave.mode.hint': '波形の見せ方を変える',
  'wave.mode.echo': '返り',
  'wave.mode.mirror': '対称',
  'wave.mode.bars': '棒',
  'wave.mode.line': '輪郭',
  'wave.mode.heat': '熱',
  'wave.mode.radial': '放射',

  'wave.title': '鳴らし方',
  'wave.hint': '波形は画面の下に出ています。ドラッグで範囲を変えられます',
  'wave.start': '始め',
  'wave.end': '終わり',
  'wave.loopStart': 'ループ始め',
  'wave.loopEnd': 'ループ終わり',

  'sound.amp': '音量の変化',
  'sound.amp.hint': '弾いてから消えるまでの形',
  'sound.attack': '立ち上がり',
  'sound.decay': '減衰',
  'sound.sustain': '持続',
  'sound.release': '余韻',
  'sound.filter': 'フィルター',
  'sound.filter.mode': '種類',
  'sound.filter.freq': '遮断周波数',
  'sound.filter.q': '効き',
  'sound.filter.keyTrack': '鍵盤に追従',
  'sound.filter.keyTrack.hint': '高い鍵盤ほど明るくします',
  'sound.filter.env': 'フィルターの変化',
  'sound.filter.envAmount': '変化の量',
  'sound.lfo': 'ゆれ（LFO）',
  'sound.lfo.rate': '速さ',
  'sound.lfo.toPitch': '音程へ',
  'sound.lfo.toFilter': '明るさへ',
  'sound.lfo.toAmp': '音量へ',
  'sound.lfo.delay': '効き始めるまで',
  'sound.play': '弾き方',
  'sound.poly': '同時発音数',
  'sound.mono': '単音で弾く',
  'sound.mono.hint': '和音を鳴らさず、音をつないで弾きます',
  'sound.glide': '音程をつなぐ',
  'sound.transpose': '移調',
  'sound.velToVolume': '強さ → 音量',
  'sound.velToFilter': '強さ → 明るさ',
  'sound.gain': '楽器の音量',

  'fx.dist': 'ひずみ',
  'fx.dist.type': '種類',
  'fx.dist.amount': '深さ',
  'fx.dist.tone': '音色',
  'fx.crush': 'ビットクラッシャー',
  'fx.crush.bits': 'ビット数',
  'fx.filter': 'フィルター（自動）',
  'fx.filter.rate': '速さ',
  'fx.filter.depth': '深さ',
  'fx.chorus': 'コーラス',
  'fx.flanger': 'フランジャー',
  'fx.phaser': 'フェイザー',
  'fx.ring': 'リングモジュレーター',
  'fx.mod': 'トレモロ / オートパン',
  'fx.space': '空間',
  'fx.width': 'ステレオの広がり',
  'fx.delay': 'ディレイ',
  'fx.delay.time': '間隔',
  'fx.delay.feedback': '繰り返し',
  'fx.delay.pingPong': '左右に振る',
  'fx.reverb': 'リバーブ',
  'fx.reverb.type': '響き',
  'fx.mix': '混ぜる量',
  'fx.rate': '速さ',
  'fx.depth': '深さ',
  'fx.feedback': '戻す量',
  'fx.freq': '周波数',
  'fx.on': 'かける',
  'fx.off': 'なし',

  'mode.off': 'なし',
  'mode.lowpass': '低域を通す',
  'mode.highpass': '高域を通す',
  'mode.bandpass': '帯域を通す',
  'mode.soft': 'やわらか',
  'mode.hard': '硬い',
  'mode.fuzz': 'ファズ',
  'mode.tremolo': 'トレモロ',
  'mode.autopan': 'オートパン',
  'room.room': 'ルーム',
  'room.plate': 'プレート',
  'room.hall': 'ホール',
  'room.cavern': 'カヴァーン',

  'pad.title': 'パッド',
  'pad.hint': '空いているパッドを押すと、いまの録音が載ります。載ったパッドは押すと鳴ります',
  'pad.add': '空いているパッドに載せる',
  'pad.stopAll': 'すべて止める',
  'pad.clear': 'このパッドを空にする',
  'pad.baking': 'パッドに焼いています…',
  'pad.added': 'パッド {n} に {name} を載せました',
  'pad.needRecording': '先に演奏を録音してください',

  'rec.start': '録音',
  'rec.stop': '停止',
  'rec.play': '再生',
  'rec.clear': '消す',
  'rec.empty': 'まだ録音がありません',
  'rec.recording': '録音中 {seconds} 秒',
  'rec.notes': '{count} 音',
  'rec.hint': '鍵盤を弾くと、そのまま記録されます',

  'export.wav': 'WAV で書き出す',
  'export.midi': 'MIDI で書き出す',
  'export.save': '楽器を保存',
  'export.load': '楽器を読み込む',
  'export.hint': '48kHz / 24bit ステレオ。書き出した音は自由に使えます',
  'export.rendering': '書き出しています…',
  'export.wavDone': 'WAV を書き出しました（{size} MB）',
  'export.midiDone': 'MIDI を書き出しました',
  'export.saved': '楽器を保存しました',
  'export.loaded': '楽器を読み込みました',
  'export.loadFailed': 'この形式のファイルは読み込めません',
  'export.failed': '書き出しに失敗しました',
  'export.nothing': '先に演奏を録音してください',
  'export.withSamples': '素材も一緒に保存する',
  'export.withSamples.hint': '付属音源は合成し直せるので含めません。取り込んだ音だけを保存します',

  'privacy.title': 'このアプリについて',
  'privacy.offline': 'このアプリは通信を一切行いません。取り込んだ音も、録音した声も、端末の外へ出ることはありません。',
  'privacy.original': '付属音源はすべてこのアプリが計算で作っています。第三者の録音は含まれていないため、作った音源はそのまま商用利用できます。',
  'privacy.clear': '取り込んだ素材をすべて消す',
  'privacy.cleared': '素材をすべて消しました',
};

const en: Record<string, string> = {
  'app.name': 'Yamabiko Sampler',
  'app.tagline': 'Build an instrument from your own sound',

  'tab.browse': 'Sounds',
  'tab.map': 'Mapping',
  'tab.sound': 'Shape',
  'tab.fx': 'Effects',
  'tab.rec': 'Record',
  'tab.export': 'Export',

  'header.voices': 'Voices',
  'header.volume': 'Volume',
  'lang.toggle': 'EN',
  'lang.toggle.hint': '日本語に切り替える',

  'inst.kotoStrings': 'Wooden Strings',
  'inst.kotoStrings.desc': 'Plucked strings over a wooden body',
  'inst.steelHarp': 'Steel Strings',
  'inst.steelHarp.desc': 'Hard metal strings with a long tail',
  'inst.mistPad': 'Mist',
  'inst.mistPad.desc': 'Slow, drifting sustained tone',
  'inst.hollowReed': 'Hollow',
  'inst.hollowReed.desc': 'Odd harmonics only — reedy and solid',
  'inst.bellField': 'Bell Field',
  'inst.bellField.desc': 'Metal with no settled pitch',
  'inst.drumField': 'Percussion',
  'inst.drumField.desc': 'A different drum on every key',

  'sample.kick': 'Kick',
  'sample.snare': 'Snare',
  'sample.rim': 'Rim',
  'sample.hatClosed': 'Closed hat',
  'sample.hatOpen': 'Open hat',
  'sample.tomLow': 'Low tom',
  'sample.tomHigh': 'High tom',
  'sample.crash': 'Crash',

  'demo.title': 'Included pieces',
  'demo.hint': 'Loads and plays. Export it as it is.',
  'demo.loaded': 'Loaded {name}',
  'demo.stoneGarden.name': 'Stone Garden',
  'demo.stoneGarden.desc': 'The quiet between the notes',
  'demo.frost.name': 'Frost',
  'demo.frost.desc': 'Arpeggios folding back on themselves',
  'demo.morningMist.name': 'Morning Mist',
  'demo.morningMist.desc': 'Chords that rise slowly',
  'demo.reedPath.name': 'Reed Path',
  'demo.reedPath.desc': 'One plain melody',
  'demo.bellHill.name': 'Bell Hill',
  'demo.bellHill.desc': 'Metal placed sparsely',
  'demo.earthPulse.name': 'Earth Pulse',
  'demo.earthPulse.desc': 'A straight four to the floor',
  'demo.raindrops.name': 'Raindrops',
  'demo.raindrops.desc': 'Falling from high up',
  'demo.stardust.name': 'Stardust',
  'demo.stardust.desc': 'Sparse high notes in a long delay',
  'demo.trench.name': 'Trench',
  'demo.trench.desc': 'A drone that barely moves',
  'demo.festival.name': 'Festival',
  'demo.festival.desc': 'Off-beats packed to push it forward',

  'browse.title': 'Choose a sound',
  'browse.factory': 'Included sounds',
  'browse.factory.hint': 'All synthesised on the spot. No recordings inside.',
  'browse.mine': 'Your samples',
  'browse.mine.hint': 'Imported and recorded audio',
  'browse.empty': 'No samples yet',
  'browse.import': 'Import a file',
  'browse.record': 'Record from mic',
  'browse.recording': 'Recording… press again to stop',
  'browse.storage': 'Using {used} of {max}',
  'browse.delete': 'Delete',
  'browse.makeInstrument': 'Make an instrument from this',
  'browse.loading': 'Synthesising…',

  'import.done': 'Imported {name}',
  'import.failed.tooLarge': 'File is too large (limit {max} MB)',
  'import.failed.tooLong': 'Too long (limit {max} seconds)',
  'import.failed.notAudio': 'Could not read this as audio',
  'import.failed.empty': 'The file is empty',
  'import.failed.silent': 'There is no sound in this file',
  'import.failed.store': 'Could not save it — check free space',

  'record.denied': 'Could not use the microphone. Allow it in your device settings.',
  'record.tooShort': 'Too short',
  'record.done': 'Recorded {seconds} seconds',

  'map.title': 'Mapping',
  'map.hint': 'Which sample plays on which key, at which strength',
  'map.zone': 'Zone {n}',
  'map.noZones': 'No zones yet',
  'map.addZone': 'Add a zone',
  'map.removeZone': 'Remove this zone',
  'map.sample': 'Sample',
  'map.keyRange': 'Key range',
  'map.velRange': 'Velocity range',
  'map.rootKey': 'Root key',
  'map.rootKey.hint': 'The pitch this sample already plays. Everything is tuned from here.',
  'map.tune': 'Tuning',
  'map.gain': 'Level',
  'map.pan': 'Pan',
  'map.group': 'Round-robin group',
  'map.group.hint': 'Zones in the same group take turns, so repeats do not sound identical',
  'map.reverse': 'Reverse',
  'map.loop': 'Loop',
  'map.loopRange': 'Loop range',
  'map.trim': 'Play range',
  'map.autoMap': 'Spread across the keyboard',
  'map.autoMap.hint': 'Re-maps the chosen samples over the whole keyboard',
  'map.listen': 'Audition',

  'wave.mode.hint': 'Change how the waveform is drawn',
  'wave.mode.echo': 'Echo',
  'wave.mode.mirror': 'Mirror',
  'wave.mode.bars': 'Bars',
  'wave.mode.line': 'Outline',
  'wave.mode.heat': 'Heat',
  'wave.mode.radial': 'Radial',

  'wave.title': 'Playback',
  'wave.hint': 'The waveform sits below. Drag it to change the range.',
  'wave.start': 'Start',
  'wave.end': 'End',
  'wave.loopStart': 'Loop start',
  'wave.loopEnd': 'Loop end',

  'sound.amp': 'Amplitude',
  'sound.amp.hint': 'How the sound rises and fades',
  'sound.attack': 'Attack',
  'sound.decay': 'Decay',
  'sound.sustain': 'Sustain',
  'sound.release': 'Release',
  'sound.filter': 'Filter',
  'sound.filter.mode': 'Type',
  'sound.filter.freq': 'Cutoff',
  'sound.filter.q': 'Resonance',
  'sound.filter.keyTrack': 'Key follow',
  'sound.filter.keyTrack.hint': 'Keeps higher keys as bright as lower ones',
  'sound.filter.env': 'Filter envelope',
  'sound.filter.envAmount': 'Amount',
  'sound.lfo': 'Movement (LFO)',
  'sound.lfo.rate': 'Rate',
  'sound.lfo.toPitch': 'To pitch',
  'sound.lfo.toFilter': 'To brightness',
  'sound.lfo.toAmp': 'To level',
  'sound.lfo.delay': 'Fade in',
  'sound.play': 'Playing',
  'sound.poly': 'Max voices',
  'sound.mono': 'One note at a time',
  'sound.mono.hint': 'Plays single notes and slides between them',
  'sound.glide': 'Glide',
  'sound.transpose': 'Transpose',
  'sound.velToVolume': 'Velocity to level',
  'sound.velToFilter': 'Velocity to brightness',
  'sound.gain': 'Instrument level',

  'fx.dist': 'Distortion',
  'fx.dist.type': 'Type',
  'fx.dist.amount': 'Drive',
  'fx.dist.tone': 'Tone',
  'fx.crush': 'Bit crusher',
  'fx.crush.bits': 'Bits',
  'fx.filter': 'Filter sweep',
  'fx.filter.rate': 'Rate',
  'fx.filter.depth': 'Depth',
  'fx.chorus': 'Chorus',
  'fx.flanger': 'Flanger',
  'fx.phaser': 'Phaser',
  'fx.ring': 'Ring modulator',
  'fx.mod': 'Tremolo / auto-pan',
  'fx.space': 'Space',
  'fx.width': 'Stereo width',
  'fx.delay': 'Delay',
  'fx.delay.time': 'Time',
  'fx.delay.feedback': 'Repeats',
  'fx.delay.pingPong': 'Ping-pong',
  'fx.reverb': 'Reverb',
  'fx.reverb.type': 'Room',
  'fx.mix': 'Mix',
  'fx.rate': 'Rate',
  'fx.depth': 'Depth',
  'fx.feedback': 'Feedback',
  'fx.freq': 'Frequency',
  'fx.on': 'On',
  'fx.off': 'Off',

  'mode.off': 'Off',
  'mode.lowpass': 'Low pass',
  'mode.highpass': 'High pass',
  'mode.bandpass': 'Band pass',
  'mode.soft': 'Soft',
  'mode.hard': 'Hard',
  'mode.fuzz': 'Fuzz',
  'mode.tremolo': 'Tremolo',
  'mode.autopan': 'Auto-pan',
  'room.room': 'Room',
  'room.plate': 'Plate',
  'room.hall': 'Hall',
  'room.cavern': 'Cavern',

  'pad.title': 'Pads',
  'pad.hint': 'Press an empty pad to put the current recording on it. Press a loaded pad to play it.',
  'pad.add': 'Put on a free pad',
  'pad.stopAll': 'Stop all',
  'pad.clear': 'Empty this pad',
  'pad.baking': 'Rendering to the pad…',
  'pad.added': 'Pad {n} now holds {name}',
  'pad.needRecording': 'Record a performance first',

  'rec.start': 'Record',
  'rec.stop': 'Stop',
  'rec.play': 'Play',
  'rec.clear': 'Clear',
  'rec.empty': 'Nothing recorded yet',
  'rec.recording': 'Recording {seconds}s',
  'rec.notes': '{count} notes',
  'rec.hint': 'Whatever you play on the keyboard is captured',

  'export.wav': 'Export WAV',
  'export.midi': 'Export MIDI',
  'export.save': 'Save instrument',
  'export.load': 'Load instrument',
  'export.hint': '48kHz / 24-bit stereo. Exported audio is yours to use freely.',
  'export.rendering': 'Rendering…',
  'export.wavDone': 'WAV exported ({size} MB)',
  'export.midiDone': 'MIDI exported',
  'export.saved': 'Instrument saved',
  'export.loaded': 'Instrument loaded',
  'export.loadFailed': 'That file is not in a format this app can read',
  'export.failed': 'Export failed',
  'export.nothing': 'Record a performance first',
  'export.withSamples': 'Include the samples',
  'export.withSamples.hint': 'Included sounds are re-synthesised, so only your own samples are stored',

  'privacy.title': 'About this app',
  'privacy.offline':
    'This app never uses the network. Nothing you import or record leaves your device.',
  'privacy.original':
    'Every included sound is calculated by the app itself. No third-party recordings are inside, so what you make here is yours to sell.',
  'privacy.clear': 'Delete all imported samples',
  'privacy.cleared': 'All samples deleted',
};

registerStrings(ja, en);
