/* Aozora Grand Piano の全UI文字列（日本語 / 英語） */
import { registerStrings } from './i18n';

const ja: Record<string, string> = {
  'brand.subtitle': '物理モデリング・グランドピアノ',
  'preset.ariaLabel': '音色プリセット',
  'panic.label': '全停止',
  'panic.title': 'すべての音を止める（Esc）',
  'panic.ariaLabel': 'すべての音を止める',
  'help.button': '?',
  'lang.toggle': 'EN',

  'tab.tone': '音色',
  'tab.space': '響き',
  'tab.play': '演奏',
  'tab.rec': '録音',
  'tab.demo': 'デモ',

  'pedal.soft': 'ソフト',
  'pedal.sostenuto': 'ソステヌート',
  'pedal.sustain': 'サステイン',
  'octave.down': '◀ オクターブ',
  'octave.up': 'オクターブ ▶',
  'octave.label': 'PCキー: C{n}',

  'status.ready': '準備完了',
  'status.pressKey': '鍵盤を押すと開始',
  'status.midi': 'MIDI: {devices}',
  'status.audioError': 'オーディオを開始できません: {err}',

  'tone.presetsTitle': '音色プリセット',
  'tone.soundTitle': '音づくり',
  'tone.brightness': 'ハンマーの硬さ（明るさ）',
  'tone.brightness.hint': 'フェルト ← → ブライト',
  'tone.strikePos': '打弦位置',
  'tone.strikePos.hint': '端寄り（硬い） ← → 中央寄り（丸い）',
  'tone.decay': '減衰（余韻の長さ）',
  'tone.stringRes': '弦の共鳴',
  'tone.stringRes.hint': 'ペダルを踏んだときに他の弦が共鳴する量',
  'tone.unison': 'ユニゾンのうなり',
  'tone.unison.hint': '1つの音に張られた複数弦のズレ',
  'tone.hammerNoise': '打弦ノイズ',
  'tone.releaseNoise': '離鍵ノイズ',
  'tone.releaseNoise.hint': 'ダンパーが弦に触れる音',

  'space.title': '空間と響き',
  'space.reverbOff': 'オフ',
  'space.lid': '大屋根の開き',
  'space.lid.hint': '閉じるほど丸く、開くほど華やかに',
  'space.tone': 'トーン',
  'space.reverbType': '残響空間',
  'space.reverbMix': '残響の量',
  'space.volume': 'マスター音量',
  'space.note': '残響はインパルス応答をその場で生成しています。音声ファイルのダウンロードは一切ありません。',

  'play.touchTuningTitle': 'タッチと調律',
  'play.velCurve': 'ベロシティカーブ',
  'play.velCurve.hint': '大きいほど強く弾かないと音量が出ません',
  'play.dynamics': 'ダイナミクス',
  'play.dynamics.hint': '小さいほど強弱の差が圧縮されます',
  'play.a4': '基準ピッチ A4',
  'play.stretch': 'ストレッチ調律',
  'play.stretch.hint': '低音を低く・高音を高く。実際の調律に近づきます',
  'play.maxVoices': '最大同時発音数',
  'play.maxVoices.hint': '動作が重いときは減らしてください',
  'play.keyWidth': '鍵盤の大きさ',
  'play.labelMode': '鍵盤の音名表示',
  'play.labelMode.off': 'なし',
  'play.labelMode.c': 'Cのみ',
  'play.labelMode.all': '英語',
  'play.labelMode.ja': 'ドレミ',
  'play.range': '表示する鍵盤の範囲',
  'play.range.full': '88鍵',
  'play.range.wide': '61鍵',
  'play.range.mid': '49鍵',
  'play.range.small': '25鍵',
  'play.velocityMode': '鍵盤のベロシティ',
  'play.velocityMode.touch': '打鍵位置で変化',
  'play.velocityMode.soft': '固定 (弱)',
  'play.velocityMode.mid': '固定 (中)',
  'play.velocityMode.loud': '固定 (強)',
  'play.metroTempo': 'メトロノーム テンポ',
  'play.metroToggle': 'メトロノームを鳴らす',
  'play.practiceTitle': '練習ツール',
  'play.midiTitle': 'MIDI',
  'play.midiRescan': 'MIDI 再検出',
  'play.midiConnect': 'MIDIキーボードを接続',
  'play.midiConnected': '接続中: {devices}',
  'play.midiHint': '外部MIDIキーボードを接続すると、そのまま演奏できます。',
  'play.midiUnsupported': 'このブラウザは Web MIDI に対応していません（Chrome / Edge 推奨）。',

  'rec.title': '録音と書き出し',
  'rec.stop': '■ 録音停止',
  'rec.start': '● 録音開始',
  'rec.play': '▶ 再生',
  'rec.clear': 'クリア',
  'rec.empty': '録音すると、演奏がイベントとして記録されます。あとから音色を変えて書き出せます。',
  'rec.count': '録音済み: {count} 音 / {time}',
  'rec.exportWav': 'WAV で書き出し',
  'rec.exportMidi': 'MIDI で書き出し',
  'rec.exporting': '書き出し中…',
  'rec.filesTitle': 'ファイル',
  'rec.note': 'WAV は 48kHz / 24bit・ステレオで、現在の音色設定のまま再合成して書き出します。作成した音源の利用に制限はありません（商用利用も自由です）。',

  'demo.title': 'デモ演奏',
  'demo.play': '▶ 再生',
  'demo.stop': '■ 停止',
  'demo.useDemoPreset': '推奨音色に切り替えて再生する',
  'demo.note': 'デモはすべて権利処理が不要な楽曲です（パブリックドメイン作品と本アプリのオリジナル曲）。再生中の演奏もそのまま WAV / MIDI に書き出せます。',

  'flash.presetChanged': '音色: {name}',
  'flash.allStopped': 'すべての音を停止しました',
  'flash.recStopped': '録音を停止しました',
  'flash.recording': '● 録音中',
  'flash.recordedPerformance': '録音した演奏',
  'flash.playbackEnded': '再生が終了しました',
  'flash.nothingToExport': '書き出す演奏がありません',
  'flash.exportingWav': 'WAV を書き出しています…',
  'flash.wavSaved': 'WAV を保存しました',
  'flash.exportFailed': '書き出しに失敗しました: {err}',
  'flash.midiSaved': 'MIDI を保存しました',
  'flash.midiConnectFailed': 'MIDIデバイスに接続できませんでした',

  'help.title': '使い方',
  'help.play.term': '演奏',
  'help.play.desc': '画面の鍵盤をクリック／タッチ（マルチタッチ対応）。鍵盤の手前を押すほど強い音になります。',
  'help.pcKeys.term': 'PCキーボード',
  'help.pcKeys.desc': 'Z S X D C V G B H N J M , L . ; / と Q 2 W 3 E R 5 T 6 Y 7 U で2オクターブ。←→ でオクターブ移動。',
  'help.pedals.term': 'ペダル',
  'help.pedals.desc': 'スペースキーでサステイン。Shift でソフト（弱音）ペダル。',
  'help.midi.term': 'MIDI',
  'help.midi.desc': '「演奏」タブから MIDI キーボードを接続できます（CC64/66/67 のペダルにも対応）。',
  'help.rec.term': '録音',
  'help.rec.desc': '「録音」タブで演奏を記録し、WAV（48kHz/24bit）や MIDI として保存できます。',
  'help.aboutSoundTitle': 'この音について',
  'help.aboutSound': '録音済みのピアノ音源（サンプル）は使っていません。88鍵それぞれの弦の部分音・不協和度・打弦位置・ダンパー・共鳴を計算して、その場で音を合成しています。そのためアプリ本体は数百KBで、追加ダウンロードも通信も不要です。',
  'help.free': '広告なし・追跡なし・アカウント登録なし。オフラインでも動作します。',
  'help.usage': '書き出した音源はご自由にお使いいただけます（商用利用可・クレジット表記不要）。',
  'help.privacy': 'プライバシーポリシー',
  'help.close': '閉じる',

  'noscript': 'このアプリの動作には JavaScript が必要です。',

  'reverb.room': 'ルーム',
  'reverb.studio': 'スタジオ',
  'reverb.hall': 'コンサートホール',
  'reverb.church': '教会',

  'preset.concert.name': 'コンサートグランド',
  'preset.concert.description': 'ホールの9フィート・フルコンサート。伸びやかで華やか。',
  'preset.studio.name': 'スタジオグランド',
  'preset.studio.description': '近接マイクの締まったサウンド。レコーディング向け。',
  'preset.warm.name': 'ウォームバラード',
  'preset.warm.description': '柔らかいハンマー。弾き語りやバラードに。',
  'preset.bright.name': 'ブライトポップ',
  'preset.bright.description': '硬めのハンマーで抜けの良い音。バンドの中でも埋もれない。',
  'preset.jazz.name': 'ジャズクラブ',
  'preset.jazz.description': 'ややタイトな減衰と近い響き。コンピングが濁らない。',
  'preset.felt.name': 'フェルトピアノ',
  'preset.felt.description': 'ハンマーにフェルトを挟んだ、囁くようなローファイ音色。',
  'preset.cinematic.name': 'シネマティック',
  'preset.cinematic.description': '大聖堂の残響と豊かな共鳴。アンビエント／劇伴向け。',
  'preset.honkytonk.name': 'ホンキートンク',
  'preset.honkytonk.description': '調律の狂ったアップライト風。酒場のピアノ。',

  'demo.bwv846.title': '前奏曲 第1番 ハ長調 BWV 846',
  'demo.bwv846.composer': 'J.S. バッハ',
  'demo.furelise.title': 'エリーゼのために WoO 59',
  'demo.furelise.composer': 'L.v. ベートーヴェン',
  'demo.moonlight.title': 'ピアノソナタ第14番「月光」第1楽章',
  'demo.moonlight.composer': 'L.v. ベートーヴェン',
  'demo.canon.title': 'カノン ニ長調',
  'demo.canon.composer': 'J. パッヘルベル',
  'demo.minuet.title': 'メヌエット ト長調 BWV Anh.114',
  'demo.minuet.composer': 'C. ペツォールト',
  'demo.odetojoy.title': '歓喜の歌（交響曲第9番より）',
  'demo.odetojoy.composer': 'L.v. ベートーヴェン',
  'demo.twinkle.title': 'きらきら星',
  'demo.twinkle.composer': 'フランス民謡',
  'demo.amazinggrace.title': 'アメイジング・グレイス',
  'demo.amazinggrace.composer': '賛美歌',
  'demo.greensleeves.title': 'グリーンスリーブス',
  'demo.greensleeves.composer': 'イングランド民謡',
  'demo.waltz.title': '星降る夜のワルツ',
  'demo.waltz.composer': 'オリジナル',
  'demo.ballad.title': '夏の終わりのバラード',
  'demo.ballad.composer': 'オリジナル',
  'demo.nocturne.title': '夜明けのノクターン',
  'demo.nocturne.composer': 'オリジナル',
  'demo.note.publicDomain': 'パブリックドメイン',
  'demo.note.original': '本アプリ書き下ろし',
};

const en: Record<string, string> = {
  'brand.subtitle': 'Physically Modelled Grand Piano',
  'preset.ariaLabel': 'Tone preset',
  'panic.label': 'Stop all',
  'panic.title': 'Stop all sound (Esc)',
  'panic.ariaLabel': 'Stop all sound',
  'help.button': '?',
  'lang.toggle': '日',

  'tab.tone': 'Tone',
  'tab.space': 'Space',
  'tab.play': 'Play',
  'tab.rec': 'Record',
  'tab.demo': 'Demos',

  'pedal.soft': 'Soft',
  'pedal.sostenuto': 'Sostenuto',
  'pedal.sustain': 'Sustain',
  'octave.down': '◀ Octave',
  'octave.up': 'Octave ▶',
  'octave.label': 'PC key: C{n}',

  'status.ready': 'Ready',
  'status.pressKey': 'Press a key to start',
  'status.midi': 'MIDI: {devices}',
  'status.audioError': 'Could not start audio: {err}',

  'tone.presetsTitle': 'Tone presets',
  'tone.soundTitle': 'Sound design',
  'tone.brightness': 'Hammer hardness (brightness)',
  'tone.brightness.hint': 'Felt ← → Bright',
  'tone.strikePos': 'Strike position',
  'tone.strikePos.hint': 'Near the edge (hard) ← → Center (round)',
  'tone.decay': 'Decay (sustain length)',
  'tone.stringRes': 'String resonance',
  'tone.stringRes.hint': 'How much other strings resonate when a pedal is held',
  'tone.unison': 'Unison beating',
  'tone.unison.hint': 'Detuning between the multiple strings of one note',
  'tone.hammerNoise': 'Hammer noise',
  'tone.releaseNoise': 'Release noise',
  'tone.releaseNoise.hint': 'Sound of the damper touching the string',

  'space.title': 'Space & resonance',
  'space.reverbOff': 'Off',
  'space.lid': 'Lid opening',
  'space.lid.hint': 'More closed = rounder, more open = brighter',
  'space.tone': 'Tone',
  'space.reverbType': 'Reverb space',
  'space.reverbMix': 'Reverb amount',
  'space.volume': 'Master volume',
  'space.note': 'Reverb impulse responses are generated on the fly — no audio files are ever downloaded.',

  'play.touchTuningTitle': 'Touch & tuning',
  'play.velCurve': 'Velocity curve',
  'play.velCurve.hint': 'Higher means you need to play harder for volume',
  'play.dynamics': 'Dynamics',
  'play.dynamics.hint': 'Lower compresses the difference between soft and loud',
  'play.a4': 'Reference pitch A4',
  'play.stretch': 'Stretch tuning',
  'play.stretch.hint': 'Lowers the bass and raises the treble, closer to a real piano',
  'play.maxVoices': 'Max polyphony',
  'play.maxVoices.hint': 'Lower this if playback feels heavy',
  'play.keyWidth': 'Key width',
  'play.labelMode': 'Key labels',
  'play.labelMode.off': 'None',
  'play.labelMode.c': 'C only',
  'play.labelMode.all': 'Letters',
  'play.labelMode.ja': 'Solfège',
  'play.range': 'Visible key range',
  'play.range.full': '88 keys',
  'play.range.wide': '61 keys',
  'play.range.mid': '49 keys',
  'play.range.small': '25 keys',
  'play.velocityMode': 'Key velocity',
  'play.velocityMode.touch': 'Varies with touch',
  'play.velocityMode.soft': 'Fixed (soft)',
  'play.velocityMode.mid': 'Fixed (mid)',
  'play.velocityMode.loud': 'Fixed (loud)',
  'play.metroTempo': 'Metronome tempo',
  'play.metroToggle': 'Enable metronome',
  'play.practiceTitle': 'Practice tools',
  'play.midiTitle': 'MIDI',
  'play.midiRescan': 'Rescan MIDI',
  'play.midiConnect': 'Connect MIDI keyboard',
  'play.midiConnected': 'Connected: {devices}',
  'play.midiHint': 'Connect an external MIDI keyboard and play right away.',
  'play.midiUnsupported': 'This browser does not support Web MIDI (Chrome / Edge recommended).',

  'rec.title': 'Record & export',
  'rec.stop': '■ Stop recording',
  'rec.start': '● Start recording',
  'rec.play': '▶ Play',
  'rec.clear': 'Clear',
  'rec.empty': 'Recording captures your performance as events, so you can change the tone before exporting.',
  'rec.count': 'Recorded: {count} notes / {time}',
  'rec.exportWav': 'Export as WAV',
  'rec.exportMidi': 'Export as MIDI',
  'rec.exporting': 'Exporting…',
  'rec.filesTitle': 'Files',
  'rec.note': 'WAV is exported at 48kHz / 24-bit stereo, re-synthesized with the current tone settings. There are no restrictions on using the exported audio — commercial use is fine.',

  'demo.title': 'Demo performances',
  'demo.play': '▶ Play',
  'demo.stop': '■ Stop',
  'demo.useDemoPreset': 'Switch to the recommended tone when playing',
  'demo.note': 'Every demo is free of rights issues — public-domain works and original pieces written for this app. Playback can be exported to WAV / MIDI too.',

  'flash.presetChanged': 'Tone: {name}',
  'flash.allStopped': 'All sound stopped',
  'flash.recStopped': 'Recording stopped',
  'flash.recording': '● Recording',
  'flash.recordedPerformance': 'Recorded performance',
  'flash.playbackEnded': 'Playback finished',
  'flash.nothingToExport': 'Nothing to export',
  'flash.exportingWav': 'Exporting WAV…',
  'flash.wavSaved': 'WAV saved',
  'flash.exportFailed': 'Export failed: {err}',
  'flash.midiSaved': 'MIDI saved',
  'flash.midiConnectFailed': 'Could not connect to the MIDI device',

  'help.title': 'How to use',
  'help.play.term': 'Play',
  'help.play.desc': 'Click or tap the on-screen keys (multi-touch supported). Pressing nearer the front of the key plays louder.',
  'help.pcKeys.term': 'PC keyboard',
  'help.pcKeys.desc': 'Z S X D C V G B H N J M , L . ; / and Q 2 W 3 E R 5 T 6 Y 7 U play two octaves. ←→ shift octave.',
  'help.pedals.term': 'Pedals',
  'help.pedals.desc': 'Space bar for sustain. Shift for the soft (una corda) pedal.',
  'help.midi.term': 'MIDI',
  'help.midi.desc': 'Connect a MIDI keyboard from the Play tab (CC64/66/67 pedal messages are supported too).',
  'help.rec.term': 'Record',
  'help.rec.desc': 'Capture your playing from the Record tab and save it as WAV (48kHz/24-bit) or MIDI.',
  'help.aboutSoundTitle': 'About this sound',
  'help.aboutSound': 'No recorded piano samples are used. Each of the 88 keys is synthesized on the fly by computing the string partials, inharmonicity, strike position, damper, and resonance. The app itself is only a few hundred KB, with nothing else to download and no network use.',
  'help.free': 'No ads, no tracking, no account. Works fully offline.',
  'help.usage': 'Feel free to use anything you export — commercial use is fine and no credit is required.',
  'help.privacy': 'Privacy policy',
  'help.close': 'Close',

  'noscript': 'This app requires JavaScript to run.',

  'reverb.room': 'Room',
  'reverb.studio': 'Studio',
  'reverb.hall': 'Concert hall',
  'reverb.church': 'Church',

  'preset.concert.name': 'Concert Grand',
  'preset.concert.description': 'A 9-foot full concert grand in a hall. Broad and brilliant.',
  'preset.studio.name': 'Studio Grand',
  'preset.studio.description': 'Tight, close-mic\'d sound built for recording.',
  'preset.warm.name': 'Warm Ballad',
  'preset.warm.description': 'Soft hammers, suited to singer-songwriter ballads.',
  'preset.bright.name': 'Bright Pop',
  'preset.bright.description': 'Hard hammers that cut through a full band mix.',
  'preset.jazz.name': 'Jazz Club',
  'preset.jazz.description': 'Tighter decay and close ambience, so comping stays clear.',
  'preset.felt.name': 'Felt Piano',
  'preset.felt.description': 'Felt between hammer and string for a whispery, lo-fi tone.',
  'preset.cinematic.name': 'Cinematic',
  'preset.cinematic.description': 'Cathedral-scale reverb and rich resonance for ambient scoring.',
  'preset.honkytonk.name': 'Honky-Tonk',
  'preset.honkytonk.description': 'An out-of-tune upright feel, like a piano in an old saloon.',

  'demo.bwv846.title': 'Prelude No. 1 in C major, BWV 846',
  'demo.bwv846.composer': 'J.S. Bach',
  'demo.furelise.title': 'Für Elise, WoO 59',
  'demo.furelise.composer': 'L.v. Beethoven',
  'demo.moonlight.title': 'Piano Sonata No. 14 "Moonlight", 1st mvt.',
  'demo.moonlight.composer': 'L.v. Beethoven',
  'demo.canon.title': 'Canon in D',
  'demo.canon.composer': 'J. Pachelbel',
  'demo.minuet.title': 'Minuet in G, BWV Anh.114',
  'demo.minuet.composer': 'C. Petzold',
  'demo.odetojoy.title': 'Ode to Joy (from Symphony No. 9)',
  'demo.odetojoy.composer': 'L.v. Beethoven',
  'demo.twinkle.title': 'Twinkle, Twinkle, Little Star',
  'demo.twinkle.composer': 'French folk song',
  'demo.amazinggrace.title': 'Amazing Grace',
  'demo.amazinggrace.composer': 'Hymn',
  'demo.greensleeves.title': 'Greensleeves',
  'demo.greensleeves.composer': 'English folk song',
  'demo.waltz.title': 'Waltz Under Falling Stars',
  'demo.waltz.composer': 'Original',
  'demo.ballad.title': 'Ballad of Summer\'s End',
  'demo.ballad.composer': 'Original',
  'demo.nocturne.title': 'Nocturne at Dawn',
  'demo.nocturne.composer': 'Original',
  'demo.note.publicDomain': 'Public domain',
  'demo.note.original': 'Written for this app',
};

registerStrings(ja, en);
