import { registerStrings } from './i18n';

const ja = {
  'help.button': '?',
  'brand.subtitle': '物理モデリング・エレキベース',
  'preset.ariaLabel': '音色プリセット',
  'panic.label': '全停止',
  'panic.title': 'すべての音を止める（Esc）',
  'panic.ariaLabel': 'すべての音を止める',
  'fretboard.ariaLabel': 'ベースの指板',

  'position.range': '{first}〜{last}フレット',
  'position.muteAll': '全ミュート',

  'tab.tone': '音色',
  'tab.amp': 'アンプ',
  'tab.play': '演奏',
  'tab.rec': '録音',
  'tab.demo': 'フレーズ',

  'technique.finger.label': '指',
  'technique.finger.hint': '2フィンガー。基本の弾き方',
  'technique.pick.label': 'ピック',
  'technique.pick.hint': '硬いアタック',
  'technique.slap.label': 'スラップ',
  'technique.slap.hint': '親指で叩く',
  'technique.pop.label': 'プル',
  'technique.pop.hint': '指で引っ張る',
  'technique.mute.label': 'ミュート',
  'technique.mute.hint': 'ブリッジミュート',
  'technique.ghost.label': 'ゴースト',
  'technique.ghost.hint': '音程のない打音',
  'technique.harmonic.label': 'ハーモニクス',
  'technique.harmonic.hint': '5・7・12フレットで倍音',

  'panel.tonePresets': '音色プリセット',
  'ctl.brightness.label': '弦の明るさ',
  'ctl.brightness.hint': '使い込んだ弦 ← → 張りたての弦',
  'ctl.sustain.label': 'サステイン（余韻）',
  'ctl.stiffness.label': '弦の硬さ（ゴリッと感）',
  'ctl.stiffness.hint': '倍音が少しずれて生まれる、太い弦特有の唸り',
  'ctl.buzz.label': 'フレットのビビり',
  'ctl.buzz.hint': '弦高を下げるほど、強く弾いたときに「バチッ」と鳴ります',
  'ctl.pluckPos.label': '弾く位置',
  'ctl.pluckPos.hint': 'ブリッジ寄り（硬い） ← → ネック寄り（丸い）',
  'ctl.noise.label': '撥弦ノイズ',
  'ctl.noise.hint': '指やピックが弦に当たる音',
  'ctl.beat.label': 'うなり',
  'ctl.beat.hint': '縦振動と横振動のズレ。太さと生々しさが出ます',
  'ctl.sympathetic.label': '他弦の共鳴',
  'ctl.sympathetic.hint': '押さえていない弦がブリッジ越しに一緒に鳴ります',
  'panel.strings': '弦',

  'ctl.pickupBlend.label': 'ピックアップ・バランス',
  'ctl.pickupBlend.hint': 'フロントは太く、リアは細くて硬い音になります',
  'pickup.front': 'フロント',
  'pickup.rear': 'リア',
  'ctl.pickupTone.label': 'ピックアップの効き',
  'ctl.pickupTone.hint': 'コイルの共振。上げるほど抜けが良く、下げるとこもります',
  'ctl.pickupNeck.label': 'フロントPUの位置',
  'ctl.pickupNeck.hint': 'ブリッジからの距離。倍音の欠け方が変わります',
  'ctl.pickupBridge.label': 'リアPUの位置',
  'panel.pickups': 'ピックアップ',

  'ctl.drive.label': 'ドライブ（歪み）',
  'ctl.drive.hint': '低音はクリーンのまま、中高域だけを歪ませます',
  'ctl.comp.label': 'コンプレッサー',
  'ctl.comp.hint': '粒を揃えます。指弾きやスラップで特に有効',
  'ctl.ampMidFreq.label': 'MIDDLE の周波数',
  'ctl.ampMidFreq.hint': '250Hz付近は太さ、800Hz付近は輪郭に効きます',
  'panel.amp': 'アンプ',
  'panel.cabinet': 'キャビネット',
  'fx.off': 'オフ',
  'ctl.wah.label': 'オートワウ',
  'ctl.wah.hint': '弾く強さでフィルターが開くエンベロープフィルター',
  'ctl.wahSens.label': 'ワウの戻りの速さ',
  'ctl.chorus.label': 'コーラス',
  'ctl.chorus.hint': 'フレットレスやバラードで広がりが出ます',
  'reverb.label': '残響',
  'ctl.reverbMix.label': '残響の量',
  'ctl.volume.label': 'マスター音量',
  'panel.fx': 'エフェクト',
  'amp.note': 'キャビネットも残響も、その場で計算して作っています。音声ファイルのダウンロードは一切ありません。',

  'cab.di.label': 'DI（ライン）',
  'cab.di.hint': 'キャビネットを通さない素の音。宅録・打ち込み向き',
  'cab.1x15.label': '1×15"',
  'cab.1x15.hint': '大口径1発。丸くて太い、モータウン系の音',
  'cab.4x10.label': '4×10"',
  'cab.4x10.hint': '万能。芯があって抜けが良い、いちばん使いやすい',
  'cab.8x10.label': '8×10"',
  'cab.8x10.hint': '定番の巨大キャビ。低域の圧と歪みの相性が良い',

  'reverb.room.label': 'ルーム',
  'reverb.studio.label': 'スタジオ',
  'reverb.hall.label': 'ホール',

  'panel.instrument': '楽器',
  'ctl.tuning.label': 'チューニング',
  'tuning.standard4.name': '4弦 レギュラー',
  'tuning.standard4.hint': 'E1 A1 D2 G2 ・ 最も標準的',
  'tuning.dropd4.name': '4弦 ドロップD',
  'tuning.dropd4.hint': 'D1 A1 D2 G2 ・ ロック／メタル',
  'tuning.halfdown4.name': '4弦 半音下げ',
  'tuning.halfdown4.hint': 'E♭1 A♭1 D♭2 G♭2',
  'tuning.wholedown4.name': '4弦 1音下げ',
  'tuning.wholedown4.hint': 'D1 G1 C2 F2 ・ 重心の低いサウンド',
  'tuning.standard5.name': '5弦 (低B)',
  'tuning.standard5.hint': 'B0 E1 A1 D2 G2 ・ 低音の拡張',
  'tuning.high5.name': '5弦 (高C)',
  'tuning.high5.hint': 'E1 A1 D2 G2 C3 ・ ソロ向き',
  'tuning.standard6.name': '6弦',
  'tuning.standard6.hint': 'B0 E1 A1 D2 G2 C3',

  'ctl.fretless.label': 'フレットレス',
  'ctl.fretless.hint': 'フレットの無い指板。スライドが滑らかになります',
  'ctl.letRing.label': '指を離しても鳴らし続ける',
  'ctl.letRing.hint': 'オフにすると、指を離した瞬間に音が止まります',
  'ctl.labelMode.label': '指板の音名表示',
  'labelMode.off': 'なし',
  'labelMode.root': 'ルートのみ',
  'labelMode.all': 'すべて',
  'ctl.rootPitch.label': 'キー（ルート音を光らせる）',
  'rootPitch.none': '指定しない',
  'ctl.fretCount.label': '表示するフレット数',
  'ctl.touch.label': 'タッチの強さ',
  'ctl.touch.hint': '筆圧に対応した端末では、押す強さでも変化します',
  'panel.touch': 'タッチ',

  'ctl.a4.label': '基準ピッチ A4',
  'ctl.velCurve.label': 'ベロシティカーブ',
  'ctl.velCurve.hint': '大きいほど強く弾かないと音量が出ません',
  'ctl.dynamics.label': 'ダイナミクス',
  'ctl.release.label': 'ミュートの速さ',
  'ctl.release.hint': '指を置いてから音が止まるまでの速さ',
  'ctl.glide.label': 'スライドの速さ',

  'rhythm.click.name': 'クリック',
  'rhythm.rock8.name': '8ビート',
  'rhythm.rock16.name': '16ビート',
  'rhythm.shuffle.name': 'シャッフル',
  'rhythm.funk.name': 'ファンク',
  'rhythm.halftime.name': 'ハーフタイム',
  'rhythm.latin.name': 'ラテン',

  'panel.practiceTools': '練習ツール',
  'ctl.rhythm.label': 'リズム',
  'ctl.tempo.label': 'テンポ',
  'ctl.rhythmVolume.label': 'リズムの音量',
  'ctl.rhythmToggle.label': 'リズムを鳴らす',
  'ctl.rhythmToggle.hint': 'スペースキーでも切り替えられます',

  'panel.midi': 'MIDI',
  'midi.reconnect': 'MIDI 再検出',
  'midi.connect': 'MIDIキーボードを接続',
  'midi.connected': '接続中: {devices}',
  'midi.hint': 'MIDIキーボードの音は、自動でいちばん自然な弦とフレットに割り当てられます。',
  'midi.unsupported': 'このブラウザは Web MIDI に対応していません（Chrome / Edge 推奨）。',

  'panel.record': '録音と書き出し',
  'record.start': '● 録音開始',
  'record.stop': '■ 録音停止',
  'record.play': '▶ 再生',
  'record.clear': 'クリア',
  'record.empty': '録音すると、演奏がイベントとして記録されます。あとから音色を変えて書き出せます。',
  'record.count': '録音済み: {count} 音 / {time}',
  'panel.file': 'ファイル',
  'export.wav': 'WAV で書き出し',
  'export.midi': 'MIDI で書き出し',
  'export.exporting': '書き出し中…',
  'export.note': 'WAV は 48kHz / 24bit・ステレオで、現在の音色のまま再合成して書き出します。作成した音源の利用に制限はありません（商用利用も自由です）。',

  'panel.demo': 'デモ・フレーズ',
  'demo.play': '▶ 再生',
  'demo.stop': '■ 停止',
  'demo.useDemoPreset': '推奨音色とリズムに切り替えて再生する',
  'demo.note': 'デモはすべて本アプリのオリジナル・フレーズです（権利処理は不要）。再生中の演奏もそのまま WAV / MIDI に書き出せます。',

  'preset.vintage.name': 'ヴィンテージ・フィンガー',
  'preset.vintage.description': 'フロントPU＋古い弦の丸い音。モータウンや歌モノの土台に。',
  'preset.modern.name': 'モダン・フィンガー',
  'preset.modern.description': '両PUミックスの万能サウンド。どんな曲にも馴染む基本の音。',
  'preset.pickrock.name': 'ピック・ロック',
  'preset.pickrock.description': 'ピック弾きの硬いアタック。ギターの壁の中でも輪郭が消えない。',
  'preset.slapfunk.name': 'スラップ・ファンク',
  'preset.slapfunk.description': '低域と高域を持ち上げた「ドンシャリ」。親指と人差し指のための音。',
  'preset.autowah.name': 'オートワウ・ファンク',
  'preset.autowah.description': '弾く強さでフィルターが開くエンベロープフィルター。16分のカッティングに。',
  'preset.fretless.name': 'フレットレス',
  'preset.fretless.description': 'フレットの無い指板の「ムワッ」とした鳴り。スライドで歌わせる音。',
  'preset.jazz.name': 'ウォーキング・ジャズ',
  'preset.jazz.description': '減衰の速い太い音。ウッドベースに寄せた4ビート向けの設定。',
  'preset.dub.name': 'ダブ／レゲエ',
  'preset.dub.description': '高域を完全に落とした地を這う低音。ルート弾きが気持ちいい。',
  'preset.grind.name': 'グラインド・ドライブ',
  'preset.grind.description': '歪ませても低音が痩せない、真空管アンプ風のオーバードライブ。',
  'preset.flatline.name': 'DI クリーン',
  'preset.flatline.description': 'キャビネットを通さない素の音。打ち込みやミックスの素材に。',

  'demo.rock8.title': 'ロック 8ビート',
  'demo.rock8.style': 'ピック弾き',
  'demo.rock8.note': 'ルート主体の8分。まずはこれが弾ければバンドで通用します',
  'demo.motown.title': 'モータウン風',
  'demo.motown.style': '指弾き',
  'demo.motown.note': '歌の隙間を埋めるように動く、ソウル／R&B の定番ライン',
  'demo.walking.title': 'ウォーキング・ジャズ',
  'demo.walking.style': '4ビート',
  'demo.walking.note': 'II-V-I を歩き回る4分音符。ゴーストノートで推進力を出しています',
  'demo.slapfunk.title': 'スラップ・ファンク',
  'demo.slapfunk.style': 'サム＆プル',
  'demo.slapfunk.note': '親指（スラップ）と人差し指（プル）、そして休符が主役の16ビート',
  'demo.disco.title': 'ディスコ・オクターブ',
  'demo.disco.style': '指弾き',
  'demo.disco.note': 'ルートとオクターブ上を行き来する、踊れる8分のライン',
  'demo.reggae.title': 'レゲエ／ダブ',
  'demo.reggae.style': 'ミュート',
  'demo.reggae.note': '1拍目を抜いた、うねる低音。音の隙間そのものがグルーヴになります',
  'demo.metal.title': 'メタル・ピック刻み',
  'demo.metal.style': 'ピック弾き',
  'demo.metal.note': '16分の高速ダウンピッキング。歪ませても輪郭が残ります',
  'demo.blues.title': 'ブルース・シャッフル',
  'demo.blues.style': '指弾き',
  'demo.blues.note': '12小節のブルース進行を、はねたリズムで',
  'demo.ballad.title': 'フレットレス・バラード',
  'demo.ballad.style': 'フレットレス',
  'demo.ballad.note': 'スライドで音程を繋ぐ、歌うようなライン',
  'demo.bossa.title': 'ボサノバ',
  'demo.bossa.style': '指弾き',
  'demo.bossa.note': 'ルートと5度だけで作る、ゆったりしたラテンの土台',

  'status.ready': '準備完了',
  'status.tapToStart': '指板をタップすると開始',
  'status.midi': 'MIDI: {devices}',
  'status.audioError': 'オーディオを開始できません: {err}',
  'status.midiFailed': 'MIDIデバイスに接続できませんでした',

  'flash.presetChanged': '音色: {name}',
  'flash.allStopped': 'すべての音を停止しました',
  'flash.recordStopped': '録音を停止しました',
  'flash.recording': '● 録音中',
  'flash.playbackEnded': '再生が終了しました',
  'flash.recordedPerformance': '録音した演奏',
  'flash.playing': '▶ {label}',
  'flash.demoLabel': '{title}（{style}）',
  'flash.noExportable': '書き出す演奏がありません',
  'flash.exportingWav': 'WAV を書き出しています…',
  'flash.wavSaved': 'WAV を保存しました',
  'flash.exportFailed': '書き出しに失敗しました: {err}',
  'flash.midiSaved': 'MIDI を保存しました',

  'help.title': '使い方',
  'help.play.term': '弾く',
  'help.play.desc': '指板をタップ／クリック（マルチタッチ対応）。下の段ほど低い弦です。',
  'help.slide.term': 'スライド',
  'help.slide.desc': '押さえたまま左右にドラッグすると、弾き直さずに音程が移動します。',
  'help.bend.term': 'チョーキング',
  'help.bend.desc': '押さえたまま上へドラッグすると音程が上がります。',
  'help.vibrato.term': 'ビブラート',
  'help.vibrato.desc': '押さえたまま指を小刻みに上下させると、チョーキングと同じ仕組みでビブラートがかかります。',
  'help.technique.term': '奏法',
  'help.technique.desc': '指板の下のボタンで、指弾き／ピック／スラップ／プル／ミュート／ゴースト／ハーモニクスを切り替えます。',
  'help.pcKeys.term': 'PCキーボード',
  'help.pcKeys.desc':
    '手前の段から順に低い弦。<br>Z X C V B N M , . / ＝ 1弦目 ／ A S D F G H J K L ; ＝ 2弦目 ／ Q W E R T Y U I O P ＝ 3弦目 ／ 1 2 3 4 5 6 7 8 9 0 ＝ 4弦目。左右キーでポジション移動、Shift で強く弾きます。',
  'help.rhythm.term': 'リズム',
  'help.rhythm.desc': 'スペースキーでドラム／メトロノームの開始・停止。',
  'help.rec.term': '録音',
  'help.rec.desc': '「録音」タブで演奏を記録し、WAV（48kHz/24bit）や MIDI として保存できます。',
  'help.aboutSoundTitle': 'この音について',
  'help.aboutSound':
    '録音されたベースの音（サンプル）は一切使っていません。弦の振動・弾く位置・ピックアップの位置・フレットとの衝突までを計算して、その場で音を合成しています。だからアプリ本体は数百KBで、追加ダウンロードも通信も不要です。',
  'help.free': '広告なし・追跡なし・アカウント登録なし。オフラインでも動作します。',
  'help.usage': '書き出した音源はご自由にお使いいただけます（商用利用可・クレジット表記不要）。',
  'help.privacy': 'プライバシーポリシー',
  'help.close': '閉じる',

  'lang.toggle': 'JP',
};

const en: typeof ja = {
  'help.button': '?',
  'brand.subtitle': 'Physically Modeled Electric Bass',
  'preset.ariaLabel': 'Tone preset',
  'panic.label': 'Stop All',
  'panic.title': 'Stop all sound (Esc)',
  'panic.ariaLabel': 'Stop all sound',
  'fretboard.ariaLabel': 'Bass fretboard',

  'position.range': 'Fret {first}–{last}',
  'position.muteAll': 'Mute All',

  'tab.tone': 'Tone',
  'tab.amp': 'Amp',
  'tab.play': 'Play',
  'tab.rec': 'Record',
  'tab.demo': 'Phrases',

  'technique.finger.label': 'Finger',
  'technique.finger.hint': 'Two-finger. The basic technique',
  'technique.pick.label': 'Pick',
  'technique.pick.hint': 'Hard attack',
  'technique.slap.label': 'Slap',
  'technique.slap.hint': 'Strike with the thumb',
  'technique.pop.label': 'Pop',
  'technique.pop.hint': 'Pull with the finger',
  'technique.mute.label': 'Mute',
  'technique.mute.hint': 'Bridge mute',
  'technique.ghost.label': 'Ghost',
  'technique.ghost.hint': 'Unpitched percussive note',
  'technique.harmonic.label': 'Harmonic',
  'technique.harmonic.hint': 'Overtones at frets 5, 7, 12',

  'panel.tonePresets': 'Tone Presets',
  'ctl.brightness.label': 'String Brightness',
  'ctl.brightness.hint': 'Worn-in strings ← → Fresh strings',
  'ctl.sustain.label': 'Sustain (Decay Length)',
  'ctl.stiffness.label': 'String Stiffness (Growl)',
  'ctl.stiffness.hint': 'A slight overtone shift that gives thick strings their growl',
  'ctl.buzz.label': 'Fret Buzz',
  'ctl.buzz.hint': 'The lower the action, the more it "buzzes" when played hard',
  'ctl.pluckPos.label': 'Pluck Position',
  'ctl.pluckPos.hint': 'Near the bridge (hard) ← → Near the neck (round)',
  'ctl.noise.label': 'Pluck Noise',
  'ctl.noise.hint': 'The sound of a finger or pick hitting the string',
  'ctl.beat.label': 'Beating',
  'ctl.beat.hint': 'A slight mismatch between vertical and horizontal vibration, adding thickness and realism',
  'ctl.sympathetic.label': 'Sympathetic Resonance',
  'ctl.sympathetic.hint': 'Unfretted strings ring faintly through the bridge',
  'panel.strings': 'Strings',

  'ctl.pickupBlend.label': 'Pickup Balance',
  'ctl.pickupBlend.hint': 'The front pickup is thicker, the rear pickup is thinner and harder',
  'pickup.front': 'Front',
  'pickup.rear': 'Rear',
  'ctl.pickupTone.label': 'Pickup Resonance',
  'ctl.pickupTone.hint': 'Coil resonance. Higher clears things up, lower muffles it',
  'ctl.pickupNeck.label': 'Front Pickup Position',
  'ctl.pickupNeck.hint': 'Distance from the bridge. Changes which overtones drop out',
  'ctl.pickupBridge.label': 'Rear Pickup Position',
  'panel.pickups': 'Pickups',

  'ctl.drive.label': 'Drive (Distortion)',
  'ctl.drive.hint': 'Keeps the lows clean while distorting only the mids and highs',
  'ctl.comp.label': 'Compressor',
  'ctl.comp.hint': 'Evens out the notes. Especially effective for fingerstyle and slap',
  'ctl.ampMidFreq.label': 'MIDDLE Frequency',
  'ctl.ampMidFreq.hint': 'Around 250Hz adds thickness, around 800Hz adds definition',
  'panel.amp': 'Amp',
  'panel.cabinet': 'Cabinet',
  'fx.off': 'Off',
  'ctl.wah.label': 'Auto-Wah',
  'ctl.wah.hint': 'An envelope filter that opens with your playing dynamics',
  'ctl.wahSens.label': 'Wah Release Speed',
  'ctl.chorus.label': 'Chorus',
  'ctl.chorus.hint': 'Adds width, great for fretless or ballads',
  'reverb.label': 'Reverb',
  'ctl.reverbMix.label': 'Reverb Amount',
  'ctl.volume.label': 'Master Volume',
  'panel.fx': 'Effects',
  'amp.note': 'Both the cabinet and reverb are computed in real time. There are no audio files to download.',

  'cab.di.label': 'DI (Line)',
  'cab.di.hint': 'The raw sound with no cabinet. Good for home recording and programming',
  'cab.1x15.label': '1×15"',
  'cab.1x15.hint': 'A single large driver. Round and fat, a Motown-style sound',
  'cab.4x10.label': '4×10"',
  'cab.4x10.hint': 'All-purpose. Has a solid core and cuts through well — the easiest to use',
  'cab.8x10.label': '8×10"',
  'cab.8x10.hint': 'A classic giant cabinet. Pairs well with low-end pressure and distortion',

  'reverb.room.label': 'Room',
  'reverb.studio.label': 'Studio',
  'reverb.hall.label': 'Hall',

  'panel.instrument': 'Instrument',
  'ctl.tuning.label': 'Tuning',
  'tuning.standard4.name': '4-String Standard',
  'tuning.standard4.hint': 'E1 A1 D2 G2 ・ The most common tuning',
  'tuning.dropd4.name': '4-String Drop D',
  'tuning.dropd4.hint': 'D1 A1 D2 G2 ・ Rock / Metal',
  'tuning.halfdown4.name': '4-String Half-Step Down',
  'tuning.halfdown4.hint': 'E♭1 A♭1 D♭2 G♭2',
  'tuning.wholedown4.name': '4-String Whole-Step Down',
  'tuning.wholedown4.hint': 'D1 G1 C2 F2 ・ A low-centered sound',
  'tuning.standard5.name': '5-String (Low B)',
  'tuning.standard5.hint': 'B0 E1 A1 D2 G2 ・ Extended low range',
  'tuning.high5.name': '5-String (High C)',
  'tuning.high5.hint': 'E1 A1 D2 G2 C3 ・ Great for solos',
  'tuning.standard6.name': '6-String',
  'tuning.standard6.hint': 'B0 E1 A1 D2 G2 C3',

  'ctl.fretless.label': 'Fretless',
  'ctl.fretless.hint': 'A fretboard with no frets. Slides become smooth',
  'ctl.letRing.label': 'Let Ring After Release',
  'ctl.letRing.hint': 'When off, the note stops the instant you release',
  'ctl.labelMode.label': 'Fretboard Note Names',
  'labelMode.off': 'Off',
  'labelMode.root': 'Root Only',
  'labelMode.all': 'All',
  'ctl.rootPitch.label': 'Key (Highlight the Root Note)',
  'rootPitch.none': 'None',
  'ctl.fretCount.label': 'Frets Shown',
  'ctl.touch.label': 'Touch Sensitivity',
  'ctl.touch.hint': 'On devices that support pressure, harder presses also change the sound',
  'panel.touch': 'Touch',

  'ctl.a4.label': 'Reference Pitch A4',
  'ctl.velCurve.label': 'Velocity Curve',
  'ctl.velCurve.hint': 'Higher values require harder playing to reach full volume',
  'ctl.dynamics.label': 'Dynamics',
  'ctl.release.label': 'Mute Speed',
  'ctl.release.hint': 'How quickly the note stops after you rest your finger',
  'ctl.glide.label': 'Slide Speed',

  'rhythm.click.name': 'Click',
  'rhythm.rock8.name': '8th-Note Rock',
  'rhythm.rock16.name': '16th-Note Rock',
  'rhythm.shuffle.name': 'Shuffle',
  'rhythm.funk.name': 'Funk',
  'rhythm.halftime.name': 'Half-Time',
  'rhythm.latin.name': 'Latin',

  'panel.practiceTools': 'Practice Tools',
  'ctl.rhythm.label': 'Rhythm',
  'ctl.tempo.label': 'Tempo',
  'ctl.rhythmVolume.label': 'Rhythm Volume',
  'ctl.rhythmToggle.label': 'Play Rhythm',
  'ctl.rhythmToggle.hint': 'Can also be toggled with the Space key',

  'panel.midi': 'MIDI',
  'midi.reconnect': 'Rescan MIDI',
  'midi.connect': 'Connect MIDI Keyboard',
  'midi.connected': 'Connected: {devices}',
  'midi.hint': 'MIDI notes are automatically assigned to the most natural string and fret.',
  'midi.unsupported': 'This browser does not support Web MIDI (Chrome / Edge recommended).',

  'panel.record': 'Record & Export',
  'record.start': '● Start Recording',
  'record.stop': '■ Stop Recording',
  'record.play': '▶ Play',
  'record.clear': 'Clear',
  'record.empty': 'Recording captures your performance as events, so you can change the tone afterward and export it.',
  'record.count': 'Recorded: {count} notes / {time}',
  'panel.file': 'File',
  'export.wav': 'Export as WAV',
  'export.midi': 'Export as MIDI',
  'export.exporting': 'Exporting…',
  'export.note': 'WAV is re-synthesized in the current tone at 48kHz / 24-bit stereo. There are no restrictions on using the exported audio (commercial use is fine).',

  'panel.demo': 'Demo Phrases',
  'demo.play': '▶ Play',
  'demo.stop': '■ Stop',
  'demo.useDemoPreset': 'Switch to the recommended tone and rhythm when playing',
  'demo.note': 'All demos are original phrases created for this app (no rights clearance needed). The performance can be exported directly as WAV / MIDI while it plays.',

  'preset.vintage.name': 'Vintage Finger',
  'preset.vintage.description': 'Front pickup plus the round tone of old strings. A foundation for Motown and vocal tunes.',
  'preset.modern.name': 'Modern Finger',
  'preset.modern.description': 'An all-purpose sound blending both pickups. The go-to tone that fits any song.',
  'preset.pickrock.name': 'Pick Rock',
  'preset.pickrock.description': 'A hard pick attack that keeps its edge even inside a wall of guitars.',
  'preset.slapfunk.name': 'Slap Funk',
  'preset.slapfunk.description': 'A scooped tone boosting lows and highs, built for thumb and index finger.',
  'preset.autowah.name': 'Auto-Wah Funk',
  'preset.autowah.description': 'An envelope filter that opens with your playing dynamics, great for 16th-note cutting.',
  'preset.fretless.name': 'Fretless',
  'preset.fretless.description': 'The smooth, mwah-like tone of a fretless board. A voice that sings through slides.',
  'preset.jazz.name': 'Walking Jazz',
  'preset.jazz.description': 'A fast-decaying, thick tone. Set up for 4-beat walking lines close to an upright bass.',
  'preset.dub.name': 'Dub / Reggae',
  'preset.dub.description': 'A ground-hugging low end with the highs cut entirely. Root notes feel great.',
  'preset.grind.name': 'Grind Drive',
  'preset.grind.description': 'Tube-amp-style overdrive that keeps the low end full even when distorted.',
  'preset.flatline.name': 'DI Clean',
  'preset.flatline.description': 'The raw sound with no cabinet. Great material for programming or mixing.',

  'demo.rock8.title': '8th-Note Rock',
  'demo.rock8.style': 'Pick',
  'demo.rock8.note': 'A root-driven 8th-note line. Master this first and you can hold down any band.',
  'demo.motown.title': 'Motown Style',
  'demo.motown.style': 'Fingerstyle',
  'demo.motown.note': 'A classic soul/R&B line that moves to fill the gaps between vocal phrases.',
  'demo.walking.title': 'Walking Jazz',
  'demo.walking.style': '4-Beat',
  'demo.walking.note': 'Quarter notes walking through a II-V-I. Ghost notes add forward drive.',
  'demo.slapfunk.title': 'Slap Funk',
  'demo.slapfunk.style': 'Thumb & Pull',
  'demo.slapfunk.note': 'A 16th-note groove starring the thumb (slap), index finger (pull), and rests.',
  'demo.disco.title': 'Disco Octaves',
  'demo.disco.style': 'Fingerstyle',
  'demo.disco.note': 'A danceable 8th-note line moving between the root and the octave above.',
  'demo.reggae.title': 'Reggae / Dub',
  'demo.reggae.style': 'Muted',
  'demo.reggae.note': 'A rolling low end with beat one dropped out — the gap itself becomes the groove.',
  'demo.metal.title': 'Metal Pick Chugging',
  'demo.metal.style': 'Pick',
  'demo.metal.note': 'Fast 16th-note downpicking that keeps its edge even when distorted.',
  'demo.blues.title': 'Blues Shuffle',
  'demo.blues.style': 'Fingerstyle',
  'demo.blues.note': 'A 12-bar blues progression, played with a shuffle feel.',
  'demo.ballad.title': 'Fretless Ballad',
  'demo.ballad.style': 'Fretless',
  'demo.ballad.note': 'A singing line that connects pitches with slides.',
  'demo.bossa.title': 'Bossa Nova',
  'demo.bossa.style': 'Fingerstyle',
  'demo.bossa.note': 'A relaxed Latin foundation built from just the root and the fifth.',

  'status.ready': 'Ready',
  'status.tapToStart': 'Tap the fretboard to start',
  'status.midi': 'MIDI: {devices}',
  'status.audioError': 'Could not start audio: {err}',
  'status.midiFailed': 'Could not connect to the MIDI device',

  'flash.presetChanged': 'Tone: {name}',
  'flash.allStopped': 'All sound stopped',
  'flash.recordStopped': 'Recording stopped',
  'flash.recording': '● Recording',
  'flash.playbackEnded': 'Playback finished',
  'flash.recordedPerformance': 'Recorded performance',
  'flash.playing': '▶ {label}',
  'flash.demoLabel': '{title} ({style})',
  'flash.noExportable': 'There is no performance to export',
  'flash.exportingWav': 'Exporting WAV…',
  'flash.wavSaved': 'WAV saved',
  'flash.exportFailed': 'Export failed: {err}',
  'flash.midiSaved': 'MIDI saved',

  'help.title': 'How to Play',
  'help.play.term': 'Play',
  'help.play.desc': 'Tap or click the fretboard (multi-touch supported). Lower rows are lower strings.',
  'help.slide.term': 'Slide',
  'help.slide.desc': 'Drag left or right while holding to change pitch without replucking.',
  'help.bend.term': 'Bend',
  'help.bend.desc': 'Drag upward while holding to raise the pitch.',
  'help.vibrato.term': 'Vibrato',
  'help.vibrato.desc': 'Wiggle your finger up and down slightly while holding — it uses the same bend mechanism to add vibrato.',
  'help.technique.term': 'Technique',
  'help.technique.desc': 'Use the buttons below the fretboard to switch between finger, pick, slap, pop, mute, ghost, and harmonic.',
  'help.pcKeys.term': 'Computer Keyboard',
  'help.pcKeys.desc':
    'The front row is the lowest string.<br>Z X C V B N M , . / = string 1 / A S D F G H J K L ; = string 2 / Q W E R T Y U I O P = string 3 / 1 2 3 4 5 6 7 8 9 0 = string 4. Arrow keys shift position, Shift plays harder.',
  'help.rhythm.term': 'Rhythm',
  'help.rhythm.desc': 'Press the Space key to start or stop the drums/metronome.',
  'help.rec.term': 'Record',
  'help.rec.desc': 'Use the Record tab to capture a performance and save it as WAV (48kHz/24bit) or MIDI.',
  'help.aboutSoundTitle': 'About the Sound',
  'help.aboutSound':
    'No recorded bass samples are used at all. The vibration of the strings, pluck position, pickup position, and even fret contact are all computed and synthesized in real time. That is why the app itself is only a few hundred KB, with no extra downloads or network access required.',
  'help.free': 'No ads, no tracking, no account registration. Works offline too.',
  'help.usage': 'Exported audio is yours to use freely (commercial use is fine, no credit required).',
  'help.privacy': 'Privacy Policy',
  'help.close': 'Close',

  'lang.toggle': 'EN',
};

registerStrings(ja, en);
