import { registerStrings } from './i18n';

const ja = {
  'help.button': '?',
  'lang.toggle': 'JP',
  'brand.subtitle': '物理モデリング・ギター',
  'preset.ariaLabel': '音色プリセット',
  'panic.label': '全停止',
  'panic.title': 'すべての音を止める（Esc）',
  'panic.ariaLabel': 'すべての音を止める',

  'tab.chord': 'コード',
  'tab.backing': '伴奏',
  'tab.string': '弦',
  'tab.amp': 'アンプ',
  'tab.space': 'エフェクト',
  'tab.play': '演奏',
  'tab.rec': '録音',
  'tab.demo': 'デモ',

  'palm.label': 'ブリッジミュート',
  'palm.title': 'M キーでも切り替えられます',
  'strum.down': '▼ ダウン',
  'strum.up': '▲ アップ',
  'mute.label': 'ミュート',

  'status.ready': '準備完了',
  'status.tapToStart': '指板に触れると開始',
  'status.capo': 'カポ {n}',
  'status.midi': 'MIDI: {devices}',

  'chord.hint': 'パッドをタップでダウンストローク、上へスワイプでアップストローク。選んだコードの押さえ方は指板に表示されます。',
  'ctl.strumSpeed.label': 'ストロークの速さ',
  'unit.msPerString': 'ms/弦',
  'ctl.strumSpeed.hint': '隣り合う弦を弾く間隔。大きいほどゆっくり「ジャラーン」と鳴ります。',

  'panel.rhythmPattern.title': 'リズムパターン',
  'ctl.pattern.label': 'パターン',
  'ctl.tempo.label': 'テンポ',
  'ctl.humanize.label': '人間らしさ',
  'ctl.humanize.hint': 'タイミングと強さを少しだけ揺らします。',
  'panel.progression.title': 'コード進行',
  'panel.progression.hint': '1マス＝1小節。タップで削除できます。',
  'progression.empty': 'コードがありません。下のボタンで追加してください。',
  'slot.title': 'タップで削除',
  'action.addSelected': '選択中のコードを追加',
  'status.selectChordFirst': '先に「コード」タブでコードを選んでください',
  'action.clearAll': 'すべて消す',
  'panel.backingPlayback.title': '伴奏の再生',
  'backing.stop': '■ 停止',
  'backing.play': '▶ 伴奏を再生',
  'action.exportBackingWav': 'WAVで書き出す',
  'ctl.loopBacking.label': '繰り返し再生',

  'ctl.pickPos.label': 'ピッキング位置',
  'pickPos.bridge': 'ブリッジ寄り',
  'pickPos.neck': 'ネック寄り',
  'pickPos.standard': '標準',
  'ctl.pickPos.hint': 'ブリッジ寄りほど硬く、ネック寄りほど丸い音になります。',
  'ctl.pickHard.label': 'ピックの硬さ',
  'pickHard.finger': '指',
  'pickHard.hard': '硬いピック',
  'pickHard.normal': '普通のピック',
  'ctl.brightness.label': '弦の明るさ',
  'ctl.brightness.hint': '高域の伸び。新品の弦ほど明るく鳴ります。',
  'ctl.sustain.label': 'サステイン',
  'ctl.stiffness.label': '弦の張り（倍音のずれ）',
  'ctl.stiffness.hint': '太い弦ほど倍音が少し高めにずれます。金属的な質感の元。',
  'ctl.coupling.label': '弦どうしの共鳴',
  'ctl.coupling.hint': 'ブリッジを介して他の弦が共鳴します。',
  'ctl.pickNoise.label': 'ピックのアタック音',
  'ctl.fretNoise.label': '指のこすれ音',
  'ctl.fretNoise.hint': 'スライドしたときのキュッという音。',
  'ctl.buzz.label': 'ビビり',
  'ctl.buzz.hint': '強く弾いたときだけ出るバズ音。',
  'ctl.spread.label': '左右の広がり',
  'panel.body.title': 'ボディ（胴鳴り）',
  'panel.body.hint': 'アコースティックの箱の響き。エレキでは「なし」に。',
  'ctl.bodyType.label': '種類',
  'ctl.bodyMix.label': '胴鳴りの量',

  'body.none.label': 'なし（エレキ）',
  'body.dread.label': 'ドレッドノート',
  'body.parlor.label': 'パーラー（小型）',
  'body.nylon.label': 'クラシック（ナイロン）',
  'body.archtop.label': 'アーチトップ',
  'body.resonator.label': 'リゾネーター（金属）',

  'ctl.amp.label': 'アンプ',
  'ctl.amp.hint': 'アコースティックは「アンプなし」。',
  'ctl.driveType.label': '歪み',
  'drive.off': 'なし',
  'drive.boost': 'ブースター',
  'drive.overdrive': 'オーバードライブ',
  'drive.distortion': 'ディストーション',
  'drive.fuzz': 'ファズ',
  'ctl.driveAmount.label': 'ドライブ量',
  'ctl.compress.label': 'コンプレッサー',
  'ctl.compress.hint': '粒を揃えてサステインを伸ばします。カッティングに有効。',
  'panel.eq.title': 'イコライザー',
  'eq.bass': 'ロー',
  'eq.mid': 'ミドル',
  'eq.treble': 'ハイ',
  'eq.presence': 'プレゼンス',
  'ctl.cabinet.label': 'キャビネット',
  'cab.off.label': 'なし（ラインアウト）',
  'ctl.cabinet.hint': 'スピーカーの箱の特性。歪ませるときは必ず通すと自然になります。',

  'amp.off.label': 'アンプなし（生音）',
  'amp.clean.label': 'クリーン',
  'amp.tweed.label': 'ツイード',
  'amp.british.label': 'ブリティッシュ',
  'amp.modern.label': 'モダンハイゲイン',
  'amp.bassamp.label': 'ベースアンプ',

  'cab.combo1x12.label': '1x12 コンボ',
  'cab.twin2x12.label': '2x12 ツイン',
  'cab.stack4x12.label': '4x12 スタック',
  'cab.bass8x10.label': '8x10 ベースキャビ',

  'panel.mod.title': 'モジュレーション',
  'ctl.modType.label': '種類',
  'mod.off': 'なし',
  // --- 追加エフェクター（ドラム／ベースと共通の実装。重ねがけできる） ---
  'panel.pedals.title': 'エフェクター（重ねがけ）',
  'panel.pedals.hint': '上のモジュレーションとは別に、いくつでも同時にかけられます',
  'ctl.flanger.label': 'フランジャー',
  'ctl.flanger.hint': 'ジェット機のように鋭く唸らせる',
  'ctl.flangerRate.label': 'フランジャーの速さ',
  'ctl.flangerDepth.label': 'フランジャーの深さ',
  'ctl.flangerFeedback.label': 'フランジャーの返し',
  'ctl.flangerMix.label': 'フランジャーの混ぜ量',
  'ctl.filterMode.label': 'フィルター',
  'ctl.filterMode.hint': 'ワウとは別に、帯域を削ったりうねらせたりします',
  'filter.lowpass': 'ローパス',
  'filter.highpass': 'ハイパス',
  'filter.bandpass': 'バンドパス',
  'ctl.filterFreq.label': 'カットオフ',
  'ctl.filterQ.label': 'レゾナンス',
  'ctl.filterQ.hint': '上げるとカットオフ付近が強調されてクセが出る',
  'ctl.filterLfoRate.label': '揺らしの速さ',
  'ctl.filterLfoDepth.label': '揺らしの深さ',
  'ctl.filterLfoDepth.hint': '0 で固定。上げるとワウのようにカットオフが動く',
  'ctl.crushBits.label': 'ビットクラッシャー',
  'ctl.crushBits.hint': 'ビット数を落として粗いレトロな質感にする',
  'ctl.crushMix.label': 'クラッシュの混ぜ量',
  'ctl.ring.label': 'リングモジュレーター',
  'ctl.ring.hint': 'サイン波を掛け合わせて金属的・非音楽的な響きにする',
  'ctl.ringFreq.label': 'リングの周波数',
  'ctl.ringMix.label': 'リングの混ぜ量',
  'ctl.autopanDepth.label': 'オートパン',
  'ctl.autopanDepth.hint': '音を左右に自動で振る。0 で切',
  'ctl.autopanRate.label': 'オートパンの速さ',
  'ctl.width.label': 'ステレオ幅',
  'ctl.width.hint': '100% でそのまま。下げるとモノラル、上げると左右に広がる',
  'width.mono': 'モノラル',

  'mod.chorus': 'コーラス',
  'mod.vibrato': 'ビブラート',
  'mod.phaser': 'フェイザー',
  'mod.tremolo': 'トレモロ',
  'mod.wah': 'オートワウ',
  'ctl.modRate.label': '速さ',
  'ctl.modDepth.label': '深さ',
  'panel.delay.title': 'ディレイ',
  'ctl.delayMix.label': 'ディレイ量',
  'delay.off': 'オフ',
  'ctl.delayTime.label': 'ディレイタイム',
  'ctl.delayFeedback.label': 'フィードバック',
  'delay.quarter': '4分',
  'delay.dottedEighth': '付点8分',
  'delay.eighth': '8分',
  'delay.sixteenth': '16分',
  'delay.syncHint': 'テンポ（{bpm} BPM）に合わせる:',
  'panel.reverb.title': 'リバーブ',
  'ctl.reverbType.label': '種類',
  'reverb.off': 'なし',
  'ctl.reverbAmount.label': 'リバーブ量',
  'ctl.masterVolume.label': 'マスター音量',
  'ctl.outputTrim.label': '出力トリム',
  'ctl.outputTrim.hint': '音色ごとの音量差をならすための補正。プリセットを選ぶと自動で設定されます。',

  'room.room.label': 'ルーム',
  'room.plate.label': 'プレート',
  'room.spring.label': 'スプリング',
  'room.hall.label': 'ホール',

  'panel.tuning.title': 'チューニング',
  'ctl.tuningSelect.label': '調弦',
  'ctl.capo.label': 'カポ',
  'capo.none': 'なし',
  'capo.fret': '{v} フレット',
  'ctl.a4.label': '基準ピッチ',
  'tuner.stringLabel': '{n}弦 {note}',
  'tuner.hint': 'タップすると基準音が鳴ります（耳で合わせるチューナー）:',
  'panel.boardDisplay.title': '指板の表示',
  'ctl.fretCount.label': '表示するフレット数',
  'fretCount.value': '{v} フレット',
  'ctl.labelMode.label': '音名の表示',
  'labelMode.off': 'なし',
  'labelMode.note': '音名',
  'labelMode.degree': '度数',
  'ctl.labelMode.hint': '「度数」は選んだコードのルートから見た音の役割を表示します。',
  'panel.metronome.title': 'メトロノーム',
  'metro.stop': '■ 停止',
  'metro.start': '▶ 開始',
  'panel.input.title': '入力',
  'ctl.velCurve.label': 'ベロシティカーブ',
  'velCurve.light': '軽い',
  'velCurve.heavy': '重い',
  'velCurve.standard': '標準',
  'midi.reconnect': 'MIDI 再検出',
  'midi.connect': 'MIDIキーボードを使う',
  'midi.hint': 'MIDIノートは自動で弦とフレットに割り当てられます。',
  'midi.unsupported': 'このブラウザは Web MIDI に対応していません。',
  'keyboard.hint': 'PCキーボード: Space=ダウンストローク / Shift+Space=アップ / 1〜6=各弦 / Z〜M・Q〜P=音階 / M=ブリッジミュート / Esc=全停止',

  'record.stop': '■ 録音停止',
  'record.start': '● 録音開始',
  'record.play': '▶ 再生',
  'record.clear': '消去',
  'record.empty': '録音すると、演奏そのもの（弾いた弦・フレット・強さ）が記録されます。後から音色を変えて書き出すこともできます。',
  'record.count': '{count} 個のイベント / {time}',
  'panel.export.title': '書き出し',
  'export.wav': 'WAVで書き出す',
  'export.midi': 'MIDIで書き出す',
  'export.hint': 'WAV は今の音色設定でオフライン合成します（実時間より速く書き出せます）。MIDI は弦とフレットを実音に直して保存します。',

  'demo.hint': 'コード進行とリズムから自動で演奏します。再生すると音色プリセットも切り替わります。',
  'demo.stop': '■ 再生を止める',

  'status.audioError': 'オーディオを開始できません: {err}',
  'status.midiUnavailable': 'MIDIデバイスを利用できませんでした',
  'status.allStopped': 'すべて停止しました',
  'status.noRecording': '録音がありません',
  'flash.recordingPlayback': '録音の再生',
  'status.emptyProgression': 'コード進行が空です',
  'flash.backing': '伴奏',
  'status.nothingToExportLong': '書き出すものがありません（先に録音するかデモを再生してください）',
  'status.exporting': '書き出し中…',
  'status.wavExported': 'WAVを書き出しました',
  'status.exportFailed': '書き出しに失敗しました: {err}',
  'status.nothingToExport': '書き出すものがありません',
  'status.midiExported': 'MIDIを書き出しました',
  'status.playing': '再生中: {label}',
  'status.pcOctave': 'PCキー: C{n}',

  'help.title': 'Takibi Guitar の使い方',
  'help.play.heading': '弾く',
  'help.play.tap': '<b>指板をタップ</b> … その弦・フレットを弾きます。',
  'help.play.bendSlide': '<b>押したまま上下</b> … チョーキング。<b>左右</b> … スライド。',
  'help.play.vibrato': '<b>押さえたまま指を小刻みに上下</b> … チョーキングと同じ仕組みでビブラートがかかります。',
  'help.play.strumBar': '<b>指板の下の帯を左右になぞる</b> … ストローク。',
  'help.play.chordPad': '<b>コードタブのパッド</b> … タップでダウン、上へスワイプでアップストローク。',
  'help.keyboard.heading': 'キーボード',
  'help.keyboard.space': '<b>Space</b> … ダウンストローク（<b>Shift+Space</b> でアップ）',
  'help.keyboard.digits': '<b>1〜6</b> … その弦を単独で弾く',
  'help.keyboard.notes': '<b>Z〜M / Q〜P</b> … 音階（自動で弦とフレットに割り当て）',
  'help.keyboard.misc': '<b>↑↓</b> … オクターブ切替、<b>M</b> … ブリッジミュート、<b>Esc</b> … 全停止',
  'help.tone.heading': '音づくり',
  'help.tone.synthesis': 'サンプル音源は一切使わず、弦の振動をその場で計算しています。',
  'help.tone.tabs': '「弦」タブでピッキング位置や弦の明るさ、「アンプ」タブで歪みとEQ、「空間」タブで揺れ・ディレイ・残響を調整できます。',
  'help.create.heading': '作る',
  'help.create.backing': '「伴奏」タブでコード進行とリズムを決めると、自動で伴奏を演奏します。',
  'help.create.record': '「録音」タブで演奏を記録し、WAV / MIDI に書き出せます。',
  'help.note': 'すべてブラウザ内で動作します。音源のダウンロードも、通信も、課金もありません。',
  'help.close': '閉じる',

  'preset.steel.name': 'アコースティック（スチール弦）',
  'preset.steel.description': '定番のドレッドノート。弾き語りの基本の音。',
  'preset.strum.name': 'ストラム（ジャキッと）',
  'preset.strum.description': 'ピックで強めに弾いた、抜けの良いストローク向け。',
  'preset.fingerpick.name': 'フィンガーピッキング',
  'preset.fingerpick.description': '指弾きの柔らかいアタック。アルペジオに。',
  'preset.nylon.name': 'クラシックギター（ナイロン）',
  'preset.nylon.description': '柔らかく丸いナイロン弦。ボサノバやクラシックに。',
  'preset.parlor.name': 'パーラー（小型ボディ）',
  'preset.parlor.description': '小ぶりな箱の軽やかな鳴り。ブルースやラグタイムに。',
  'preset.resonator.name': 'リゾネーター（スライド）',
  'preset.resonator.description': '金属の共鳴板。ボトルネック奏法に。オープンGと相性◎',
  'preset.clean.name': 'エレキ・クリーン',
  'preset.clean.description': '素直なクリーントーン。コード弾きにもアルペジオにも。',
  'preset.funk.name': 'ファンク・カッティング',
  'preset.funk.description': 'コンプの効いた歯切れの良いカッティング。',
  'preset.jazz.name': 'ジャズ・アーチトップ',
  'preset.jazz.description': 'フロントピックアップの太く丸いトーン。',
  'preset.blues.name': 'ブルース・クランチ',
  'preset.blues.description': '軽く歪んだチューブアンプ。ピッキングの強弱で表情が出る。',
  'preset.british.name': 'ブリティッシュ・ロック',
  'preset.british.description': '中域の張り出したロックンロールの歪み。',
  'preset.metal.name': 'モダン・ハイゲイン',
  'preset.metal.description': 'ミッドを削った重い歪み。ブリッジミュートの刻みに。',
  'preset.fuzz.name': 'ファズ・リード',
  'preset.fuzz.description': '荒々しいファズ。単音リードで真価を発揮。',
  'preset.surf.name': 'サーフ（スプリング＋トレモロ）',
  'preset.surf.description': '揺れるトレモロとバネの残響。60年代のインスト。',
  'preset.ambient.name': 'アンビエント（ディレイ）',
  'preset.ambient.description': '深いディレイとホール。コードを置くだけで空間が広がる。',
  'preset.chorus.name': 'コーラス・クリーン',
  'preset.chorus.description': '80年代風の煌びやかなコーラス。アルペジオに。',
  'preset.wah.name': 'オートワウ・ファンク',
  'preset.wah.description': '周期的に動くワウ。カッティングと合わせて。',
  'preset.bass.name': 'エレキベース',
  'preset.bass.description': '4弦ベース。チューニングも自動でベースに切り替わります。',
  'preset.ukulele.name': 'ウクレレ',
  'preset.ukulele.description': '4弦ウクレレ。チューニングも自動で切り替わります。',

  'tuning.standard.name': 'スタンダード (EADGBE)',
  'tuning.standard.hint': '一般的な6弦ギターの調弦。',
  'tuning.dropd.name': 'ドロップD (DADGBE)',
  'tuning.dropd.hint': '6弦を1音下げ。パワーコードを1本指で押さえられる。',
  'tuning.halfdown.name': '半音下げ (E♭A♭D♭G♭B♭E♭)',
  'tuning.halfdown.hint': '全弦を半音下げ。太くルーズな響き。',
  'tuning.wholedown.name': '1音下げ (DGCFAD)',
  'tuning.wholedown.hint': '全弦を1音下げ。ヘヴィなリフ向け。',
  'tuning.dropc.name': 'ドロップC (CGCFAD)',
  'tuning.dropc.hint': '低く重いリフに。ラウド系で定番。',
  'tuning.dadgad.name': 'DADGAD',
  'tuning.dadgad.hint': 'ケルト/アコースティック系の変則調弦。浮遊感のある響き。',
  'tuning.openg.name': 'オープンG (DGDGBD)',
  'tuning.openg.hint': '開放でGメジャー。スライドやブルースに。',
  'tuning.opend.name': 'オープンD (DADF♯AD)',
  'tuning.opend.hint': '開放でDメジャー。ボトルネック向け。',
  'tuning.opene.name': 'オープンE (EBEG♯BE)',
  'tuning.opene.hint': '開放でEメジャー。荒々しいブルースに。',
  'tuning.bass.name': 'ベース4弦 (EADG)',
  'tuning.bass.hint': 'エレキベースの調弦。ベース音色と組み合わせて。',
  'tuning.ukulele.name': 'ウクレレ (GCEA)',
  'tuning.ukulele.hint': 'ハイG調弦のソプラノウクレレ。ナイロン音色で。',

  'pattern.whole.name': 'ジャーン（全音符）',
  'pattern.whole.hint': '小節あたま1回だけ。コードの響きを確かめるときに。',
  'pattern.eighth.name': '8ビート・ストローク',
  'pattern.eighth.hint': '8分の全ダウン。ロック/ポップスの基本。',
  'pattern.folk.name': 'フォーク（D DU UDU）',
  'pattern.folk.hint': '弾き語りの定番ストローク。',
  'pattern.sixteen.name': '16ビート・カッティング',
  'pattern.sixteen.hint': '空ピッキングを混ぜた16分。ファンク/シティポップに。',
  'pattern.shuffle.name': 'シャッフル',
  'pattern.shuffle.hint': 'ハネた8分。ブルース/ロカビリーに。',
  'pattern.ballad.name': 'バラード・アルペジオ',
  'pattern.ballad.hint': '低音→内声→高音の順に爪弾く定番アルペジオ。',
  'pattern.threefinger.name': 'スリーフィンガー',
  'pattern.threefinger.hint': 'p-i-m-i の交互ピッキング。カントリー/フォーク。',
  'pattern.bossa.name': 'ボサノバ',
  'pattern.bossa.hint': 'シンコペーションの効いたブラジリアン・リズム。',
  'pattern.country.name': 'オルタネイトベース',
  'pattern.country.hint': '低音を交互に弾きながら和音を挟むカントリー奏法。',
  'pattern.chug.name': 'ブリッジミュート刻み',
  'pattern.chug.hint': '8分の刻み。パワーコード＋歪みで。',
  'pattern.waltz.name': 'ワルツ（3拍子）',
  'pattern.waltz.hint': '3/4拍子。ズン・チャッ・チャッ。',
  'pattern.slowarp.name': 'スローアルペジオ',
  'pattern.slowarp.hint': '1拍1音のゆったりした分散和音。',

  'demo.canon.title': 'カノン進行',
  'demo.canon.description': '定番中の定番。フォークストロークで。',
  'demo.ballad.title': 'バラード・アルペジオ',
  'demo.ballad.description': '指弾きのアルペジオ。夜に似合う響き。',
  'demo.komuro.title': '小室進行（16ビート）',
  'demo.komuro.description': 'Am-F-G-C。16分のカッティングで疾走感を出す。',
  'demo.blues12.title': 'ブルース12小節',
  'demo.blues12.description': 'A7-D7-E7 のスリーコード。シャッフルで。',
  'demo.bossa.title': 'ボサノバ',
  'demo.bossa.description': 'ナイロン弦でシンコペーション。',
  'demo.rock8.title': '8ビート・ロック',
  'demo.rock8.description': 'G-D-Em-C。ブリティッシュな歪みで。',
  'demo.chug.title': 'パワーコード刻み',
  'demo.chug.description': 'ブリッジミュートの効いたリフ。ハイゲインで。',
  'demo.country.title': 'カントリー（オルタネイトベース）',
  'demo.country.description': '低音を刻みながらコードを挟む定番の伴奏。',
  'demo.waltz.title': 'ワルツ（3拍子）',
  'demo.waltz.description': 'ズン・チャッ・チャッの3拍子。',
  'demo.ambient.title': 'アンビエント',
  'demo.ambient.description': '広いディレイとリバーブ。コードを置くだけで空間になる。',
  'demo.funk9.title': 'ファンク・カッティング',
  'demo.funk9.description': 'Em9-A9 の2コード。オートワウと合わせても。',
  'demo.jazz251.title': 'ジャズ II-V-I',
  'demo.jazz251.description': 'Dm7-G7-CM7。アーチトップの丸いトーンで。',
  'demo.surf.title': 'サーフ・インスト',
  'demo.surf.description': 'トレモロとスプリングリバーブの60年代サウンド。',
  'demo.uke.title': 'ウクレレ・ハワイアン',
  'demo.uke.description': '4弦ウクレレの軽やかなストローク。',
  'demo.bassline.title': 'ベースライン',
  'demo.bassline.description': 'エレキベースで8分のルート弾き。',

  'chordpad.key': 'キー',
  'chordpad.major': 'メジャー',
  'chordpad.minor': 'マイナー',
  'chordpad.free': '任意',
  'chordpad.majorSuffix': '（メジャー）',
  'chordpad.play': '鳴らす',

  'quality.maj.name': 'メジャー',
  'quality.min.name': 'マイナー',
  'quality.dom7.name': 'セブンス',
  'quality.min7.name': 'マイナーセブンス',
  'quality.maj7.name': 'メジャーセブンス',
  'quality.min6.name': 'マイナーシックス',
  'quality.maj6.name': 'シックス',
  'quality.sus4.name': 'サスフォー',
  'quality.sus2.name': 'サスツー',
  'quality.7sus4.name': 'セブンスサスフォー',
  'quality.add9.name': 'アドナイン',
  'quality.dom9.name': 'ナインス',
  'quality.min9.name': 'マイナーナインス',
  'quality.maj9.name': 'メジャーナインス',
  'quality.min7b5.name': 'ハーフディミニッシュ',
  'quality.dim7.name': 'ディミニッシュセブンス',
  'quality.aug.name': 'オーギュメント',
  'quality.dom7b9.name': 'セブンスフラットナイン',
  'quality.dom7s9.name': 'セブンスシャープナイン',
  'quality.power.name': 'パワーコード',

  'fretboard.strumHint': 'ここを左右になぞってストローク',
};

const en: typeof ja = {
  'help.button': '?',
  'lang.toggle': 'EN',
  'brand.subtitle': 'Physically Modeled Guitar',
  'preset.ariaLabel': 'Tone preset',
  'panic.label': 'Stop All',
  'panic.title': 'Stop all sound (Esc)',
  'panic.ariaLabel': 'Stop all sound',

  'tab.chord': 'Chord',
  'tab.backing': 'Backing',
  'tab.string': 'String',
  'tab.amp': 'Amp',
  'tab.space': 'Effects',
  'tab.play': 'Play',
  'tab.rec': 'Record',
  'tab.demo': 'Demo',

  'palm.label': 'Palm Mute',
  'palm.title': 'Can also be toggled with the M key',
  'strum.down': '▼ Down',
  'strum.up': '▲ Up',
  'mute.label': 'Mute',

  'status.ready': 'Ready',
  'status.tapToStart': 'Touch the fretboard to start',
  'status.capo': 'Capo {n}',
  'status.midi': 'MIDI: {devices}',

  'chord.hint': 'Tap a pad for a downstroke, swipe up for an upstroke. The fingering for the selected chord shows on the fretboard.',
  'ctl.strumSpeed.label': 'Strum Speed',
  'unit.msPerString': 'ms/string',
  'ctl.strumSpeed.hint': 'The interval between adjacent strings. Higher values give a slower "jangle."',

  'panel.rhythmPattern.title': 'Rhythm Pattern',
  'ctl.pattern.label': 'Pattern',
  'ctl.tempo.label': 'Tempo',
  'ctl.humanize.label': 'Humanize',
  'ctl.humanize.hint': 'Adds a slight wobble to timing and strength.',
  'panel.progression.title': 'Chord Progression',
  'panel.progression.hint': 'One cell = one bar. Tap to delete.',
  'progression.empty': 'No chords yet. Add one with the button below.',
  'slot.title': 'Tap to delete',
  'action.addSelected': 'Add Selected Chord',
  'status.selectChordFirst': 'Select a chord in the "Chord" tab first',
  'action.clearAll': 'Clear All',
  'panel.backingPlayback.title': 'Backing Playback',
  'backing.stop': '■ Stop',
  'backing.play': '▶ Play Backing',
  'action.exportBackingWav': 'Export as WAV',
  'ctl.loopBacking.label': 'Loop Playback',

  'ctl.pickPos.label': 'Pick Position',
  'pickPos.bridge': 'Near Bridge',
  'pickPos.neck': 'Near Neck',
  'pickPos.standard': 'Standard',
  'ctl.pickPos.hint': 'Nearer the bridge is harder, nearer the neck is rounder.',
  'ctl.pickHard.label': 'Pick Hardness',
  'pickHard.finger': 'Finger',
  'pickHard.hard': 'Hard Pick',
  'pickHard.normal': 'Medium Pick',
  'ctl.brightness.label': 'String Brightness',
  'ctl.brightness.hint': 'High-end extension. Newer strings ring brighter.',
  'ctl.sustain.label': 'Sustain',
  'ctl.stiffness.label': 'String Tension (Overtone Shift)',
  'ctl.stiffness.hint': 'Thicker strings shift overtones slightly higher — the source of that metallic character.',
  'ctl.coupling.label': 'Sympathetic Coupling',
  'ctl.coupling.hint': 'Other strings resonate faintly through the bridge.',
  'ctl.pickNoise.label': 'Pick Attack Noise',
  'ctl.fretNoise.label': 'Finger Slide Noise',
  'ctl.fretNoise.hint': 'The squeak heard when sliding.',
  'ctl.buzz.label': 'Buzz',
  'ctl.buzz.hint': 'A buzz that appears only when played hard.',
  'ctl.spread.label': 'Stereo Width',
  'panel.body.title': 'Body (Acoustic Resonance)',
  'panel.body.hint': 'The resonance of an acoustic body. Set to "None" for electric.',
  'ctl.bodyType.label': 'Type',
  'ctl.bodyMix.label': 'Body Resonance Amount',

  'body.none.label': 'None (Electric)',
  'body.dread.label': 'Dreadnought',
  'body.parlor.label': 'Parlor (Small Body)',
  'body.nylon.label': 'Classical (Nylon)',
  'body.archtop.label': 'Archtop',
  'body.resonator.label': 'Resonator (Metal)',

  'ctl.amp.label': 'Amp',
  'ctl.amp.hint': 'For acoustic tones, use "No Amp."',
  'ctl.driveType.label': 'Drive',
  'drive.off': 'None',
  'drive.boost': 'Boost',
  'drive.overdrive': 'Overdrive',
  'drive.distortion': 'Distortion',
  'drive.fuzz': 'Fuzz',
  'ctl.driveAmount.label': 'Drive Amount',
  'ctl.compress.label': 'Compressor',
  'ctl.compress.hint': 'Evens out the notes and extends sustain. Effective for cutting.',
  'panel.eq.title': 'Equalizer',
  'eq.bass': 'Low',
  'eq.mid': 'Mid',
  'eq.treble': 'High',
  'eq.presence': 'Presence',
  'ctl.cabinet.label': 'Cabinet',
  'cab.off.label': 'None (Line Out)',
  'ctl.cabinet.hint': 'The character of a speaker cabinet. Always route distortion through one for a natural sound.',

  'amp.off.label': 'No Amp (Raw Tone)',
  'amp.clean.label': 'Clean',
  'amp.tweed.label': 'Tweed',
  'amp.british.label': 'British',
  'amp.modern.label': 'Modern High-Gain',
  'amp.bassamp.label': 'Bass Amp',

  'cab.combo1x12.label': '1x12 Combo',
  'cab.twin2x12.label': '2x12 Twin',
  'cab.stack4x12.label': '4x12 Stack',
  'cab.bass8x10.label': '8x10 Bass Cab',

  'panel.mod.title': 'Modulation',
  'ctl.modType.label': 'Type',
  'mod.off': 'None',
  // --- Extra pedals (shared with the drum and bass apps; these stack) ---
  'panel.pedals.title': 'Pedals (Stackable)',
  'panel.pedals.hint': 'Separate from the modulation above — run as many at once as you like',
  'ctl.flanger.label': 'Flanger',
  'ctl.flanger.hint': 'That sharp jet-plane sweep',
  'ctl.flangerRate.label': 'Flanger Rate',
  'ctl.flangerDepth.label': 'Flanger Depth',
  'ctl.flangerFeedback.label': 'Flanger Feedback',
  'ctl.flangerMix.label': 'Flanger Mix',
  'ctl.filterMode.label': 'Filter',
  'ctl.filterMode.hint': 'Separate from the wah — carve or sweep the frequency range',
  'filter.lowpass': 'Low-Pass',
  'filter.highpass': 'High-Pass',
  'filter.bandpass': 'Band-Pass',
  'ctl.filterFreq.label': 'Cutoff',
  'ctl.filterQ.label': 'Resonance',
  'ctl.filterQ.hint': 'Emphasises the cutoff region for more character',
  'ctl.filterLfoRate.label': 'Sweep Rate',
  'ctl.filterLfoDepth.label': 'Sweep Depth',
  'ctl.filterLfoDepth.hint': '0 holds still; raise it for a wah-like sweep',
  'ctl.crushBits.label': 'Bit Crusher',
  'ctl.crushBits.hint': 'Drops bit depth for a coarse, retro texture',
  'ctl.crushMix.label': 'Crush Mix',
  'ctl.ring.label': 'Ring Modulator',
  'ctl.ring.hint': 'Multiplies by a sine wave for a clangorous, atonal edge',
  'ctl.ringFreq.label': 'Ring Frequency',
  'ctl.ringMix.label': 'Ring Mix',
  'ctl.autopanDepth.label': 'Auto-Pan',
  'ctl.autopanDepth.hint': 'Sweeps the sound left and right. 0 turns it off',
  'ctl.autopanRate.label': 'Auto-Pan Rate',
  'ctl.width.label': 'Stereo Width',
  'ctl.width.hint': '100% leaves it alone; below narrows to mono, above spreads it out',
  'width.mono': 'Mono',

  'mod.chorus': 'Chorus',
  'mod.vibrato': 'Vibrato',
  'mod.phaser': 'Phaser',
  'mod.tremolo': 'Tremolo',
  'mod.wah': 'Auto-Wah',
  'ctl.modRate.label': 'Rate',
  'ctl.modDepth.label': 'Depth',
  'panel.delay.title': 'Delay',
  'ctl.delayMix.label': 'Delay Amount',
  'delay.off': 'Off',
  'ctl.delayTime.label': 'Delay Time',
  'ctl.delayFeedback.label': 'Feedback',
  'delay.quarter': 'Quarter',
  'delay.dottedEighth': 'Dotted 8th',
  'delay.eighth': 'Eighth',
  'delay.sixteenth': '16th',
  'delay.syncHint': 'Sync to tempo ({bpm} BPM):',
  'panel.reverb.title': 'Reverb',
  'ctl.reverbType.label': 'Type',
  'reverb.off': 'None',
  'ctl.reverbAmount.label': 'Reverb Amount',
  'ctl.masterVolume.label': 'Master Volume',
  'ctl.outputTrim.label': 'Output Trim',
  'ctl.outputTrim.hint': 'Corrects for the volume differences between tones. Set automatically when you pick a preset.',

  'room.room.label': 'Room',
  'room.plate.label': 'Plate',
  'room.spring.label': 'Spring',
  'room.hall.label': 'Hall',

  'panel.tuning.title': 'Tuning',
  'ctl.tuningSelect.label': 'Tuning',
  'ctl.capo.label': 'Capo',
  'capo.none': 'None',
  'capo.fret': 'Fret {v}',
  'ctl.a4.label': 'Reference Pitch',
  'tuner.stringLabel': 'String {n} {note}',
  'tuner.hint': 'Tap to sound the reference pitch (tune by ear):',
  'panel.boardDisplay.title': 'Fretboard Display',
  'ctl.fretCount.label': 'Frets Shown',
  'fretCount.value': '{v} frets',
  'ctl.labelMode.label': 'Note Name Display',
  'labelMode.off': 'Off',
  'labelMode.note': 'Note Name',
  'labelMode.degree': 'Degree',
  'ctl.labelMode.hint': '"Degree" shows each note\'s role relative to the root of the selected chord.',
  'panel.metronome.title': 'Metronome',
  'metro.stop': '■ Stop',
  'metro.start': '▶ Start',
  'panel.input.title': 'Input',
  'ctl.velCurve.label': 'Velocity Curve',
  'velCurve.light': 'Light',
  'velCurve.heavy': 'Heavy',
  'velCurve.standard': 'Standard',
  'midi.reconnect': 'Rescan MIDI',
  'midi.connect': 'Use MIDI Keyboard',
  'midi.hint': 'MIDI notes are automatically assigned to string and fret.',
  'midi.unsupported': 'This browser does not support Web MIDI.',
  'keyboard.hint': 'Keyboard: Space = down-strum / Shift+Space = up-strum / 1-6 = each string / Z-M, Q-P = notes / M = palm mute / Esc = stop all',

  'record.stop': '■ Stop Recording',
  'record.start': '● Start Recording',
  'record.play': '▶ Play',
  'record.clear': 'Clear',
  'record.empty': 'Recording captures the performance itself (which string, which fret, how hard) so you can change the tone and export it later.',
  'record.count': '{count} events / {time}',
  'panel.export.title': 'Export',
  'export.wav': 'Export as WAV',
  'export.midi': 'Export as MIDI',
  'export.hint': 'WAV is synthesized offline with the current tone (faster than real time). MIDI resolves each string/fret to its actual pitch.',

  'demo.hint': 'Automatically performs from a chord progression and rhythm. The tone preset also switches when you play it.',
  'demo.stop': '■ Stop Playback',

  'status.audioError': 'Could not start audio: {err}',
  'status.midiUnavailable': 'Could not use the MIDI device',
  'status.allStopped': 'Stopped all sound',
  'status.noRecording': 'No recording',
  'flash.recordingPlayback': 'Recording playback',
  'status.emptyProgression': 'The chord progression is empty',
  'flash.backing': 'Backing',
  'status.nothingToExportLong': 'There is nothing to export (record something or play a demo first)',
  'status.exporting': 'Exporting…',
  'status.wavExported': 'WAV exported',
  'status.exportFailed': 'Export failed: {err}',
  'status.nothingToExport': 'There is nothing to export',
  'status.midiExported': 'MIDI exported',
  'status.playing': 'Playing: {label}',
  'status.pcOctave': 'Keyboard: C{n}',

  'help.title': 'How to Play Takibi Guitar',
  'help.play.heading': 'Play',
  'help.play.tap': '<b>Tap the fretboard</b> … plays that string and fret.',
  'help.play.bendSlide': '<b>Drag up/down while holding</b> … bend. <b>Left/right</b> … slide.',
  'help.play.vibrato': '<b>Wiggle your finger up and down slightly while holding</b> … uses the same bend mechanism to add vibrato.',
  'help.play.strumBar': '<b>Drag left/right on the strip below the fretboard</b> … strum.',
  'help.play.chordPad': '<b>Chord tab pads</b> … tap for a downstroke, swipe up for an upstroke.',
  'help.keyboard.heading': 'Keyboard',
  'help.keyboard.space': '<b>Space</b> … downstroke (<b>Shift+Space</b> for up)',
  'help.keyboard.digits': '<b>1-6</b> … play that string alone',
  'help.keyboard.notes': '<b>Z-M / Q-P</b> … notes (auto-assigned to string and fret)',
  'help.keyboard.misc': '<b>↑↓</b> … change octave, <b>M</b> … palm mute, <b>Esc</b> … stop all',
  'help.tone.heading': 'Tone Shaping',
  'help.tone.synthesis': 'No sampled audio is used at all — string vibration is computed in real time.',
  'help.tone.tabs': 'Use the "String" tab for pick position and brightness, "Amp" for drive and EQ, and "Space" for modulation, delay, and reverb.',
  'help.create.heading': 'Create',
  'help.create.backing': 'Set a chord progression and rhythm in the "Backing" tab to auto-play an accompaniment.',
  'help.create.record': 'Use the "Record" tab to capture a performance and export it as WAV / MIDI.',
  'help.note': 'Everything runs in the browser. No audio downloads, no network access, no purchases.',
  'help.close': 'Close',

  'preset.steel.name': 'Acoustic (Steel String)',
  'preset.steel.description': 'The classic dreadnought. A staple singer-songwriter tone.',
  'preset.strum.name': 'Strum (Jangly)',
  'preset.strum.description': 'A hard pick attack for cutting strumming.',
  'preset.fingerpick.name': 'Fingerpicking',
  'preset.fingerpick.description': 'A soft fingerstyle attack, great for arpeggios.',
  'preset.nylon.name': 'Classical Guitar (Nylon)',
  'preset.nylon.description': 'Soft, round nylon strings. Great for bossa nova and classical.',
  'preset.parlor.name': 'Parlor (Small Body)',
  'preset.parlor.description': 'The light, airy ring of a small body. Great for blues and ragtime.',
  'preset.resonator.name': 'Resonator (Slide)',
  'preset.resonator.description': 'A metal resonator plate for bottleneck playing. Pairs great with open G.',
  'preset.clean.name': 'Electric Clean',
  'preset.clean.description': 'A straightforward clean tone, great for chords and arpeggios alike.',
  'preset.funk.name': 'Funk Cutting',
  'preset.funk.description': 'Crisp, compressed cutting rhythm guitar.',
  'preset.jazz.name': 'Jazz Archtop',
  'preset.jazz.description': 'A thick, round front-pickup tone.',
  'preset.blues.name': 'Blues Crunch',
  'preset.blues.description': 'A lightly overdriven tube amp that reacts to your picking dynamics.',
  'preset.british.name': 'British Rock',
  'preset.british.description': 'Mid-forward rock \'n\' roll distortion.',
  'preset.metal.name': 'Modern High-Gain',
  'preset.metal.description': 'Scooped-mid heavy distortion for tight palm-muted riffing.',
  'preset.fuzz.name': 'Fuzz Lead',
  'preset.fuzz.description': 'A raw fuzz tone that shines on single-note leads.',
  'preset.surf.name': 'Surf (Spring + Tremolo)',
  'preset.surf.description': 'Wobbly tremolo and spring reverb — that 60s instrumental sound.',
  'preset.ambient.name': 'Ambient (Delay)',
  'preset.ambient.description': 'Deep delay and hall reverb — a single chord fills the space.',
  'preset.chorus.name': 'Chorus Clean',
  'preset.chorus.description': 'A shimmering 80s-style chorus, great for arpeggios.',
  'preset.wah.name': 'Auto-Wah Funk',
  'preset.wah.description': 'A cyclic wah, great paired with cutting rhythm.',
  'preset.bass.name': 'Electric Bass',
  'preset.bass.description': 'A 4-string bass. The tuning switches to bass automatically.',
  'preset.ukulele.name': 'Ukulele',
  'preset.ukulele.description': 'A 4-string ukulele. The tuning switches automatically.',

  'tuning.standard.name': 'Standard (EADGBE)',
  'tuning.standard.hint': 'The common 6-string guitar tuning.',
  'tuning.dropd.name': 'Drop D (DADGBE)',
  'tuning.dropd.hint': 'The low string tuned down a whole step, so power chords can be fretted with one finger.',
  'tuning.halfdown.name': 'Half-Step Down (E♭A♭D♭G♭B♭E♭)',
  'tuning.halfdown.hint': 'All strings down a half step. A thicker, looser tone.',
  'tuning.wholedown.name': 'Whole-Step Down (DGCFAD)',
  'tuning.wholedown.hint': 'All strings down a whole step, great for heavy riffs.',
  'tuning.dropc.name': 'Drop C (CGCFAD)',
  'tuning.dropc.hint': 'For low, heavy riffs. A staple in loud styles.',
  'tuning.dadgad.name': 'DADGAD',
  'tuning.dadgad.hint': 'A Celtic/acoustic alternate tuning with a floating quality.',
  'tuning.openg.name': 'Open G (DGDGBD)',
  'tuning.openg.hint': 'Open strings ring a G major chord. Great for slide and blues.',
  'tuning.opend.name': 'Open D (DADF♯AD)',
  'tuning.opend.hint': 'Open strings ring a D major chord. Great for bottleneck.',
  'tuning.opene.name': 'Open E (EBEG♯BE)',
  'tuning.opene.hint': 'Open strings ring an E major chord. Great for raw blues.',
  'tuning.bass.name': '4-String Bass (EADG)',
  'tuning.bass.hint': 'Electric bass tuning. Pair it with a bass tone.',
  'tuning.ukulele.name': 'Ukulele (GCEA)',
  'tuning.ukulele.hint': 'High-G soprano ukulele tuning. Use with a nylon tone.',

  'pattern.whole.name': 'Whole Strum',
  'pattern.whole.hint': 'One strum per bar. Good for checking a chord\'s ring.',
  'pattern.eighth.name': '8th-Note Strum',
  'pattern.eighth.hint': 'All-down 8th notes. A rock/pop staple.',
  'pattern.folk.name': 'Folk (D DU UDU)',
  'pattern.folk.hint': 'The classic singer-songwriter strum.',
  'pattern.sixteen.name': '16th-Note Cutting',
  'pattern.sixteen.hint': '16th notes mixed with muted picking. Great for funk/city pop.',
  'pattern.shuffle.name': 'Shuffle',
  'pattern.shuffle.hint': 'Swung 8th notes. Great for blues/rockabilly.',
  'pattern.ballad.name': 'Ballad Arpeggio',
  'pattern.ballad.hint': 'A classic arpeggio moving low → inner → high.',
  'pattern.threefinger.name': 'Three-Finger',
  'pattern.threefinger.hint': 'Alternating p-i-m-i picking. Country/folk.',
  'pattern.bossa.name': 'Bossa Nova',
  'pattern.bossa.hint': 'A syncopated Brazilian rhythm.',
  'pattern.country.name': 'Alternating Bass',
  'pattern.country.hint': 'A country style alternating bass notes with chord hits.',
  'pattern.chug.name': 'Palm-Muted Chugging',
  'pattern.chug.hint': '8th-note chugging. Great with power chords and distortion.',
  'pattern.waltz.name': 'Waltz (3/4)',
  'pattern.waltz.hint': '3/4 time. Boom-chick-chick.',
  'pattern.slowarp.name': 'Slow Arpeggio',
  'pattern.slowarp.hint': 'A relaxed broken chord, one note per beat.',

  'demo.canon.title': 'Canon Progression',
  'demo.canon.description': 'The classic of classics, played with a folk strum.',
  'demo.ballad.title': 'Ballad Arpeggio',
  'demo.ballad.description': 'A fingerstyle arpeggio, a sound made for nighttime.',
  'demo.komuro.title': 'Komuro Progression (16th-Note)',
  'demo.komuro.description': 'Am-F-G-C. 16th-note cutting for a driving feel.',
  'demo.blues12.title': '12-Bar Blues',
  'demo.blues12.description': 'The A7-D7-E7 three-chord form, played as a shuffle.',
  'demo.bossa.title': 'Bossa Nova',
  'demo.bossa.description': 'Syncopation on nylon strings.',
  'demo.rock8.title': '8th-Note Rock',
  'demo.rock8.description': 'G-D-Em-C, with a British-style distortion.',
  'demo.chug.title': 'Power Chord Chugging',
  'demo.chug.description': 'A palm-muted riff with high gain.',
  'demo.country.title': 'Country (Alternating Bass)',
  'demo.country.description': 'A classic accompaniment interleaving bass notes and chords.',
  'demo.waltz.title': 'Waltz (3/4)',
  'demo.waltz.description': 'A boom-chick-chick 3/4 time feel.',
  'demo.ambient.title': 'Ambient',
  'demo.ambient.description': 'Wide delay and reverb — a single chord becomes a space.',
  'demo.funk9.title': 'Funk Cutting',
  'demo.funk9.description': 'A two-chord Em9-A9 vamp, pairs well with auto-wah.',
  'demo.jazz251.title': 'Jazz II-V-I',
  'demo.jazz251.description': 'Dm7-G7-CM7, with a round archtop tone.',
  'demo.surf.title': 'Surf Instrumental',
  'demo.surf.description': 'Tremolo and spring reverb — that 60s sound.',
  'demo.uke.title': 'Ukulele Hawaiian',
  'demo.uke.description': 'A light, breezy strum on a 4-string ukulele.',
  'demo.bassline.title': 'Bass Line',
  'demo.bassline.description': 'Root-note 8th notes on electric bass.',

  'chordpad.key': 'Key',
  'chordpad.major': 'Major',
  'chordpad.minor': 'Minor',
  'chordpad.free': 'Free',
  'chordpad.majorSuffix': '(Major)',
  'chordpad.play': 'Play',

  'quality.maj.name': 'Major',
  'quality.min.name': 'Minor',
  'quality.dom7.name': 'Dominant 7th',
  'quality.min7.name': 'Minor 7th',
  'quality.maj7.name': 'Major 7th',
  'quality.min6.name': 'Minor 6th',
  'quality.maj6.name': '6th',
  'quality.sus4.name': 'Sus4',
  'quality.sus2.name': 'Sus2',
  'quality.7sus4.name': '7sus4',
  'quality.add9.name': 'Add9',
  'quality.dom9.name': '9th',
  'quality.min9.name': 'Minor 9th',
  'quality.maj9.name': 'Major 9th',
  'quality.min7b5.name': 'Half-Diminished',
  'quality.dim7.name': 'Diminished 7th',
  'quality.aug.name': 'Augmented',
  'quality.dom7b9.name': '7♭9',
  'quality.dom7s9.name': '7♯9',
  'quality.power.name': 'Power Chord',

  'fretboard.strumHint': 'Drag left and right here to strum',
};

registerStrings(ja, en);
