import { registerStrings } from './i18n';

const ja = {
  'lang.toggle': 'JP',
  'loading': '読み込み中…',
  'boot.error': 'お使いのブラウザは AudioWorklet に対応していないため起動できません。<br>最新の Chrome / Edge / Firefox / Safari をお使いください。',

  'transport.play.title': '再生 / 停止（スペースキー）',
  'transport.stop.title': '停止＆全音消音',
  'transport.rec.title': 'リアルタイム録音（WAV）',
  'mode.pattern': 'パターン',
  'mode.song': 'ソング',
  'tap.title': 'タップテンポ',
  'metro.title': 'メトロノーム',
  'action.exportWav': 'WAV書出',
  'action.exportMidi': 'MIDI書出',
  'action.save': '保存',
  'action.load': '読込',
  'action.help': '？',

  'tab.synth': 'シンセ',
  'tab.master': 'マスターFX',
  'tab.song': 'ソング構成',

  'addTrack.title': 'トラックを追加：音色を選択',

  'toast.tempo': 'テンポ: {bpm} BPM',
  'toast.recordSaved': '録音を WAV で保存しました',
  'toast.noRecordData': '録音データがありません',
  'toast.recording': '録音中… もう一度押すと停止して WAV を保存します',
  'toast.recordUnavailable': 'この環境では録音を開始できませんでした',

  'export.info': 'オフラインレンダリングで高品質な WAV（24bit）を書き出します。リアルタイム録音と違い音切れがなく、実時間より短時間で完了します。',
  'export.bars': '小節数',
  'export.repeat': '繰り返し',
  'export.sampleRate': 'サンプルレート',
  'export.rendering': 'レンダリング中…',
  'export.done': '完了しました',
  'export.failed': '失敗しました: {err}',
  'export.go': '書き出す',
  'export.modalTitle': 'WAV 書き出し',
  'toast.wavExported': 'WAV を書き出しました',
  'toast.midiExported': 'MIDI ファイルを書き出しました',
  'toast.midiExportFailed': 'MIDI 書き出しに失敗しました: {err}',
  'toast.songSaved': '曲データを保存しました',
  'toast.songLoaded': '曲データを読み込みました',
  'toast.loadFailed': '読み込みに失敗しました: {err}',

  'status.midiConnected': 'MIDI: {names}',
  'status.midiDisconnected': 'MIDI: 未接続',
  'status.keyboardBase': 'キーボード基準: C{oct}（← →で変更）',
  'status.hints': 'Space: 再生/停止 ・ Ctrl+Z: 元に戻す ・ Alt+クリック: ノート削除',

  'help.basics.heading': '基本操作',
  'help.basics.play': '<b>演奏</b>：画面下の鍵盤、PCキーボード（Z S X D C… / Q 2 W 3 E…）、MIDIキーボード。',
  'help.basics.octave': '<b>オクターブ</b>：← → キー、または OCT ボタン。',
  'help.basics.input': '<b>打ち込み</b>：ピアノロールをクリックでノート追加。右端をドラッグで長さ変更、ドラッグで移動、Alt+クリックまたは右クリックで削除。',
  'help.basics.velocity': '<b>ベロシティ</b>：ピアノロール下部のレーンを上下ドラッグ。',
  'help.basics.pattern': '<b>パターン</b>：A〜D の 4 スロットを切り替えて別フレーズを作れます。',
  'help.basics.song': '<b>ソング</b>：「ソング構成」タブでシーンを並べ、トランスポートを「ソング」に切り替えて再生。',
  'help.tone.heading': '音づくり',
  'help.tone.osc': '<b>OSC</b>：波形・オクターブ・デチューン。Super Saw は 7 基のノコギリ波を重ねた厚い音。',
  'help.tone.filter': '<b>フィルター (FILTER)</b>：Ladder は独特の粘りがあるアナログ風、Clean SVF は素直な特性。',
  'help.tone.lfo': '<b>LFO</b>：テンポ同期に切り替えると BPM に追従します。',
  'help.tone.save': '<b>音色保存</b>：ブラウザ内に保存され、次回起動時も残ります。',
  'help.analyzer.heading': 'アナライザー',
  'help.analyzer.top': '画面最上部にマスター出力を常時表示します。左のラベルをクリックすると「波形＋スペクトラム → スペクトラム → 波形」の順に切り替わります（選択は記憶されます）。',
  'help.analyzer.meter': '右側は L / R のピークメーター。白い線はピークホールド、数値は dBFS です。0.0 に近づくと赤くなるので、書き出し前の音量確認に使えます。',
  'help.export.heading': '書き出し',
  'help.export.wav': '<b>WAV書出</b>：オフラインレンダリングで高音質・音切れなしの WAV を生成。',
  'help.export.midi': '<b>MIDI書出</b>：他の DAW に読み込める標準MIDIファイル。',
  'help.export.save': '<b>保存 / 読込</b>：曲データ（JSON）。作業内容はブラウザにも自動保存されます。',
  'help.license.heading': 'ライセンス',
  'help.license.text': '音はすべてコード生成（サンプル音源不使用）。作った曲の権利は制作者であるあなたのものです。商用利用も自由です。',
  'help.title': '使い方',
  'help.reloadDemo': 'デモ曲を読み込み直す',
  'confirm.reloadDemo': '現在の曲は失われます。よろしいですか？',

  'song.demos.title': 'デモ曲',
  'song.demos.hint': 'クリックすると現在の曲と入れ替わります。',
  'confirm.loadDemo': '現在の曲は失われます。「{title}」を読み込みますか？',
  'flash.demoLoaded': '「{title}」を読み込みました',
  'demo.sunrise.title': '陽だまりのグルーヴ',
  'demo.sunrise.subtitle': 'アップテンポなハウス',
  'demo.midnight.title': '真夜中のドリフト',
  'demo.midnight.subtitle': '静かなアンビエント',
  'demo.neon.title': 'ネオン・ランナー',
  'demo.neon.subtitle': '80年代風シンセウェイブ',
  'demo.pixel.title': 'ピクセル・ラッシュ',
  'demo.pixel.subtitle': '軽快なチップチューン',

  'demo.tenmon-01.title': '混沌の序章',
  'demo.tenmon-01.subtitle': 'アルバム「天問」#1 — モーダル・スウィングのジャズ・コンボ',
  'demo.tenmon-02.title': '誰が空を創ったのか',
  'demo.tenmon-02.subtitle': 'アルバム「天問」#2 — ミディアム・スウィングの12小節ブルース',
  'demo.tenmon-03.title': '星の回廊',
  'demo.tenmon-03.subtitle': 'アルバム「天問」#3 — 3拍子のジャズ・ワルツ',
  'demo.tenmon-04.title': '地の果てへ',
  'demo.tenmon-04.subtitle': 'アルバム「天問」#4 — ボサノヴァのジャズ・コンボ',
  'demo.tenmon-05.title': '問いかける月',
  'demo.tenmon-05.subtitle': 'アルバム「天問」#5 — スロー・バラード',
  'demo.tenmon-06.title': '龍の眠り',
  'demo.tenmon-06.subtitle': 'アルバム「天問」#6 — ハードバップ',
  'demo.tenmon-07.title': '見えない橋',
  'demo.tenmon-07.subtitle': 'アルバム「天問」#7 — アフロキューバン／ラテン・ジャズ',
  'demo.tenmon-08.title': '光と影のあいだ',
  'demo.tenmon-08.subtitle': 'アルバム「天問」#8 — 2コード・ヴァンプのモーダル・ジャズ',
  'demo.tenmon-09.title': '天の川を渡る',
  'demo.tenmon-09.subtitle': 'アルバム「天問」#9 — アップテンポ・スウィング',
  'demo.tenmon-10.title': '終わりなき問い',
  'demo.tenmon-10.subtitle': 'アルバム「天問」#10 — ルバート気味のエピローグ・バラード',

  'modal.close': '閉じる',

  'mixer.track': 'トラック',
  'mixer.addTrack': '＋ 追加',
  'mixer.mute.title': 'ミュート',
  'mixer.solo.title': 'ソロ',
  'mixer.delete.title': 'トラックを削除',
  'mixer.delete.confirm': 'トラック「{name}」を削除しますか？',

  'division.2beat': '2拍',
  'division.1beat': '1拍',
  'division.dotted8': '付点8分',
  'division.8': '8分',
  'division.triplet8': '3連8分',
  'division.16': '16分',
  'ctl.delayNote': '音符',

  'song.intro': 'シーンを縦に並べて曲の構成を作ります。各セルはトラックが鳴らすパターン（A〜D）です。「ソング」モードで再生すると上から順に演奏されます。',
  'song.sceneHeader': 'シーン',
  'song.barsHeader': '小節',
  'song.emptySuffix': '（空）',
  'song.duplicate': '複製',
  'song.moveUp': '↑',
  'song.moveDown': '↓',
  'song.delete': '×',
  'toast.sceneMinimum': 'シーンは最低1つ必要です',
  'song.addScene': '＋ シーンを追加',
  'song.total': '全 {bars} 小節 / 約 {min}分{sec}秒（{bpm} BPM）',

  'ctl.waveform': '波形',
  'ctl.subWaveform': 'SUB波形',
  'ctl.filterModel': 'モデル',
  'ctl.filterType': 'タイプ',
  'ctl.slope': 'スロープ',
  'ctl.sync': '同期',
  'ctl.modTarget': '変調先',
  'ctl.voiceMode': 'モード',
  'ctl.arpMode': 'モード',
  'ctl.drumVoice': '音色',
  'filterModel.ladder': 'Ladder (太い)',
  'unit.perBeat': '/拍',
  'drum.preview': '▶ 試聴',
  'lfoDiv.bar1': '1小節',
  'lfoDiv.beat2': '2拍',
  'lfoDiv.beat1': '1拍',
  'lfoDiv.beat0_5': '1/2拍',
  'lfoDiv.beat0_25': '1/4拍',
  'lfoDiv.triplet': '3連符',

  'analyzer.switchDisplay': '表示を切り替え',

  'roll.slotTitle': 'パターン {letter}',
  'roll.lengthOption': '{steps} steps ({bars}小節)',
  'roll.length': '長さ',
  'notelen.16': '16分',
  'notelen.8': '8分',
  'notelen.4': '4分',
  'notelen.2': '2分',
  'notelen.whole': '全音符',
  'roll.inputLength': '入力長',
  'roll.velocity': '強さ',
  'roll.copy': 'コピー',
  'roll.copy.title': 'このパターンをコピー',
  'roll.paste': '貼付',
  'roll.paste.title': 'コピーしたパターンを貼り付け',
  'roll.undo': '元に戻す',
  'roll.clear': 'クリア',
  'roll.clear.title': 'このパターンのノートを全消去',
  'roll.zoomOut.title': '縮小',
  'roll.zoomIn.title': '拡大',
  'toast.patternCopied': 'パターンをコピーしました',
  'toast.patternPasted': 'パターンを貼り付けました',

  'patch.searchPlaceholder': '音色を検索…',
  'patch.save': '＋ 音色を保存',
  'patch.namePrompt': '音色名を入力してください',
  'toast.patchSaved': '「{name}」を保存しました',
  'patch.empty': '該当する音色がありません',
  'patch.delete.title': '削除',
  'patch.delete.confirm': '「{name}」を削除しますか？',

  // カテゴリー名
  'category.BASS': 'ベース',
  'category.LEAD': 'リード',
  'category.PAD': 'パッド',
  'category.KEYS': 'キーボード',
  'category.PLUCK_BELL': 'プラック / ベル',
  'category.BRASS_STRINGS': 'ブラス / ストリングス',
  'category.SEQ_ARP': 'シーケンス / アルペジオ',
  'category.SFX': '効果音',
  'category.DRUM': 'ドラム',
  'category.MY_PATCH': 'マイ音色',

  // ファクトリー音色名
  'preset.bass_analog': 'アナログベース',
  'preset.bass_acid': 'アシッド303',
  'preset.bass_sub': 'ディープサブ',
  'preset.bass_reese': 'リースベース',
  'preset.bass_fm': 'FMベース',
  'preset.bass_pluck': 'プラックベース',
  'preset.bass_growl': 'グロウルベース',
  'preset.lead_super': 'スーパーソウリード',
  'preset.lead_saw': 'クラシックソウリード',
  'preset.lead_square': 'ホロウスクエア',
  'preset.lead_sync': 'シンクリード',
  'preset.lead_fm': 'FMリード',
  'preset.lead_flute': 'ソフトフルート',
  'preset.lead_chip': 'チップチューンリード',
  'preset.lead_whistle': 'サインホイッスル',
  'preset.pad_warm': 'ウォームパッド',
  'preset.pad_glass': 'グラスパッド',
  'preset.pad_choir': 'クワイア「アー」',
  'preset.pad_sweep': 'スイープパッド',
  'preset.pad_dark': 'ダークドローン',
  'preset.pad_shimmer': 'シマーエア',
  'preset.keys_ep': 'エレクトリックピアノ',
  'preset.keys_clav': 'クラビネット',
  'preset.keys_organ': 'ドローバーオルガン',
  'preset.keys_house': 'ハウスピアノ',
  'preset.keys_toy': 'トイボックス',
  'preset.pluck_synth': 'シンセプラック',
  'preset.pluck_koto': '琴',
  'preset.bell_glocken': 'グロッケンシュピール',
  'preset.bell_tubular': 'チューブラーベル',
  'preset.bell_metal': 'メタルリング',
  'preset.pluck_marimba': 'マリンバ',
  'preset.brass_synth': 'シンセブラス',
  'preset.brass_stab': 'ブラススタブ',
  'preset.strings_ensemble': 'ストリングスアンサンブル',
  'preset.strings_solo': 'ソロストリングス',
  'preset.seq_pulse': 'パルスシーケンス',
  'preset.seq_blip': 'ブリップアルペジオ',
  'preset.seq_dust': 'ダストモーション',
  'preset.sfx_riser': 'ライザー',
  'preset.sfx_laser': 'レーザーザップ',
  'preset.sfx_wind': 'ウィンドノイズ',
  'preset.sfx_impact': 'インパクトヒット',
  'preset.dr_kick': 'キック909',
  'preset.dr_kick808': 'キック808',
  'preset.dr_kick_tight': 'タイトキック',
  'preset.dr_snare': 'スネア',
  'preset.dr_snare_rim': 'リムショット',
  'preset.dr_clap': 'ハンドクラップ',
  'preset.dr_hat_closed': 'クローズハット',
  'preset.dr_hat_open': 'オープンハット',
  'preset.dr_tom_low': 'ロータム',
  'preset.dr_tom_mid': 'ミッドタム',
  'preset.dr_tom_high': 'ハイタム',
  'preset.dr_crash': 'クラッシュ',
  'preset.dr_ride': 'ライド',
  'preset.dr_cowbell': 'カウベル',
  'preset.dr_shaker': 'シェイカー',
  'preset.dr_clave': 'クラベ',

  // シンセパネル：モジュール見出し
  'module.mixerMod': 'ミキサー / モジュレーション',
  'module.filter': 'フィルター',
  'module.voice': 'ボイス',
  'module.fxSend': 'FXセンド',
  'module.arp': 'アルペジエーター',
  'module.drumVoiceGroup': 'ドラム音色',
  'module.ampEg': 'アンプEG',
  'module.filterEg': 'フィルターEG',

  // シンセパネル：ノブラベル
  'knob.octave': 'オクターブ',
  'knob.semi': '半音',
  'knob.detune': 'デチューン',
  'knob.level': 'レベル',
  'knob.pulseWidth': 'パルス幅',
  'knob.spread': '広がり',
  'knob.oscMix': 'OSCミックス',
  'knob.fm': 'FM',
  'knob.subLevel': 'サブレベル',
  'knob.subOctave': 'サブオクターブ',
  'knob.noiseLevel': 'ノイズレベル',
  'knob.cutoff': 'カットオフ',
  'knob.reso': 'レゾナンス',
  'knob.drive': 'ドライブ',
  'knob.egAmount': 'EG量',
  'knob.keyTrack': 'キートラック',
  'knob.velToCut': '速度→カット',
  'knob.attack': 'アタック',
  'knob.decay': 'ディケイ',
  'knob.sustain': 'サステイン',
  'knob.release': 'リリース',
  'knob.rate': 'レート',
  'knob.amount': '量',
  'knob.fadeIn': 'フェードイン',
  'knob.glide': 'グライド',
  'knob.bend': 'ベンド',
  'knob.velToAmp': '速度→音量',
  'knob.modAmount': 'MOD量',
  'knob.volume': 'ボリューム',
  'knob.pan': 'パン',
  'knob.chorus': 'コーラス',
  'knob.delay': 'ディレイ',
  'knob.reverb': 'リバーブ',
  'knob.octaves': 'オクターブ数',
  'knob.gate': 'ゲート',
  'knob.swing': 'スウィング',
  'knob.tune': 'チューン',
  'knob.tone': 'トーン',
  'knob.snap': 'スナップ',

  // シンセパネル：トグルラベル
  'toggle.ringMod': 'リングモッド',
  'toggle.oscSync': 'OSCシンク',
  'toggle.tempoSync': 'テンポシンク',
  'toggle.keyRetrig': 'キーリトリガー',
  'toggle.arpOn': 'アルペジエーターON',
  'toggle.latch': 'ラッチ',

  // シンセパネル：ドロップダウン選択肢
  'wave.saw': 'ソウ',
  'wave.square': 'スクエア',
  'wave.pulse': 'パルス',
  'wave.triangle': 'トライアングル',
  'wave.sine': 'サイン',
  'wave.superSaw': 'スーパーソウ',
  'wave.noise': 'ノイズ',
  'wave.sampleHold': 'S&H',
  'filterType.lowpass': 'ローパス',
  'filterType.highpass': 'ハイパス',
  'filterType.bandpass': 'バンドパス',
  'filterType.notch': 'ノッチ',
  'lfoTarget.off': 'オフ',
  'lfoTarget.pitch': 'ピッチ',
  'lfoTarget.osc2Pitch': 'OSC2ピッチ',
  'lfoTarget.pulseWidth': 'パルス幅',
  'lfoTarget.cutoff': 'カットオフ',
  'lfoTarget.amp': 'アンプ',
  'lfoTarget.pan': 'パン',
  'lfoTarget.fmAmount': 'FM量',
  'voiceMode.poly': 'ポリ',
  'voiceMode.mono': 'モノ',
  'voiceMode.legato': 'レガート',
  'modTarget.off': 'オフ',
  'modTarget.lfo1Depth': 'LFO1深さ',
  'modTarget.lfo2Depth': 'LFO2深さ',
  'modTarget.cutoff': 'カットオフ',
  'arpMode.up': 'アップ',
  'arpMode.down': 'ダウン',
  'arpMode.updown': 'アップ/ダウン',
  'arpMode.random': 'ランダム',
  'arpMode.order': '順番',
  'arpMode.chord': 'コード',
  'drumOpt.kickAnalog': 'キック（アナログ）',
  'drumOpt.kick808': 'キック（808ディープ）',
  'drumOpt.snare': 'スネア',
  'drumOpt.rim': 'リムショット',
  'drumOpt.clap': 'ハンドクラップ',
  'drumOpt.hatClosed': 'クローズハイハット',
  'drumOpt.hatOpen': 'オープンハイハット',
  'drumOpt.tomLow': 'ロータム',
  'drumOpt.tomMid': 'ミッドタム',
  'drumOpt.tomHigh': 'ハイタム',
  'drumOpt.crash': 'クラッシュシンバル',
  'drumOpt.ride': 'ライドシンバル',
  'drumOpt.cowbell': 'カウベル',
  'drumOpt.shaker': 'シェイカー',
  'drumOpt.clave': 'クラベ',
  'ctl.noiseType': 'ノイズ種類',
  'noiseType.white': 'ホワイト',
  'noiseType.pink': 'ピンク',
  'ctl.modWheel': 'MODホイール',

  // 音色ブラウザー：その他
  'patch.categoryAll': 'すべて',
  'patch.customSuffix': ' カスタム',
};

const en: typeof ja = {
  'lang.toggle': 'EN',
  'loading': 'Loading…',
  'boot.error': 'Your browser does not support AudioWorklet, so this app cannot start.<br>Please use a recent version of Chrome / Edge / Firefox / Safari.',

  'transport.play.title': 'Play / Stop (Space)',
  'transport.stop.title': 'Stop & Silence All',
  'transport.rec.title': 'Real-Time Recording (WAV)',
  'mode.pattern': 'Pattern',
  'mode.song': 'Song',
  'tap.title': 'Tap Tempo',
  'metro.title': 'Metronome',
  'action.exportWav': 'Export WAV',
  'action.exportMidi': 'Export MIDI',
  'action.save': 'Save',
  'action.load': 'Load',
  'action.help': '?',

  'tab.synth': 'Synth',
  'tab.master': 'Master FX',
  'tab.song': 'Song Structure',

  'addTrack.title': 'Add Track: Choose a Tone',

  'toast.tempo': 'Tempo: {bpm} BPM',
  'toast.recordSaved': 'Recording saved as WAV',
  'toast.noRecordData': 'There is no recorded data',
  'toast.recording': 'Recording… press again to stop and save the WAV',
  'toast.recordUnavailable': 'Recording could not be started in this environment',

  'export.info': 'Renders a high-quality 24-bit WAV offline. Unlike real-time recording there are no dropouts, and it finishes faster than real time.',
  'export.bars': 'Bars',
  'export.repeat': 'Repeats',
  'export.sampleRate': 'Sample Rate',
  'export.rendering': 'Rendering…',
  'export.done': 'Done',
  'export.failed': 'Failed: {err}',
  'export.go': 'Export',
  'export.modalTitle': 'Export WAV',
  'toast.wavExported': 'WAV exported',
  'toast.midiExported': 'MIDI file exported',
  'toast.midiExportFailed': 'MIDI export failed: {err}',
  'toast.songSaved': 'Song data saved',
  'toast.songLoaded': 'Song data loaded',
  'toast.loadFailed': 'Failed to load: {err}',

  'status.midiConnected': 'MIDI: {names}',
  'status.midiDisconnected': 'MIDI: Not connected',
  'status.keyboardBase': 'Keyboard base: C{oct} (change with ← →)',
  'status.hints': 'Space: Play/Stop ・ Ctrl+Z: Undo ・ Alt+click: Delete note',

  'help.basics.heading': 'Basic Controls',
  'help.basics.play': '<b>Play</b>: The on-screen keyboard, your computer keyboard (Z S X D C… / Q 2 W 3 E…), or a MIDI keyboard.',
  'help.basics.octave': '<b>Octave</b>: The ← → keys, or the OCT buttons.',
  'help.basics.input': '<b>Programming notes</b>: Click the piano roll to add a note. Drag the right edge to resize, drag to move, Alt+click or right-click to delete.',
  'help.basics.velocity': '<b>Velocity</b>: Drag up/down in the lane below the piano roll.',
  'help.basics.pattern': '<b>Patterns</b>: Switch between the 4 slots A–D to build different phrases.',
  'help.basics.song': '<b>Song</b>: Arrange scenes in the "Song Structure" tab, then switch the transport to "Song" to play them in order.',
  'help.tone.heading': 'Sound Design',
  'help.tone.osc': '<b>OSC</b>: Waveform, octave, and detune. Super Saw layers 7 sawtooth waves for a thick sound.',
  'help.tone.filter': '<b>FILTER</b>: Ladder has a distinctive, sticky analog character; Clean SVF is more neutral.',
  'help.tone.lfo': '<b>LFO</b>: Switch to tempo sync to follow the BPM.',
  'help.tone.save': '<b>Saving tones</b>: Saved in the browser and still there next time you open the app.',
  'help.analyzer.heading': 'Analyzer',
  'help.analyzer.top': 'The master output is always shown at the top of the screen. Click the label on the left to cycle through "waveform + spectrum → spectrum → waveform" (your choice is remembered).',
  'help.analyzer.meter': 'On the right are the L / R peak meters. The white line is the peak hold, and the number is in dBFS. It turns red as it approaches 0.0, which is handy for checking levels before exporting.',
  'help.export.heading': 'Export',
  'help.export.wav': '<b>Export WAV</b>: Renders a high-quality, dropout-free WAV offline.',
  'help.export.midi': '<b>Export MIDI</b>: A standard MIDI file you can load into other DAWs.',
  'help.export.save': '<b>Save / Load</b>: Song data (JSON). Your work is also auto-saved in the browser.',
  'help.license.heading': 'License',
  'help.license.text': 'All sound is generated by code (no sample audio used). The songs you make are yours — commercial use is fine too.',
  'help.title': 'How to Use',
  'help.reloadDemo': 'Reload Demo Song',
  'confirm.reloadDemo': 'The current song will be lost. Continue?',

  'song.demos.title': 'Demo Songs',
  'song.demos.hint': 'Click one to swap in for the current song.',
  'confirm.loadDemo': 'The current song will be lost. Load "{title}"?',
  'flash.demoLoaded': 'Loaded "{title}"',
  'demo.sunrise.title': 'Sunrise Groove',
  'demo.sunrise.subtitle': 'Upbeat house',
  'demo.midnight.title': 'Midnight Drift',
  'demo.midnight.subtitle': 'Calm ambient',
  'demo.neon.title': 'Neon Runner',
  'demo.neon.subtitle': '80s-style synthwave',
  'demo.pixel.title': 'Pixel Rush',
  'demo.pixel.subtitle': 'Bouncy chiptune',

  'demo.tenmon-01.title': 'Prologue: Chaos',
  'demo.tenmon-01.subtitle': 'Tenmon album #1 — modal-swing jazz combo',
  'demo.tenmon-02.title': 'Who Made the Sky?',
  'demo.tenmon-02.subtitle': 'Tenmon album #2 — medium-swing 12-bar blues',
  'demo.tenmon-03.title': 'Corridor of Stars',
  'demo.tenmon-03.subtitle': 'Tenmon album #3 — jazz waltz in 3/4',
  'demo.tenmon-04.title': 'To the Edge of the Earth',
  'demo.tenmon-04.subtitle': 'Tenmon album #4 — bossa nova jazz combo',
  'demo.tenmon-05.title': 'The Questioning Moon',
  'demo.tenmon-05.subtitle': 'Tenmon album #5 — slow ballad',
  'demo.tenmon-06.title': 'Sleep of the Dragon',
  'demo.tenmon-06.subtitle': 'Tenmon album #6 — hard bop',
  'demo.tenmon-07.title': 'The Invisible Bridge',
  'demo.tenmon-07.subtitle': 'Tenmon album #7 — Afro-Cuban / Latin jazz',
  'demo.tenmon-08.title': 'Between Light and Shadow',
  'demo.tenmon-08.subtitle': 'Tenmon album #8 — two-chord modal jazz vamp',
  'demo.tenmon-09.title': 'Crossing the Milky Way',
  'demo.tenmon-09.subtitle': 'Tenmon album #9 — up-tempo swing',
  'demo.tenmon-10.title': 'Endless Question',
  'demo.tenmon-10.subtitle': 'Tenmon album #10 — rubato ballad epilogue',

  'modal.close': 'Close',

  'mixer.track': 'Track',
  'mixer.addTrack': '+ Add',
  'mixer.mute.title': 'Mute',
  'mixer.solo.title': 'Solo',
  'mixer.delete.title': 'Delete Track',
  'mixer.delete.confirm': 'Delete track "{name}"?',

  'division.2beat': '2 Beats',
  'division.1beat': '1 Beat',
  'division.dotted8': 'Dotted 8th',
  'division.8': '8th',
  'division.triplet8': 'Triplet 8th',
  'division.16': '16th',
  'ctl.delayNote': 'Note',

  'song.intro': 'Arrange scenes vertically to build the song\'s structure. Each cell is the pattern (A–D) that track plays. Playing in "Song" mode performs them top to bottom.',
  'song.sceneHeader': 'Scene',
  'song.barsHeader': 'Bars',
  'song.emptySuffix': ' (empty)',
  'song.duplicate': 'Duplicate',
  'song.moveUp': '↑',
  'song.moveDown': '↓',
  'song.delete': '×',
  'toast.sceneMinimum': 'At least one scene is required',
  'song.addScene': '+ Add Scene',
  'song.total': '{bars} bars total / about {min}m {sec}s ({bpm} BPM)',

  'ctl.waveform': 'Wave',
  'ctl.subWaveform': 'Sub Wave',
  'ctl.filterModel': 'Model',
  'ctl.filterType': 'Type',
  'ctl.slope': 'Slope',
  'ctl.sync': 'Sync',
  'ctl.modTarget': 'Mod Target',
  'ctl.voiceMode': 'Mode',
  'ctl.arpMode': 'Mode',
  'ctl.drumVoice': 'Voice',
  'filterModel.ladder': 'Ladder (Thick)',
  'unit.perBeat': '/beat',
  'drum.preview': '▶ Preview',
  'lfoDiv.bar1': '1 Bar',
  'lfoDiv.beat2': '2 Beats',
  'lfoDiv.beat1': '1 Beat',
  'lfoDiv.beat0_5': '1/2 Beat',
  'lfoDiv.beat0_25': '1/4 Beat',
  'lfoDiv.triplet': 'Triplet',

  'analyzer.switchDisplay': 'Switch display',

  'roll.slotTitle': 'Pattern {letter}',
  'roll.lengthOption': '{steps} steps ({bars} bars)',
  'roll.length': 'Length',
  'notelen.16': '16th',
  'notelen.8': '8th',
  'notelen.4': 'Quarter',
  'notelen.2': 'Half',
  'notelen.whole': 'Whole',
  'roll.inputLength': 'Input Length',
  'roll.velocity': 'Velocity',
  'roll.copy': 'Copy',
  'roll.copy.title': 'Copy this pattern',
  'roll.paste': 'Paste',
  'roll.paste.title': 'Paste the copied pattern',
  'roll.undo': 'Undo',
  'roll.clear': 'Clear',
  'roll.clear.title': 'Erase all notes in this pattern',
  'roll.zoomOut.title': 'Zoom Out',
  'roll.zoomIn.title': 'Zoom In',
  'toast.patternCopied': 'Pattern copied',
  'toast.patternPasted': 'Pattern pasted',

  'patch.searchPlaceholder': 'Search tones…',
  'patch.save': '+ Save Tone',
  'patch.namePrompt': 'Enter a name for this tone',
  'toast.patchSaved': 'Saved "{name}"',
  'patch.empty': 'No matching tones',
  'patch.delete.title': 'Delete',
  'patch.delete.confirm': 'Delete "{name}"?',

  // Category names
  'category.BASS': 'Bass',
  'category.LEAD': 'Lead',
  'category.PAD': 'Pad',
  'category.KEYS': 'Keys',
  'category.PLUCK_BELL': 'Pluck / Bell',
  'category.BRASS_STRINGS': 'Brass / Strings',
  'category.SEQ_ARP': 'Seq / Arp',
  'category.SFX': 'SFX',
  'category.DRUM': 'Drum',
  'category.MY_PATCH': 'My Patch',

  // Factory preset names
  'preset.bass_analog': 'Analog Bass',
  'preset.bass_acid': 'Acid 303',
  'preset.bass_sub': 'Deep Sub',
  'preset.bass_reese': 'Reese Bass',
  'preset.bass_fm': 'FM Bass',
  'preset.bass_pluck': 'Pluck Bass',
  'preset.bass_growl': 'Growl Bass',
  'preset.lead_super': 'Super Saw Lead',
  'preset.lead_saw': 'Classic Saw Lead',
  'preset.lead_square': 'Hollow Square',
  'preset.lead_sync': 'Sync Lead',
  'preset.lead_fm': 'FM Lead',
  'preset.lead_flute': 'Soft Flute',
  'preset.lead_chip': 'Chiptune Lead',
  'preset.lead_whistle': 'Sine Whistle',
  'preset.pad_warm': 'Warm Pad',
  'preset.pad_glass': 'Glass Pad',
  'preset.pad_choir': 'Choir Aah',
  'preset.pad_sweep': 'Sweep Pad',
  'preset.pad_dark': 'Dark Drone',
  'preset.pad_shimmer': 'Shimmer Air',
  'preset.keys_ep': 'Electric Piano',
  'preset.keys_clav': 'Clavinet',
  'preset.keys_organ': 'Drawbar Organ',
  'preset.keys_house': 'House Piano',
  'preset.keys_toy': 'Toy Box',
  'preset.pluck_synth': 'Synth Pluck',
  'preset.pluck_koto': 'Koto',
  'preset.bell_glocken': 'Glockenspiel',
  'preset.bell_tubular': 'Tubular Bell',
  'preset.bell_metal': 'Metal Ring',
  'preset.pluck_marimba': 'Marimba',
  'preset.brass_synth': 'Synth Brass',
  'preset.brass_stab': 'Brass Stab',
  'preset.strings_ensemble': 'String Ensemble',
  'preset.strings_solo': 'Solo Strings',
  'preset.seq_pulse': 'Pulse Sequence',
  'preset.seq_blip': 'Blip Arp',
  'preset.seq_dust': 'Dust Motion',
  'preset.sfx_riser': 'Riser',
  'preset.sfx_laser': 'Laser Zap',
  'preset.sfx_wind': 'Wind Noise',
  'preset.sfx_impact': 'Impact Hit',
  'preset.dr_kick': 'Kick 909',
  'preset.dr_kick808': 'Kick 808',
  'preset.dr_kick_tight': 'Kick Tight',
  'preset.dr_snare': 'Snare',
  'preset.dr_snare_rim': 'Rim Shot',
  'preset.dr_clap': 'Hand Clap',
  'preset.dr_hat_closed': 'Hat Closed',
  'preset.dr_hat_open': 'Hat Open',
  'preset.dr_tom_low': 'Tom Low',
  'preset.dr_tom_mid': 'Tom Mid',
  'preset.dr_tom_high': 'Tom High',
  'preset.dr_crash': 'Crash',
  'preset.dr_ride': 'Ride',
  'preset.dr_cowbell': 'Cowbell',
  'preset.dr_shaker': 'Shaker',
  'preset.dr_clave': 'Clave',

  // Synth panel: module headings
  'module.mixerMod': 'Mixer / Mod',
  'module.filter': 'Filter',
  'module.voice': 'Voice',
  'module.fxSend': 'FX Send',
  'module.arp': 'Arpeggiator',
  'module.drumVoiceGroup': 'Drum Voice',
  'module.ampEg': 'Amp EG',
  'module.filterEg': 'Filter EG',

  // Synth panel: knob labels
  'knob.octave': 'Octave',
  'knob.semi': 'Semi',
  'knob.detune': 'Detune',
  'knob.level': 'Level',
  'knob.pulseWidth': 'P.Width',
  'knob.spread': 'Spread',
  'knob.oscMix': 'OSC Mix',
  'knob.fm': 'FM',
  'knob.subLevel': 'Sub Lv',
  'knob.subOctave': 'Sub Oct',
  'knob.noiseLevel': 'Noise Lv',
  'knob.cutoff': 'Cutoff',
  'knob.reso': 'Reso',
  'knob.drive': 'Drive',
  'knob.egAmount': 'EG Amt',
  'knob.keyTrack': 'Key Trk',
  'knob.velToCut': 'Vel→Cut',
  'knob.attack': 'Attack',
  'knob.decay': 'Decay',
  'knob.sustain': 'Sustain',
  'knob.release': 'Release',
  'knob.rate': 'Rate',
  'knob.amount': 'Amount',
  'knob.fadeIn': 'Fade In',
  'knob.glide': 'Glide',
  'knob.bend': 'Bend',
  'knob.velToAmp': 'Vel→Amp',
  'knob.modAmount': 'MOD Amt',
  'knob.volume': 'Volume',
  'knob.pan': 'Pan',
  'knob.chorus': 'Chorus',
  'knob.delay': 'Delay',
  'knob.reverb': 'Reverb',
  'knob.octaves': 'Octaves',
  'knob.gate': 'Gate',
  'knob.swing': 'Swing',
  'knob.tune': 'Tune',
  'knob.tone': 'Tone',
  'knob.snap': 'Snap',

  // Synth panel: toggle labels
  'toggle.ringMod': 'Ring Mod',
  'toggle.oscSync': 'Osc Sync',
  'toggle.tempoSync': 'Tempo Sync',
  'toggle.keyRetrig': 'Key Retrig',
  'toggle.arpOn': 'ARP ON',
  'toggle.latch': 'Latch',

  // Synth panel: dropdown options
  'wave.saw': 'Saw',
  'wave.square': 'Square',
  'wave.pulse': 'Pulse',
  'wave.triangle': 'Triangle',
  'wave.sine': 'Sine',
  'wave.superSaw': 'Super Saw',
  'wave.noise': 'Noise',
  'wave.sampleHold': 'S&H',
  'filterType.lowpass': 'Low Pass',
  'filterType.highpass': 'High Pass',
  'filterType.bandpass': 'Band Pass',
  'filterType.notch': 'Notch',
  'lfoTarget.off': 'Off',
  'lfoTarget.pitch': 'Pitch',
  'lfoTarget.osc2Pitch': 'OSC2 Pitch',
  'lfoTarget.pulseWidth': 'Pulse Width',
  'lfoTarget.cutoff': 'Cutoff',
  'lfoTarget.amp': 'Amp',
  'lfoTarget.pan': 'Pan',
  'lfoTarget.fmAmount': 'FM Amount',
  'voiceMode.poly': 'Poly',
  'voiceMode.mono': 'Mono',
  'voiceMode.legato': 'Legato',
  'modTarget.off': 'Off',
  'modTarget.lfo1Depth': 'LFO1 Depth',
  'modTarget.lfo2Depth': 'LFO2 Depth',
  'modTarget.cutoff': 'Cutoff',
  'arpMode.up': 'Up',
  'arpMode.down': 'Down',
  'arpMode.updown': 'Up/Down',
  'arpMode.random': 'Random',
  'arpMode.order': 'Order',
  'arpMode.chord': 'Chord',
  'drumOpt.kickAnalog': 'Kick (Analog)',
  'drumOpt.kick808': 'Kick (808 Deep)',
  'drumOpt.snare': 'Snare',
  'drumOpt.rim': 'Rim Shot',
  'drumOpt.clap': 'Hand Clap',
  'drumOpt.hatClosed': 'Hi-Hat Closed',
  'drumOpt.hatOpen': 'Hi-Hat Open',
  'drumOpt.tomLow': 'Tom Low',
  'drumOpt.tomMid': 'Tom Mid',
  'drumOpt.tomHigh': 'Tom High',
  'drumOpt.crash': 'Crash Cymbal',
  'drumOpt.ride': 'Ride Cymbal',
  'drumOpt.cowbell': 'Cowbell',
  'drumOpt.shaker': 'Shaker',
  'drumOpt.clave': 'Clave',
  'ctl.noiseType': 'Noise',
  'noiseType.white': 'White',
  'noiseType.pink': 'Pink',
  'ctl.modWheel': 'MOD Wheel',

  // Patch browser: misc
  'patch.categoryAll': 'ALL',
  'patch.customSuffix': ' Custom',
};

registerStrings(ja, en);
