import { registerStrings } from './i18n';

const ja = {
  'lang.toggle': 'EN',
  'loading': '読み込み中…',
  'boot.error': 'お使いのブラウザは AudioWorklet に対応していないため起動できません。<br>最新の Chrome / Edge / Firefox / Safari をお使いください。',

  'transport.play.title': '再生 / 停止（スペースキー）',
  'transport.stop.title': '停止＆全音消音',
  'transport.rec.title': 'リアルタイム録音（WAV）',
  'mode.pattern': 'パターン',
  'mode.song': 'ソング',
  'tap.title': 'タップテンポ',
  'metro.title': 'メトロノーム',
  'action.exportWav': 'WAV書出',
  'action.exportMidi': 'MIDI書出',
  'action.save': '保存',
  'action.load': '読込',
  'action.help': '？',

  'tab.synth': 'シンセ',
  'tab.master': 'マスターFX',
  'tab.song': 'ソング構成',

  'addTrack.title': 'トラックを追加：音色を選択',

  'toast.tempo': 'テンポ: {bpm} BPM',
  'toast.recordSaved': '録音を WAV で保存しました',
  'toast.noRecordData': '録音データがありません',
  'toast.recording': '録音中… もう一度押すと停止して WAV を保存します',
  'toast.recordUnavailable': 'この環境では録音を開始できませんでした',

  'export.info': 'オフラインレンダリングで高品質な WAV（24bit）を書き出します。リアルタイム録音と違い音切れがなく、実時間より短時間で完了します。',
  'export.bars': '小節数',
  'export.repeat': '繰り返し',
  'export.sampleRate': 'サンプルレート',
  'export.rendering': 'レンダリング中…',
  'export.done': '完了しました',
  'export.failed': '失敗しました: {err}',
  'export.go': '書き出す',
  'export.modalTitle': 'WAV 書き出し',
  'toast.wavExported': 'WAV を書き出しました',
  'toast.midiExported': 'MIDI ファイルを書き出しました',
  'toast.midiExportFailed': 'MIDI 書き出しに失敗しました: {err}',
  'toast.songSaved': '曲データを保存しました',
  'toast.songLoaded': '曲データを読み込みました',
  'toast.loadFailed': '読み込みに失敗しました: {err}',

  'status.midiConnected': 'MIDI: {names}',
  'status.midiDisconnected': 'MIDI: 未接続',
  'status.keyboardBase': 'キーボード基準: C{oct}（← →で変更）',
  'status.hints': 'Space: 再生/停止 ・ Ctrl+Z: 元に戻す ・ Alt+クリック: ノート削除',

  'help.basics.heading': '基本操作',
  'help.basics.play': '<b>演奏</b>：画面下の鍵盤、PCキーボード（Z S X D C… / Q 2 W 3 E…）、MIDIキーボード。',
  'help.basics.octave': '<b>オクターブ</b>：← → キー、または OCT ボタン。',
  'help.basics.input': '<b>打ち込み</b>：ピアノロールをクリックでノート追加。右端をドラッグで長さ変更、ドラッグで移動、Alt+クリックまたは右クリックで削除。',
  'help.basics.velocity': '<b>ベロシティ</b>：ピアノロール下部のレーンを上下ドラッグ。',
  'help.basics.pattern': '<b>パターン</b>：A〜D の 4 スロットを切り替えて別フレーズを作れます。',
  'help.basics.song': '<b>ソング</b>：「ソング構成」タブでシーンを並べ、トランスポートを「ソング」に切り替えて再生。',
  'help.tone.heading': '音づくり',
  'help.tone.osc': '<b>OSC</b>：波形・オクターブ・デチューン。Super Saw は 7 基のノコギリ波を重ねた厚い音。',
  'help.tone.filter': '<b>FILTER</b>：Ladder は独特の粘りがあるアナログ風、Clean SVF は素直な特性。',
  'help.tone.lfo': '<b>LFO</b>：テンポ同期に切り替えると BPM に追従します。',
  'help.tone.save': '<b>音色保存</b>：ブラウザ内に保存され、次回起動時も残ります。',
  'help.analyzer.heading': 'アナライザー',
  'help.analyzer.top': '画面最上部にマスター出力を常時表示します。左のラベルをクリックすると「波形＋スペクトラム → スペクトラム → 波形」の順に切り替わります（選択は記憶されます）。',
  'help.analyzer.meter': '右側は L / R のピークメーター。白い線はピークホールド、数値は dBFS です。0.0 に近づくと赤くなるので、書き出し前の音量確認に使えます。',
  'help.export.heading': '書き出し',
  'help.export.wav': '<b>WAV書出</b>：オフラインレンダリングで高音質・音切れなしの WAV を生成。',
  'help.export.midi': '<b>MIDI書出</b>：他の DAW に読み込める標準MIDIファイル。',
  'help.export.save': '<b>保存 / 読込</b>：曲データ（JSON）。作業内容はブラウザにも自動保存されます。',
  'help.license.heading': 'ライセンス',
  'help.license.text': '音はすべてコード生成（サンプル音源不使用）。作った曲の権利は制作者であるあなたのものです。商用利用も自由です。',
  'help.title': '使い方',
  'help.reloadDemo': 'デモ曲を読み込み直す',
  'confirm.reloadDemo': '現在の曲は失われます。よろしいですか？',

  'modal.close': '閉じる',

  'mixer.track': 'トラック',
  'mixer.addTrack': '＋ 追加',
  'mixer.mute.title': 'ミュート',
  'mixer.solo.title': 'ソロ',
  'mixer.delete.title': 'トラックを削除',
  'mixer.delete.confirm': 'トラック「{name}」を削除しますか？',

  'division.2beat': '2拍',
  'division.1beat': '1拍',
  'division.dotted8': '付点8分',
  'division.8': '8分',
  'division.triplet8': '3連8分',
  'division.16': '16分',
  'ctl.delayNote': '音符',

  'song.intro': 'シーンを縦に並べて曲の構成を作ります。各セルはトラックが鳴らすパターン（A〜D）です。「ソング」モードで再生すると上から順に演奏されます。',
  'song.sceneHeader': 'シーン',
  'song.barsHeader': '小節',
  'song.emptySuffix': '（空）',
  'song.duplicate': '複製',
  'song.moveUp': '↑',
  'song.moveDown': '↓',
  'song.delete': '×',
  'toast.sceneMinimum': 'シーンは最低1つ必要です',
  'song.addScene': '＋ シーンを追加',
  'song.total': '全 {bars} 小節 / 約 {min}分{sec}秒（{bpm} BPM）',

  'ctl.waveform': '波形',
  'ctl.subWaveform': 'SUB波形',
  'ctl.filterModel': 'モデル',
  'ctl.filterType': 'タイプ',
  'ctl.slope': 'スロープ',
  'ctl.sync': '同期',
  'ctl.modTarget': '変調先',
  'ctl.voiceMode': 'モード',
  'ctl.arpMode': 'モード',
  'ctl.drumVoice': '音色',
  'filterModel.ladder': 'Ladder (太い)',
  'unit.perBeat': '/拍',
  'drum.preview': '▶ 試聴',
  'lfoDiv.bar1': '1小節',
  'lfoDiv.beat2': '2拍',
  'lfoDiv.beat1': '1拍',
  'lfoDiv.beat0_5': '1/2拍',
  'lfoDiv.beat0_25': '1/4拍',
  'lfoDiv.triplet': '3連符',

  'analyzer.switchDisplay': '表示を切り替え',

  'roll.slotTitle': 'パターン {letter}',
  'roll.lengthOption': '{steps} steps ({bars}小節)',
  'roll.length': '長さ',
  'notelen.16': '16分',
  'notelen.8': '8分',
  'notelen.4': '4分',
  'notelen.2': '2分',
  'notelen.whole': '全音符',
  'roll.inputLength': '入力長',
  'roll.velocity': '強さ',
  'roll.copy': 'コピー',
  'roll.copy.title': 'このパターンをコピー',
  'roll.paste': '貼付',
  'roll.paste.title': 'コピーしたパターンを貼り付け',
  'roll.undo': '元に戻す',
  'roll.clear': 'クリア',
  'roll.clear.title': 'このパターンのノートを全消去',
  'roll.zoomOut.title': '縮小',
  'roll.zoomIn.title': '拡大',
  'toast.patternCopied': 'パターンをコピーしました',
  'toast.patternPasted': 'パターンを貼り付けました',

  'patch.searchPlaceholder': '音色を検索…',
  'patch.save': '＋ 音色を保存',
  'patch.namePrompt': '音色名を入力してください',
  'toast.patchSaved': '「{name}」を保存しました',
  'patch.empty': '該当する音色がありません',
  'patch.delete.title': '削除',
  'patch.delete.confirm': '「{name}」を削除しますか？',
};

const en: typeof ja = {
  'lang.toggle': 'JP',
  'loading': 'Loading…',
  'boot.error': 'Your browser does not support AudioWorklet, so this app cannot start.<br>Please use a recent version of Chrome / Edge / Firefox / Safari.',

  'transport.play.title': 'Play / Stop (Space)',
  'transport.stop.title': 'Stop & Silence All',
  'transport.rec.title': 'Real-Time Recording (WAV)',
  'mode.pattern': 'Pattern',
  'mode.song': 'Song',
  'tap.title': 'Tap Tempo',
  'metro.title': 'Metronome',
  'action.exportWav': 'Export WAV',
  'action.exportMidi': 'Export MIDI',
  'action.save': 'Save',
  'action.load': 'Load',
  'action.help': '?',

  'tab.synth': 'Synth',
  'tab.master': 'Master FX',
  'tab.song': 'Song Structure',

  'addTrack.title': 'Add Track: Choose a Tone',

  'toast.tempo': 'Tempo: {bpm} BPM',
  'toast.recordSaved': 'Recording saved as WAV',
  'toast.noRecordData': 'There is no recorded data',
  'toast.recording': 'Recording… press again to stop and save the WAV',
  'toast.recordUnavailable': 'Recording could not be started in this environment',

  'export.info': 'Renders a high-quality 24-bit WAV offline. Unlike real-time recording there are no dropouts, and it finishes faster than real time.',
  'export.bars': 'Bars',
  'export.repeat': 'Repeats',
  'export.sampleRate': 'Sample Rate',
  'export.rendering': 'Rendering…',
  'export.done': 'Done',
  'export.failed': 'Failed: {err}',
  'export.go': 'Export',
  'export.modalTitle': 'Export WAV',
  'toast.wavExported': 'WAV exported',
  'toast.midiExported': 'MIDI file exported',
  'toast.midiExportFailed': 'MIDI export failed: {err}',
  'toast.songSaved': 'Song data saved',
  'toast.songLoaded': 'Song data loaded',
  'toast.loadFailed': 'Failed to load: {err}',

  'status.midiConnected': 'MIDI: {names}',
  'status.midiDisconnected': 'MIDI: Not connected',
  'status.keyboardBase': 'Keyboard base: C{oct} (change with ← →)',
  'status.hints': 'Space: Play/Stop ・ Ctrl+Z: Undo ・ Alt+click: Delete note',

  'help.basics.heading': 'Basic Controls',
  'help.basics.play': '<b>Play</b>: The on-screen keyboard, your computer keyboard (Z S X D C… / Q 2 W 3 E…), or a MIDI keyboard.',
  'help.basics.octave': '<b>Octave</b>: The ← → keys, or the OCT buttons.',
  'help.basics.input': '<b>Programming notes</b>: Click the piano roll to add a note. Drag the right edge to resize, drag to move, Alt+click or right-click to delete.',
  'help.basics.velocity': '<b>Velocity</b>: Drag up/down in the lane below the piano roll.',
  'help.basics.pattern': '<b>Patterns</b>: Switch between the 4 slots A–D to build different phrases.',
  'help.basics.song': '<b>Song</b>: Arrange scenes in the "Song Structure" tab, then switch the transport to "Song" to play them in order.',
  'help.tone.heading': 'Sound Design',
  'help.tone.osc': '<b>OSC</b>: Waveform, octave, and detune. Super Saw layers 7 sawtooth waves for a thick sound.',
  'help.tone.filter': '<b>FILTER</b>: Ladder has a distinctive, sticky analog character; Clean SVF is more neutral.',
  'help.tone.lfo': '<b>LFO</b>: Switch to tempo sync to follow the BPM.',
  'help.tone.save': '<b>Saving tones</b>: Saved in the browser and still there next time you open the app.',
  'help.analyzer.heading': 'Analyzer',
  'help.analyzer.top': 'The master output is always shown at the top of the screen. Click the label on the left to cycle through "waveform + spectrum → spectrum → waveform" (your choice is remembered).',
  'help.analyzer.meter': 'On the right are the L / R peak meters. The white line is the peak hold, and the number is in dBFS. It turns red as it approaches 0.0, which is handy for checking levels before exporting.',
  'help.export.heading': 'Export',
  'help.export.wav': '<b>Export WAV</b>: Renders a high-quality, dropout-free WAV offline.',
  'help.export.midi': '<b>Export MIDI</b>: A standard MIDI file you can load into other DAWs.',
  'help.export.save': '<b>Save / Load</b>: Song data (JSON). Your work is also auto-saved in the browser.',
  'help.license.heading': 'License',
  'help.license.text': 'All sound is generated by code (no sample audio used). The songs you make are yours — commercial use is fine too.',
  'help.title': 'How to Use',
  'help.reloadDemo': 'Reload Demo Song',
  'confirm.reloadDemo': 'The current song will be lost. Continue?',

  'modal.close': 'Close',

  'mixer.track': 'Track',
  'mixer.addTrack': '+ Add',
  'mixer.mute.title': 'Mute',
  'mixer.solo.title': 'Solo',
  'mixer.delete.title': 'Delete Track',
  'mixer.delete.confirm': 'Delete track "{name}"?',

  'division.2beat': '2 Beats',
  'division.1beat': '1 Beat',
  'division.dotted8': 'Dotted 8th',
  'division.8': '8th',
  'division.triplet8': 'Triplet 8th',
  'division.16': '16th',
  'ctl.delayNote': 'Note',

  'song.intro': 'Arrange scenes vertically to build the song\'s structure. Each cell is the pattern (A–D) that track plays. Playing in "Song" mode performs them top to bottom.',
  'song.sceneHeader': 'Scene',
  'song.barsHeader': 'Bars',
  'song.emptySuffix': ' (empty)',
  'song.duplicate': 'Duplicate',
  'song.moveUp': '↑',
  'song.moveDown': '↓',
  'song.delete': '×',
  'toast.sceneMinimum': 'At least one scene is required',
  'song.addScene': '+ Add Scene',
  'song.total': '{bars} bars total / about {min}m {sec}s ({bpm} BPM)',

  'ctl.waveform': 'Wave',
  'ctl.subWaveform': 'Sub Wave',
  'ctl.filterModel': 'Model',
  'ctl.filterType': 'Type',
  'ctl.slope': 'Slope',
  'ctl.sync': 'Sync',
  'ctl.modTarget': 'Mod Target',
  'ctl.voiceMode': 'Mode',
  'ctl.arpMode': 'Mode',
  'ctl.drumVoice': 'Voice',
  'filterModel.ladder': 'Ladder (Thick)',
  'unit.perBeat': '/beat',
  'drum.preview': '▶ Preview',
  'lfoDiv.bar1': '1 Bar',
  'lfoDiv.beat2': '2 Beats',
  'lfoDiv.beat1': '1 Beat',
  'lfoDiv.beat0_5': '1/2 Beat',
  'lfoDiv.beat0_25': '1/4 Beat',
  'lfoDiv.triplet': 'Triplet',

  'analyzer.switchDisplay': 'Switch display',

  'roll.slotTitle': 'Pattern {letter}',
  'roll.lengthOption': '{steps} steps ({bars} bars)',
  'roll.length': 'Length',
  'notelen.16': '16th',
  'notelen.8': '8th',
  'notelen.4': 'Quarter',
  'notelen.2': 'Half',
  'notelen.whole': 'Whole',
  'roll.inputLength': 'Input Length',
  'roll.velocity': 'Velocity',
  'roll.copy': 'Copy',
  'roll.copy.title': 'Copy this pattern',
  'roll.paste': 'Paste',
  'roll.paste.title': 'Paste the copied pattern',
  'roll.undo': 'Undo',
  'roll.clear': 'Clear',
  'roll.clear.title': 'Erase all notes in this pattern',
  'roll.zoomOut.title': 'Zoom Out',
  'roll.zoomIn.title': 'Zoom In',
  'toast.patternCopied': 'Pattern copied',
  'toast.patternPasted': 'Pattern pasted',

  'patch.searchPlaceholder': 'Search tones…',
  'patch.save': '+ Save Tone',
  'patch.namePrompt': 'Enter a name for this tone',
  'toast.patchSaved': 'Saved "{name}"',
  'patch.empty': 'No matching tones',
  'patch.delete.title': 'Delete',
  'patch.delete.confirm': 'Delete "{name}"?',
};

registerStrings(ja, en);
